const fs=require("fs"),path=require("path");
const lexiconRoot=process.argv[2];
if(!lexiconRoot)throw new Error("Pass the temporary lexicon directory containing node-wordnet and wordnet-db.");
const WordNet=require(path.join(lexiconRoot,"node_modules/node-wordnet"));
const wordnet=new WordNet({dataDir:path.join(lexiconRoot,"node_modules/wordnet-db/dict")});
const source=fs.readFileSync(path.resolve(__dirname,"../src/word-data.ts"),"utf8"),rows=[];
for(const match of source.matchAll(/make\(("(?:[^"\\]|\\.)*"),(E|T),(\[\[.*\]\])\),/g)){const category=JSON.parse(match[1]),language=match[2]==="E"?"English":"Tagalog";for(const row of JSON.parse(match[3]))rows.push({category,language,row})}
const expected={Food:[13],Drinks:[13],Animals:[5],Countries:[15],Cities:[15],Sports:[4],Movies:[10],"TV Shows":[10],"Video Games":[6,4],Technology:[6,9],Jobs:[18],School:[6,9,18],Places:[15],Transportation:[6],Clothing:[6],"Household Objects":[6],Nature:[19,20,17,27],Music:[10,6],"Internet Culture":[10,4],Fantasy:[9,18],"Science & Space":[9,17,19,22],"Brands & Social Media":[14,6],Hobbies:[4],"Extreme Ideas":[9],"World Cities":[15],"Technology Brands":[14,6],"Social Media":[10,4],Space:[17,9],Science:[9,22],Health:[26,22],Weather:[19],"Ocean Life":[5],Travel:[4,15],Art:[6,4],Books:[10],Superpowers:[9],Mystery:[9,10],Camping:[4,6],Garden:[20,4],Farm:[4,6],Office:[6,4],Kitchen:[6],Bathroom:[6],Party:[4],Childhood:[28,4],Feelings:[12],Actions:[4],Sounds:[10,19],"Shapes & Colors":[25,7],Money:[21],Shopping:[4],Construction:[4,6],"Crime & Law":[10,4],History:[28,10],"Campus Life":[4,15],Programming:[9,4],"Board Games":[4],Photography:[4,6]};
const lookup=word=>new Promise(resolve=>wordnet.lookup(word,(error,result)=>resolve(error?[]:result||[])));
const clean=gloss=>{let value=gloss.replace(/;\s*".*$/s,"").replace(/\s+/g," ").trim();value=value.replace(/^\(([^)]+)\)\s*/,"In $1, ");return value.charAt(0).toUpperCase()+value.slice(1).replace(/[.; ]+$/,"")+"."};
const manual={
 Istanbul:"The largest city in Turkey, spanning Europe and Asia across the Bosporus Strait.",Mouse:"A handheld pointing device used to move a cursor and select items on a computer.",Phoenix:"A mythical bird that burns and is reborn from its own ashes.",Tesla:"An electric-vehicle and clean-energy company founded in the United States.","Placebo Effect":"A real change in symptoms caused by a person's expectations rather than an active treatment.",
 Shawarma:"Seasoned meat roasted on a vertical spit and served in thin slices, often in flatbread.",Churros:"Fried strips of dough coated with sugar, commonly served with a dipping sauce.",Gyoza:"Japanese dumplings filled with meat or vegetables and usually pan-fried.","Energy Drink":"A caffeinated beverage marketed to increase alertness and energy.","Root Beer":"A sweet carbonated drink traditionally flavored with roots and spices.",Matcha:"Finely ground green tea powder whisked into water or milk.",Kombucha:"A fermented tea drink made with a culture of bacteria and yeast.","Chai Latte":"A milk-based drink flavored with spiced black tea.",Mojito:"A cocktail made with rum, lime, mint, sugar, and soda water.","Boba Tea":"A tea-based drink containing chewy tapioca pearls.","Hot Cider":"Heated apple cider commonly flavored with cinnamon and other spices.",Horchata:"A sweet drink made from rice, seeds, or nuts and flavored with cinnamon.",
 "Boss Battle":"A major game encounter against a powerful enemy.","Power-Up":"An item or effect that temporarily improves a game character's abilities.",Respawn:"To return a game character to play after defeat.",Multiplayer:"A game mode in which more than one person plays together or against each other.",Leaderboard:"A ranked list of players based on scores or achievements.",Speedrun:"An attempt to finish a video game as quickly as possible.",Cutscene:"A non-interactive scene used to present a game's story.","Open World":"A game design that lets players freely explore a large environment.","Final Boss":"The last major enemy fought near the end of a game.","Loot Box":"A virtual container that gives randomized in-game rewards.","Game Over":"The state in which a game session ends after the player fails or runs out of chances.","Side Quest":"An optional mission separate from a game's main story.",Mana:"A resource used to cast spells or activate magical abilities in games.","Co-op":"A mode where players work together toward the same goal.","Hit Points":"A number representing how much damage a game character can survive.",Crafting:"The process of combining game materials to create items.","Skill Tree":"A branching system of abilities that players unlock over time.",DLC:"Downloadable content added to a game after its main release.",
 "Going Viral":"The rapid spread of online content to a very large audience.",Clickbait:"A sensational title or image designed mainly to attract clicks.","Reaction Video":"A video showing someone's response to other content or an event.",Thread:"A connected series of online posts or messages.",Lurker:"A person who reads an online community without usually posting.",Troll:"A person who deliberately provokes or upsets others online.",Screenshot:"A digital image capturing what is displayed on a screen.","Fan Edit":"A fan-made rearrangement or modification of existing media.",Unboxing:"A video or activity showing a product being opened and examined for the first time.",POV:"Point of view, or the perspective from which content is shown.",Influencer:"A person whose online audience can affect opinions or buying choices.",Username:"A name used to identify an account online.","Trending Page":"A page listing topics or content currently receiving unusual attention.",Emoji:"A small digital image used to express an idea, object, or emotion.",Podcast:"A series of spoken-audio episodes distributed online.",Rickroll:"An online prank that unexpectedly redirects someone to the song Never Gonna Give You Up.",Avatar:"A digital character or image representing a user online.",Gif:"A digital image format commonly used for short looping animations.",Notification:"An alert from an app or website about new activity or information.",DM:"A direct message sent privately between users online.",Feed:"A continuously updated stream of online posts or content.",Clicker:"A game built around repeated clicks or taps that generate progress.",Subscribe:"To sign up to regularly receive updates or content from an online source.",Vlogger:"A person who regularly creates and posts video blogs.",Spoilers:"Details that reveal important events or endings before someone experiences a story.",Ban:"A restriction that prevents a user from accessing a platform or community.",Shadowban:"A hidden restriction that reduces a user's visibility without clearly notifying them.",
 "Déjà Vu":"The feeling that a present experience has happened before.","Parallel Universe":"A hypothetical universe existing alongside our own with different events or conditions.","Collective Memory":"Shared memories and interpretations of the past held by a group.","Infinite Loop":"A sequence that repeats forever because its stopping condition is never reached.","Uncanny Valley":"Discomfort caused by a humanlike figure that appears almost, but not fully, realistic.","Moral Dilemma":"A situation requiring a choice between conflicting moral duties.","Time Perception":"The way a person experiences and judges the passage of time.","Quantum Entanglement":"A quantum link in which particles share correlated states even when separated.","Simulation Hypothesis":"The idea that experienced reality may be an artificial computer simulation.","Schrödinger's Cat":"A thought experiment illustrating quantum superposition through a cat treated as both alive and dead until observed.","Ship of Theseus":"A thought experiment asking whether an object remains the same after all its parts are replaced.","Fermi Paradox":"The conflict between the high probability of extraterrestrial life and the lack of clear evidence for it.","Existential Dread":"Deep anxiety about existence, freedom, death, or the absence of meaning.",Multiverse:"A hypothetical collection of multiple universes.",Epiphany:"A sudden realization or moment of clear understanding.",Singularity:"A point where ordinary rules fail, such as infinite density in physics or runaway technological change.","Lucid Dreaming":"Dreaming while aware that one is dreaming, sometimes with control over the dream.","Black Swan Event":"A rare and unexpected event with major consequences that seems explainable afterward.","Echo Chamber":"An environment where repeated similar opinions reinforce beliefs and limit opposing views.",Nihilism:"The belief that life or traditional values have no inherent meaning or objective foundation."
};
const englishFallback=(category,word,hints)=>{const h=hints.filter(Boolean).slice(0,2).join(" and "),types={Food:"food prepared with",Drinks:"drink made or served with",Animals:"animal characterized by",Countries:"country associated with",Cities:"city known for",Sports:"sport involving",Movies:"film concept involving","TV Shows":"television concept involving","Video Games":"video-game concept involving",Technology:"technology used for",Jobs:"occupation responsible for",School:"education term involving",Places:"place used for",Transportation:"form of transport using",Clothing:"garment designed with","Household Objects":"household object used with",Nature:"natural feature or event involving",Music:"music term involving","Internet Culture":"online term describing",Fantasy:"fantasy concept involving","Science & Space":"scientific concept involving","Brands & Social Media":"brand or platform associated with",Hobbies:"activity involving","Extreme Ideas":"concept concerning"};return `${word} is a ${types[category]||"term referring to"} ${h}.`};
const tagalogManual={
 Palabok:"Ang palabok ay pansit na may malapot na sarsang hipon at karaniwang nilalagyan ng itlog, chicharon, at iba pang sahog.","Buko Pandan":"Ang buko pandan ay malamig na panghimagas na may murang niyog, pandan jelly, cream, at gatas.","Puto Bumbong":"Ang puto bumbong ay lilang malagkit na bigas na pinasingawan sa tubong kawayan at nilalagyan ng niyog at asukal.",Mechado:"Ang mechado ay nilagang baka sa sarsang kamatis na may patatas, karot, at mga pampalasa.",
 "Tsokolate de Batirol":"Ang tsokolate de batirol ay mainit at makapal na inuming tablea na binabati gamit ang kahoy na panghalo.","Sago Shake":"Ang sago shake ay malamig na pinaghalong yelo, gatas o arnibal, at maliliit na perlas ng sago.","Kamias Juice":"Ang kamias juice ay maasim na inuming ginagawa mula sa katas ng bunga ng kamias.",Gulaman:"Ang gulaman ay malamig na inuming may agar jelly, arnibal, tubig, at yelo.",
 Paniki:"Ang paniki ay mammal na may pakpak at karaniwang lumilipad at naghahanap ng pagkain sa gabi.",Tamaraw:"Ang tamaraw ay maliit at mailap na ligaw na kalabaw na likas lamang sa Mindoro.",Balang:"Ang balang ay insektong may malalakas na paa sa pagtalon at maaaring dumami at sumira ng pananim.",Kalapati:"Ang kalapati ay ibong may bilugang katawan, maikling tuka, at malalakas na pakpak, na madalas makita sa mga lungsod.",
 "Istasyon ng Pulis":"Ang istasyon ng pulis ay tanggapan kung saan nagtatrabaho ang mga pulis at dinadala ang mga ulat o reklamo.","Istasyon ng Bumbero":"Ang istasyon ng bumbero ay gusaling kinalalagyan ng mga bumbero, fire truck, at kagamitang panugon sa sunog.",Tubigan:"Ang tubigan ay malawak o mababang lugar na palaging may tubig, gaya ng palaisdaan o latian.",Talon:"Ang talon ay bahagi ng ilog kung saan bumabagsak ang tubig mula sa mataas na bangin.",
 Huwes:"Ang huwes ay opisyal ng hukuman na namumuno sa paglilitis at nagpapasya ayon sa batas.",Parmasyutiko:"Ang parmasyutiko ay lisensiyadong propesyonal na naghahanda, nagsusuri, at nagbibigay ng gamot.",Manunulat:"Ang manunulat ay taong lumilikha ng akda tulad ng kuwento, sanaysay, tula, o aklat.",Tubero:"Ang tubero ay manggagawang nagkakabit at nagkukumpuni ng tubo, gripo, at daluyan ng tubig.",
 Dalampasigan:"Ang dalampasigan ay lupang nasa gilid ng dagat kung saan sumasalubong ang tubig at pampang.",Lawa:"Ang lawa ay malaking anyong tubig na napalilibutan ng lupa.",Koral:"Ang koral ay kolonya ng maliliit na hayop-dagat na bumubuo ng matigas na bahura.",Sapa:"Ang sapa ay maliit at mababaw na agos ng tubig na mas makitid kaysa ilog.",
 Skylab:"Ang skylab ay motorsiklong nilagyan ng malalapad na ekstensiyon upang magsakay ng maraming tao o karga, lalo na sa Mindanao.",Padyak:"Ang padyak ay bisikletang may sidecar na pinapaandar sa pamamagitan ng pagpedal.","Bangkang De-motor":"Ang bangkang de-motor ay maliit na sasakyang pantubig na pinapaandar ng makina.",Kotse:"Ang kotse ay maliit na sasakyang may apat na gulong na karaniwang ginagamit sa pribadong biyahe.",
 Suklay:"Ang suklay ay manipis na kagamitang may hanay ng ngipin para ayusin o alisin ang buhol ng buhok.",Sipilyo:"Ang sipilyo ay maliit na brush na ginagamit kasama ng toothpaste upang linisin ang ngipin.",Baso:"Ang baso ay bukas na sisidlang iniinuman ng tubig o ibang likido.",Posporo:"Ang posporo ay maliit na patpat na nagliliyab kapag kiniskis ang ulo nito sa magaspang na ibabaw.",
 Pamanhikan:"Ang pamanhikan ay tradisyong pagdalaw ng pamilya ng lalaki sa pamilya ng babae upang pormal na pag-usapan ang kasal.","Salo-salo":"Ang salo-salo ay pagtitipon kung saan magkakasamang kumakain at nag-uusap ang isang grupo.","Harana sa Bintana":"Ang harana sa bintana ay tradisyong pag-awit sa labas ng bahay upang manligaw.",Santacruzan:"Ang Santacruzan ay prusisyon tuwing Mayo na gumugunita sa paghahanap sa Banal na Krus.",
 Epal:"Ang epal ay taong nakikisali o nagpapapansin kahit hindi kailangan o hindi siya kabilang.",KSP:"Ang KSP ay daglat ng kulang sa pansin at tumutukoy sa taong laging naghahanap ng atensiyon.",Praning:"Ang praning ay taong labis na balisa, takot, o mapaghinala.",Taray:"Ang taray ay matapang, matalas, o kapansin-pansing asal at dating ng isang tao.",
 "Direktor ng Pelikula":"Ang direktor ng pelikula ay taong namamahala sa malikhaing pagbuo at pagkuha ng mga eksena sa pelikula.",Extra:"Ang extra ay aktor sa likuran ng eksena na karaniwang walang mahalagang linya.",Endorser:"Ang endorser ay taong pampublikong nagrerekomenda o kumakatawan sa isang produkto o tatak.","Viral Video":"Ang viral video ay bidyong mabilis na kumakalat at napapanood o naibabahagi ng napakaraming tao online.",
 "Bulong-Pari":"Ang Bulong-Pari ay larong pangkat kung saan palihim na ibinubulong ang pangalan ng manlalarong haharap sa parusa.","Tumbang Lata":"Ang Tumbang Lata ay larong paghagis ng pamato upang patumbahin ang latang binabantayan ng taya.","Sawsaw-Suka":"Ang Sawsaw-Suka ay larong kamay kung saan sinusubukang umiwas ng mga daliri bago maisara ang kamay ng taya.","Piko-piko":"Ang piko-piko ay larong pagtalon sa mga kahong iginuhit sa lupa nang hindi natatapakan ang mga guhit.",
 "ID ng Mag-aaral":"Ang ID ng mag-aaral ay kard na nagpapatunay sa pagkakakilanlan at pag-enrol ng isang estudyante.",Pambura:"Ang pambura ay gamit na nag-aalis ng marka ng lapis sa papel.","Flag Ceremony":"Ang flag ceremony ay pagtitipon para sa pagtataas ng watawat at pag-awit ng pambansang awit.",Pagsasanay:"Ang pagsasanay ay gawaing inuulit upang mapaunlad ang kaalaman o kasanayan.",
 Basketbolista:"Ang basketbolista ay manlalarong nakikipaglaro ng basketball bilang atleta.","Archer sa Palaso":"Ang archer ay taong nagpapana gamit ang busog upang tamaan ang isang target.","Gymnast sa Balance Beam":"Ang gymnast sa balance beam ay atletang gumagawa ng mga galaw sa makitid at mataas na baras.","Atleta sa Palarong Pambansa":"Ito ay mag-aaral na kumakatawan sa rehiyon sa pambansang paligsahang pampaaralan.",
 "Salubong sa Pasko ng Pagkabuhay":"Ang Salubong ay ritwal sa madaling-araw ng Easter Sunday na nagsasadula sa pagtatagpo nina Hesus at Maria.","Kaamulan Festival":"Ang Kaamulan ay pista sa Bukidnon na ipinagdiriwang ang kultura at tradisyon ng mga katutubong pangkat nito.","Pintados Festival":"Ang Pintados ay pista sa Tacloban na nagtatampok ng sayaw at disenyong katawan na hango sa mga sinaunang mandirigma.","Lanzones Festival":"Ang Lanzones Festival ay taunang pista sa Camiguin na nagdiriwang sa ani ng lanzones.",
 "Kaban ng Bigas":"Ang kaban ng bigas ay malaking kahon o sisidlan para sa pag-iimbak ng bigas.",Dampa:"Ang dampa ay maliit at payak na bahay na karaniwang yari sa magagaan na materyales.",Entreswelo:"Ang entreswelo ay mababang palapag sa pagitan ng unang palapag at pangunahing palapag ng isang lumang bahay.","Bintana ng Capiz":"Ang bintana ng Capiz ay bintanang may maliliit na panel na gawa sa manipis na kabibe ng capiz.",
 "Pagpapahinga sa Sala":"Ito ay pag-upo o paghiga sa sala upang mabawi ang lakas.","Kwentuhan sa Hapon":"Ito ay impormal na pag-uusap at pagbabahagi ng kuwento tuwing hapon.","Panonood ng Teleserye":"Ito ay pagsubaybay sa seryeng dramang ipinapalabas sa telebisyon.","Dasal Bago Matulog":"Ito ay pananalangin bago matulog upang magpasalamat o humingi ng gabay.",
 "Bohol Island":"Ang Bohol ay lalawigang pulo sa Central Visayas na kilala sa Chocolate Hills at Philippine tarsier.","Luneta Park":"Ang Luneta Park ay makasaysayang pampublikong parke sa Maynila kung saan matatagpuan ang Rizal Monument.",Bataan:"Ang Bataan ay lalawigan sa Central Luzon na mahalaga sa kasaysayan ng Ikalawang Digmaang Pandaigdig.","Apo Reef":"Ang Apo Reef ay malaking coral reef system sa Occidental Mindoro at isang mahalagang tirahan ng mga hayop-dagat."
};
const tagalogTemplate=(category,word,hints)=>{const h=hints.filter(Boolean).slice(0,3).join(", ");const templates={Pagkain:`Ang ${word} ay pagkain o putahe na may ${h}.`,Inumin:`Ang ${word} ay inuming may o ginagawa mula sa ${h}.`,Hayop:`Ang ${word} ay hayop na may katangiang ${h}.`,Lugar:`Ang ${word} ay pook na ginagamit o inilalarawan bilang ${h}.`,Trabaho:`Ang ${word} ay taong gumagawa ng trabahong ${h}.`,Kalikasan:`Ang ${word} ay likas na anyo o pangyayaring may ${h}.`,Sasakyan:`Ang ${word} ay sasakyang ginagamit sa paglalakbay gamit ang ${h}.`,Bagay:`Ang ${word} ay kagamitang ginagamit para sa ${h}.`,"Kulturang Pilipino":`Ang ${word} ay kaugaliang Pilipino na ginagawa sa ${h}.`,"Pinoy Slang":`Ang ${word} ay impormal na salitang tumutukoy sa ${h}.`,"Artista at Aliwan":`Ang ${word} ay tao, palabas, o gawaing pang-aliwan tungkol sa ${h}.`,Artista:`Si ${word} ay Pilipinong personalidad na kilala sa ${h}.`,"Larong Pinoy":`Ang ${word} ay larong Pilipino na gumagamit ng ${h}.`,Paaralan:`Ang ${word} ay tao, gamit, lugar, o gawaing pampaaralan para sa ${h}.`,Palakasan:`Ang ${word} ay laro, atleta, o gawaing pampalakasan na gumagamit ng ${h}.`,"Pista at Tradisyon":`Ang ${word} ay pista o tradisyong ipinagdiriwang sa pamamagitan ng ${h}.`,Bahay:`Ang ${word} ay bahagi o gamit sa bahay para sa ${h}.`,"Pang-araw-araw na Buhay":`Ang ${word} ay pang-araw-araw na gawaing ginagawa para sa ${h}.`,"Mga Lugar sa Pilipinas":`Ang ${word} ay lugar sa Pilipinas na may ${h}.`,"Brands & Logos":`Ang ${word} ay tatak o logo na may ${h}.`,"Colors & Shapes":`Ang ${word} ay kulay, hugis, o padrong may ${h}.`,"Emotions & Feelings":`Ang ${word} ay damdaming nararanasan bilang ${h}.`,"Kitchen & Cooking":`Ang ${word} ay kagamitan o paraan sa pagluluto para sa ${h}.`,"Movies & TV Shows":`Ang ${word} ay palabas, tauhan, o terminong pansine tungkol sa ${h}.`,"Music & Bands":`Ang ${word} ay tunog, instrumento, o terminong pangmusika na may ${h}.`,"Science & Technology":`Ang ${word} ay kasangkapan, proseso, o konseptong pang-agham tungkol sa ${h}.`,Superheroes:`Ang ${word} ay bayani, kapangyarihan, o konseptong superhero na may ${h}.`,"Video Games":`Ang ${word} ay gamit, kilos, o konsepto sa video game para sa ${h}.`};return templates[category]||`Ang ${word} ay katawagang tumutukoy sa ${h}.`};
(async()=>{const direct={};let found=0,fallback=0;for(const {category,language,row} of rows){const [word,...rest]=row,hints=rest.slice(0,3),existing=row[4];if(existing)continue;const key=`${language}|${category}|${word}`;if(language==="Tagalog"){direct[key]=tagalogManual[word]||tagalogTemplate(category,word,hints);fallback++;continue}if(manual[word]){direct[key]=manual[word];found++;continue}let senses=await lookup(word.replace(/-/g," "));if(!senses.length&&word.endsWith("s"))senses=await lookup(word.slice(0,-1));if(senses.length){const wanted=expected[category]||[],ranked=senses.map((sense,index)=>({sense,index,score:(sense.pos==="n"?4:0)+(wanted.includes(sense.lexFilenum)?12-wanted.indexOf(sense.lexFilenum):0)-index*.03})).sort((a,b)=>b.score-a.score);direct[key]=clean(ranked[0].sense.gloss);found++}else{direct[key]=englishFallback(category,word,hints);fallback++}}
 const output=`// Generated from WordNet 3.1 plus word-specific cultural fallbacks.\nexport const directMeanings:Record<string,string>=${JSON.stringify(direct,null,1)};\n`;
 fs.writeFileSync(path.resolve(__dirname,"../src/direct-meanings.ts"),output);console.log(`Direct meanings: ${Object.keys(direct).length}; WordNet: ${found}; contextual: ${fallback}`)})().catch(error=>{console.error(error);process.exitCode=1});
