const tagalogCategories = {
  "Pagkain": [
    ["Adobo","Toyo","Asim","Sukang Iloko"],
    ["Sinigang","Maasim","Sampalok","Sinigang sa miso"],
    ["Lechon","Balat","Sarsa","Crispy"],
    ["Kare-Kare","Mani","Bagoong","Oxtail"],
    ["Tinola","Luya","Sili dahon","Tanglad"],
    ["Sisig","Sizzling","Maskara","Pampanga"],
    ["Lumpia","Balot","Lumpiang shanghai","Sotanghon"],
    ["Halo-halo","Yelo","Leche flan","Ube"],
    ["Balut","Itik","Sisiw","18 days"],
    ["Taho","Arnibal","Umaga","Silken tofu"],
    ["Pancit","Mahaba","Bihon","Palabok"],
    ["Bibingka","Pasko","Palayok","Galapong"],
    ["Champorado","Tsokolate","Tuyo","Malagkit"],
    ["Turon","Saging","Langka","Lumpiang"],
    ["Laing","Gata","Dahon ng gabi","Bicol"],
    ["Dinuguan","Maitim na sabaw","Suka at dugo ng baboy","Pares sa puto"],
    ["Bulalo","Malinamnam na utak sa buto","Nilagang baka","Mainit na sabaw sa Tagaytay"],
    ["Longganisa","Bawang at pampatamis","Almusal sa umaga","Pritong sausage"],
    ["Puto","Puting kakanin sa bilao","Keso sa ibabaw","Meryenda sa hapon"],
    ["Bicol Express","Maanghang na sili","Kremang gata","Hiniwang karneng baboy"],
    ["Kwek-kwek","Kulay kahel na harina","Itlog ng pugo","Tusok-tusok sa kanto"],
    ["Tokwa't Baboy","Pritong tokwa","Sarsa ng toyo at suka","Masarap na pulutan"],
    ["Kaldereta","Sarsa ng atay at keso","Patatas at carrots","Karne ng kambing o baka"],
    ["Menudo","Hiniwang atay at baboy","Pasas at diced carrots","Pulang sarsa ng kamatis"],
    ["Empanada","Palamang toge at itlog","Malutong na kulay kahel na balot","Sikat sa Ilocos"],
    ["Inasal","Inihaw na manok sa uling","Achuete at kalamansi marinade","Sikat sa Bacolod"],
    ["Palabok","Gintong sarsa ng hipon","Dinurog na chicharon","Tinapa flakes sa ibabaw"],
    ["Buko Pandan","Berdeng gulaman sa gata","Manamis-namis na kinudkod na niyog","Malamig na panghimagas"],
    ["Puto Bumbong","Kulay lilang malagkit","Niluluto sa kawayan","Niyog at asukal na muscovado"],
    ["Mechado","Taba sa gitna ng karne","Sarsa ng kamatis at laurel","Malambot na baka"]
  ],
  "Inumin": [
    ["Salabat","Luya","Mainit","Lagnat"],
    ["Kapeng Barako","Batangas","Malakas","Robust"],
    ["Sago't Gulaman","Palamig","Karinderya","Malagkit"],
    ["Buko Juice","Niyog","Malamig","Macapuno"],
    ["Calamansi Juice","Maasim","Piga","Calamondin"],
    ["Tsokolate","Batirol","Batangas","Tableya"],
    ["Tubig","Uhaw","Mineral","Artesian"],
    ["Gatas","Kaltsyum","Pasteurized","Condensada"],
    ["Lambanog","Niyog","Halamang-ugat","Cavite"],
    ["Samalamig","Kalsada","Mainit na panahon","Vendor"],
    ["Mango Shake","Blender","Carabao mango","Malambot"],
    ["Melon Juice","Matamis","Hilaw","Honeydew"],
    ["Kape","Barako","Puyat","Robusta"],
    ["Tsaa","Dahon","Steep","Camomile"],
    ["Softdrinks","Bula","Royal","De botilya"],
    ["Guyabano Juice","Maasim-asim na lasa","Masustansyang prutas","Pampalakas ng katawan"],
    ["Mais Con Yelo","Manamis-namis na mais","Gatas at kinaskas na yelo","Paboritong pangmeryenda"],
    ["Buko Shake","Kinudkod na laman ng niyog","Malamig na blender blend","Preskong pampalamig"],
    ["Tuba","Katkat mula sa puno ng niyog","Tradisyonal na alak sa probinsya","Pampa-init ng katawan"],
    ["Avocado Shake","Hinog na abukado","Kremoso at gatas","Kondensada sa yelo"],
    ["Calamansi Iced Tea","Pinigang sariwang kalamansi","Malamig na tsaa at asukal","Pamatid-uhaw sa tanghali"],
    ["Pandan Iced Tea","Mabangong dahon ng pandan","Pinakuluan at pinalamig","Halamang pampalasa"],
    ["Sarsi","Likas na lasa ng root beer","Minsan hinahaluan ng hilaw na itlog","Mabula at matapang"],
    ["Dalandan Juice","Berdeng balat na maasim-tamis","Sariwang pinigang katas","Bitamina C sa umaga"],
    ["Milo Dinosaur","Malamig na tsokolateng inumin","Tambak na pinulbos na tsokolate","Paborito ng mga bata"],
    ["Basi","Alak mula sa katas ng tubo","Tradisyonal na inumin ng Ilocano","Nakaimbak sa banga"],
    ["Tsokolate de Batirol","Purong tablea ng kakaw","Kahoy na batirol na panghalo","Makapal na bula"],
    ["Sago Shake","Malalambot na bilog na sago","Matamis na arnibal at yelo","Palamig sa basong plastik"],
    ["Kamias Juice","Matapang na asim ng bunga","Pampapresko sa tag-init","Sariwang katas"],
    ["Gulaman","Malamig na inumin sa bilao","Agar-agar na may arnibal","Tinda sa tabi ng kalsada"]
  ],
  "Hayop": [
    ["Aso","Tahol","Bantay","Aso ng gabi"],
    ["Pusa","Bigote","Miyaw","Nakikipaglaro"],
    ["Kalabaw","Bukid","Sulong","Kapwa tao"],
    ["Agila","Pakpak","Soar","Pambansang ibon"],
    ["Buwaya","Ilog","Ngipin","Saltwater"],
    ["Tarsier","Mata","Bohol","Nocturnal"],
    ["Unggoy","Saging","Puno","Primate"],
    ["Elepante","Nguso","Akbar","Herd"],
    ["Manok","Tilaok","Sabong","Kampeon"],
    ["Kambing","Sungay","Talampas","Goat"],
    ["Baboy","Putik","Pabulong","Sus scrofa"],
    ["Palaka","Lundag","Ulan","Salitre"],
    ["Pagong","Bato-bato","Turtle","Carapace"],
    ["Daga","Keso","Bubonic","Rodent"],
    ["Paruparo","Ganda","Metamorphosis","Chrysalis"],
    ["Baka","Unga sa pastulan","Pinagkukunan ng gatas","Matabang baka sa damuhan"],
    ["Kabayo","Mabilis na yabag ng kuko","Humihila ng kalesa","Hawak na renda sa leeg"],
    ["Ibon","Balahibong may pakpak","Pugad sa sanga ng puno","Huni tuwing bukang-liwayway"],
    ["Isda","Makintab na kaliskis","Lumalangoy gamit ang palikpik","Hininga sa hasang"],
    ["Tutubi","Maninipis at transparent na pakpak","Mabilis lumipad sa ibabaw ng tubig","Dumadapo sa damo"],
    ["Hipon","Balisawsaw at balat","Pumuputok na kulay pula kapag luto","Mahabang balbas sa ulo"],
    ["Alimango","Matitigas at malalaking sipit","Matabang aligue sa talukap","Nakatira sa putik at bakawan"],
    ["Pabo","Kulubot at pulang balat sa leeg","Malaking ibon sa bakuran","Paypay ng buntot"],
    ["Tupa","Makapal at malambot na balahibo","Tunog ng maa sa pastol","Kawan sa burol"],
    ["Butiki","Gumagapang sa kisame at dingding","Napuputol ang buntot kapag natakot","Nanghuhuli ng lamok"],
    ["Gansa","Mahabang leeg at puting pakpak","Nanghahabol kapag pumasok sa bakuran","Malakas na tunog"],
    ["Paniki","Nakatali at nakabitin nang baligtad","Lumilipad sa dilim ng gabi","Nakatira sa madidilim na kuweba"],
    ["Tamaraw","Sungay na hugis V sa noo","Mailap na hayop sa Mindoro","Pambansang simbolo ng lakas"],
    ["Balang","Malalakas na paang panlukso","Sumisira sa pananim sa bukid","Kawan ng insekto sa parang"],
    ["Kalapati","Puting ibon ng kapayapaan","Simbahan sa plaza","Huni at pakpak"]
  ],
  "Lugar": [
    ["Palengke","Tinda","Mamimili","Wet market"],
    ["Paaralan","Klase","Kampana","Silid-aralan"],
    ["Ospital","Pasyente","Sterile","ER"],
    ["Simbahan","Kampana","Misa","Santwaryo"],
    ["Paliparan","Eroplano","Check-in","Terminal"],
    ["Dalampasigan","Buhangin","Alon","Undertow"],
    ["Barangay Hall","Kapitan","Lupon","Permit"],
    ["Plaza","Pasyalan","Bantayog","Kiosko"],
    ["Sari-sari Store","Tingi","Bintana","Tindero"],
    ["Terminal","Sakay","Konduktor","Bus"],
    ["Bukid","Ani","Palay","Kamalig"],
    ["Bundok","Tuktok","Lambak","Treeline"],
    ["Ilog","Agos","Banig na bato","Baha"],
    ["Museo","Eksibit","Curator","Artifact"],
    ["Aklatan","Libro","Silence","Card catalog"],
    ["Munisipyo","Tanggapan ng punong alkalde","Sentro ng serbisyo sa bayan","Watawat sa harapan"],
    ["Talipapa","Maliit na pamilihan sa kanto","Sariwang isda at gulay","Bilihan ng pang-araw-araw"],
    ["Sabungan","Tari at pusta sa ruweda","Sigaw ng mga kristo","Pang-sabong na manok"],
    ["Kanto","Tambayan ng mga kabataan","Pila ng mga tricycle","Tindahan sa kanto"],
    ["Sementeryo","Puntod at mga krus","Dinadagsa tuwing Undas","Kandila at bulaklak"],
    ["Bakery","Mainit na pandisal sa umaga","Amoy ng bagong lutong tinapay","Pugon ng panadero"],
    ["Karinderya","Turo-turo sa mga kaldero","Mura at lutong-bahay na ulam","Estanteng salamin"],
    ["Post Office","Selyo at mga sobreng sulat","Paghahatid ng mga parsela","Kahon ng koreo"],
    ["Bangko","Mabigat na bakal na vault","Pila sa harap ng teller","ATM sa bungad"],
    ["Kalsada","Asphalt at mga linyang puti","Araw-araw na daloy ng trapik","Tawiran ng tao"],
    ["Parke","Bangkong kahoy sa ilalim ng puno","Pasyalan ng mga pamilya sa hapon","Lugar na luntian"],
    ["Istasyon ng Pulis","Kulungan at selda","Mga pulis na nakabantay sa desk","Radyo at sirena"],
    ["Istasyon ng Bumbero","Malalaking pulang trak","Mahahabang hose at bota","Tore ng bumbero"],
    ["Tubigan","Lawa o malawak na sapa","Pangisdaan ng mga bangka","Tubig-tabang na paligid"],
    ["Talon","Mataas na lagaslas ng tubig","Pasyalan sa probinsya","Malamig na paliguan"]
  ],
  "Trabaho": [
    ["Guro","Aralin","Whiteboard","Rubric"],
    ["Doktor","Stetoskop","Diagnosis","Rounds"],
    ["Nars","Pasyente","Vitals","Triage"],
    ["Magsasaka","Ani","Palay","Crop rotation"],
    ["Inhinyero","Plano","Toleransya","Load"],
    ["Pulis","Tsapa","Patrol","Dispatch"],
    ["Kusinero","Kusina","Mise en place","Julienne"],
    ["Abogado","Korte","Brief","Jurisprudence"],
    ["Piloto","Cockpit","Callsign","Altitude"],
    ["Mangingisda","Lambat","Catch","Trawl"],
    ["Karpintero","Martilyo","Dovetail","Grain"],
    ["Tindera","Sukli","Inventory","Markup"],
    ["Mekaniko","Makina","Torque","Diagnostic"],
    ["Bumbero","Hose","Suppression","Thermal"],
    ["Mananahi","Sinulid","Seam","Bias cut"],
    ["Barbero","Gunting at labahang matalas","Gupit na fade sa buhok","Umiikot na upuan sa salamin"],
    ["Magtataho","Pinasan na dalawang lata","Sigaw ng taho sa umaga","Sandok ng arnibal at sago"],
    ["Drayber","Hawak sa manibela ng sasakyan","Tumatapak sa kambyo at preno","Naghahatid ng pasahero"],
    ["Konduktor","Punit ng papel na tiket","Supot ng barya sa balikat","Sigaw ng babaan sa kanto"],
    ["Hardinero","Gunting pampantay ng damo","Pangangalaga sa mga halaman","Pandilig sa umaga"],
    ["Sapatero","Paggawa ng matitibay na sapatos","Bantog sa bayan ng Marikina","Martilyo at kola"],
    ["Bantay","Unipormeng pang-seguridad","Nakatayo sa pintuan ng gusali","Pagsisiyasat sa mga bag"],
    ["Kaminero","Walang-sawang pagwawalis sa kalye","Walis-tingting at pandakot","Linis ng lansangan"],
    ["Panadero","Pangmamasa ng puting harina","Nagluluto sa mainit na pugon","Paggawa ng tinapay"],
    ["Beterinaryo","Panggagamot sa mga alagang hayop","Bakuna sa aso at pusa","Klinikang pambeterinaryo"],
    ["Kartero","Bag na puno ng mga sulat","Paghahatid bahay-bahay","Tagapagdala ng balita"],
    ["Huwes","Malyete na pumapalo sa mesa","Paggawad ng hatol sa korte","Kasuotang itim na toga"],
    ["Parmasyutiko","Paghahanda ng reseta ng doktor","Pagsasaayos ng mga gamot sa botika","Paliwanag sa tamang dosis"],
    ["Manunulat","Paghabi ng mga salita at kwento","Pluma at kwaderno","May-akda ng libro"],
    ["Tubero","Pagkumpuni sa tagas ng tubig","Wrench at tubong PVC","Pag-aayos ng baradong lababo"]
  ],
  "Kalikasan": [
    ["Bundok","Tuktok","Lambak","Treeline"],
    ["Ilog","Agos","Meandering","Tributary"],
    ["Dagat","Alon","Salinity","Thermocline"],
    ["Talon","Bagsak","Plunge pool","Cataract"],
    ["Bulkan","Lava","Caldera","Pyroclastic"],
    ["Kagubatan","Puno","Canopy","Understory"],
    ["Ulan","Payong","Petrichor","Monsoon"],
    ["Kidlat","Kislap","Kulog","Plasma"],
    ["Bahaghari","Kulay","Refraction","Arc"],
    ["Kuweba","Alingawngaw","Stalactite","Karst"],
    ["Isla","Pampang","Atoll","Littoral"],
    ["Bukal","Tubig","Spring","Artesian"],
    ["Lambak","Pagitan","Rift","Watershed"],
    ["Bagyo","Hangin","Eye wall","Cyclone"],
    ["Araw","Sikat","Corona","Solstice"],
    ["Bituin","Kutitap sa kalangitan sa gabi","Milyun-milyong tala sa dilim","Tala sa langit"],
    ["Buwan","Maliwanag na kabilugan","Tanging tanglaw sa hatinggabi","Kabilugan ng buwan"],
    ["Hangin","Preskong simoy sa tabing-dagat","Malamig na ihip sa madaling-araw","Hanging amihan"],
    ["Ulap","Puting kumpol sa bughaw na langit","Nagdidilim bago bumuhos ang ulan","Mataas na ulap"],
    ["Hamog","Maliliit na patak ng tubig sa damo","Malamig na singaw sa umaga","Basa sa dahon"],
    ["Lupa","Matabang lupang taniman ng palay","Bungkal ng araro ng magsasaka","Likas na lupa"],
    ["Lindol","Biglaang pagyanig ng lupa","Paggalaw sa ilalim ng fault line","Alert level sa lindol"],
    ["Baha","Pag-apaw ng tubig sa kalsada","Dulot ng walang-tigil na ulan","Mataas na baha"],
    ["Bukang-liwayway","Unang silahis ng liwanag sa silangan","Pagsisimula ng bagong umaga","Pagsikat ng araw"],
    ["Takipsilim","Kulay kahel at lilang langit","Pahimakas ng araw sa kanluran","Paglubog ng araw"],
    ["Bakawan","Matitibay na ugat sa tubig-alat","Pananggalang sa daluyong ng bagyo","Kakahuyan sa baybay"],
    ["Dalampasigan","Pinong puting buhangin sa pampang","Tahimik na hampas ng mga alon","Pulot ng kabibe"],
    ["Lawa","Mapayapa at tahimik na tubig","Napapalibutan ng kabundukan","Lawa ng tubig-tabang"],
    ["Koral","Makukulay na bahura sa ilalim ng dagat","Tahanan ng maliliit na isda","Yamang-dagat"],
    ["Sapa","Mababaw at malinaw na batis","Malamig na tubig sa probinsya","Bato sa gilid ng sapa"]
  ],
  "Sasakyan": [
    ["Jeepney","Bayad","Ruta","Barker"],
    ["Tricycle","Sidecar","Habal-habal","Pedicab"],
    ["Bus","Konduktor","Bay","Scheduled"],
    ["Tren","Riles","Platform","Gauge"],
    ["Motorsiklo","Helmet","Throttle","Kickstart"],
    ["Bisikleta","Pedal","Derailleur","Chainring"],
    ["Bangka","Sagwan","Outrigger","Banca"],
    ["Eroplano","Pakpak","Fuselage","Aileron"],
    ["Taxi","Metro","Flag down","Meter"],
    ["Kalesa","Kabayo","Kutsero","Cochero"],
    ["Ferry","Tawid","RORO","Berth"],
    ["Van","Terminal","Route","Shuttle"],
    ["Truck","Kargamento","Payload","Axle"],
    ["Pedicab","Padyak","Sidecar","Last mile"],
    ["Ambulansya","Sirena","Code blue","Stretcher"],
    ["Habal-habal","Maramihang angkas sa motor","Matatarik na daan sa bundok","Pinasadyang motorsiklo"],
    ["Bapor","Malaking barkong pampasahero","Dungguan sa malalaking pantalan","Tawid sa bukas na karagatan"],
    ["Kuliglig","Makinang pangsaka na ginawang sasakyan","Kariton sa gilid ng palayan","Maugong na makina"],
    ["Kariton","Hinihila gamit ang kamay o kalabaw","Kahoy na gulong na may karga","Hakot ng gulay at prutas"],
    ["Sidecar","Kabitang bakal sa gilid ng motor","Inuupuan ng mga pasahero ng tricycle","May bubong na upuan"],
    ["Balsa","Pinagtali-taling mga kawayan","Pinapaandar gamit ang tikin o sagwan","Tawid sa mababaw na ilog"],
    ["E-trike","Pinapatakbo ng kuryente at baterya","Tahimik na biyahe sa barangay","Makabagong tricycle"],
    ["Patok na Jeep","Umuugong na malakas na sound system","Mabilis humarurot sa lansangan","Makulay na palamuti"],
    ["Speedboat","Mabilis na bangkang may makina sa likod","Hati sa alon patungo sa isla","Pang-turista"],
    ["Chopper","Umiikot na elisi sa ibabaw","Lumilipad nang walang pakpak","Helikopter"],
    ["Roro","Barko kung saan pumapasok ang mga sasakyan","Tawid-dagat ng mga bus at truck","Malaking rampa"],
    ["Skylab","Motorsiklong may kahoy na pakpak","Pang-akyat sa liblib na bundok sa Mindanao","Maraming kargang gulay"],
    ["Padyak","Pinapatakbo ng lakas ng mga binti","Maliit na pampasaherong sasakyan sa eskinita","Pedal ng bisikleta"],
    ["Bangkang De-motor","Bangkang may katig at makinang de-gasolina","Palaot ng mga mangingisda sa madaling-araw","Tunog ng motor sa dagat"],
    ["Kotse","Apat na gulong na pribadong sasakyan","Aircon at radyo sa loob","Maneho sa highway"]
  ],
  "Bagay": [
    ["Payong","Ulan","Canopy","Ferrule"],
    ["Unan","Tulog","Filling","Pillowcase"],
    ["Kandila","Apoy","Paraffin","Wick"],
    ["Walis","Linis","Bristles","Dustpan"],
    ["Salamin","Repleksyon","Silvering","Quicksilver"],
    ["Orasan","Oras","Escapement","Pendulum"],
    ["Lamesa","Kainan","Top","Joinery"],
    ["Upuan","Upo","Ergonomics","Lumbar"],
    ["Gunting","Gupit","Blade","Pivot"],
    ["Susi","Kandado","Pin tumbler","Cylinder"],
    ["Pitaka","Pera","Compartments","Billfold"],
    ["Tsinelas","Paa","Sole","Thong"],
    ["Timba","Tubig","Bail","Galvanized"],
    ["Kumot","Init","Tog","Weave"],
    ["Bentilador","Hangin","Blade","Oscillate"],
    ["Tabo","Pang-igib at pambuhos sa banyo","Kasama lagi ng timba","Hawakang plastik"],
    ["Sandok","Pangkuha ng masarap na sabaw","Kahoy o bakal sa kusina","Panghalo sa kaldero"],
    ["Kaldero","Lalagyan sa pagsasaing ng kanin","Itim sa ilalim dahil sa uling","Takip na bilog"],
    ["Plato","Porselana o plastik na lagayan ng kanin","Hugas pagkatapos kumain","Hapag-kainan"],
    ["Kutsara at Tinidor","Pares na gamit sa pagkain","Subo ng ulam at kanin","Kutsara't tinidor"],
    ["Plantsa","Mainit na bakal na pang-alis ng gusot","Pang-ayos ng uniporme at damit","Kabayo ng plantsahan"],
    ["Planggana","Malaking bilog na lagayan ng labada","Bula ng sabon at tubig","Kusot sa damit"],
    ["Banig","Hinabing tulugang yari sa dahon","Malamig at presko sa sahig","Tinitiklop sa umaga"],
    ["Kulambo","Manipis na lambat laban sa lamok","Nakakabit sa apat na sulok ng kama","Pang-iwas sa kagat"],
    ["Bunot","Kalahating bao ng niyog na may bunot","Pampakintab sa sahig na tabla","Kuskos gamit ang paa"],
    ["Flashlight","Ilaw na pambulsa kapag brownout","Baterya at maliit na switch","Tulong sa dilim"],
    ["Suklay","Plastik na may maraming ngipin","Pang-ayos ng gulo-gulong buhok","Humarap sa salamin"],
    ["Sipilyo","Panglinis ng ngipin araw-araw","Lalagyan ng toothpaste","Pangangalaga sa bibig"],
    ["Baso","Lalagyan ng malamig na tubig","Bubog o plastik na inuman","Tagay sa lamesa"],
    ["Posporo","Kiskis sa gilid ng kahon upang magkaapoy","Maliit na patpat na kahoy","Pangsindi ng kalan"]
  ],
  "Kulturang Pilipino": [
    ["Bayanihan","Tulong","Kapwa","Komunidad"],
    ["Mano Po","Paggalang","Kamay","Blessing"],
    ["Harana","Kanta","Gabi","Ligawan"],
    ["Pasalubong","Uwi","Lakbay","Regalo"],
    ["Sari-sari Store","Tingi","Bintana","Komunidad"],
    ["Videoke","Mikropono","Kantahan","Puntos"],
    ["Barong Tagalog","Pormal","Pinya","Jusi"],
    ["Tinikling","Kawayan","Sayaw","Labrador"],
    ["Budol Fight","Salo-salo","Handaan","Buhos"],
    ["Ukay-ukay","Murang damit","Pagpili","Thrift"],
    ["Ninong","Regalo","Kasal","Sponsor"],
    ["Ninang","Binyag","Inaanak","Godmother"],
    ["Pabitin","Kendi","Saya","Fiesta"],
    ["Perya","Rides","Pondo","Carnival"],
    ["Barangay","Kapitan","Lupon","Governance"],
    ["Pagmamano","Pagdampi ng kamay sa noo bilang paggalang","Kaugalian sa mga lolo at lola","Paghingi ng bendisyon"],
    ["Simbang Gabi","Siyam na araw na misa sa madaling-araw","Pagsapit ng malamig na simoy ng Pasko","Kain ng bibingka"],
    ["Noche Buena","Hatinggabi ng pamilyang nagsasalo-salo","Queso de bola at hamon sa mesa","Bisperas ng Pasko"],
    ["Pamahiin","Matatandang paniniwala sa swerte at malas","Bawal magwalis sa gabi","Kaugaliang iniingatan"],
    ["Kasal","Seremonya ng pag-iisang dibdib sa simbahan","Singsing belo at kurdon","Handaan ng dalawang angkan"],
    ["Binyag","Pagtanggap ng sanggol sa kristiyanismo","Ninong at ninang na gagabay","Binyagan sa parokya"],
    ["Fiesta","Makukulay na banderitas sa mga kalsada","Piyesta ng patron sa bayan","Bukas ang pintuan ng bawat bahay"],
    ["Balikbayan Box","Kahon ng mga padala mula sa ibang bansa","Tsokolate sabon at damit ng OFW","Sabik na binubuksan ng pamilya"],
    ["Kamayan","Tradisyonal na pagkain gamit ang mga kamay","Nakatambak sa dahon ng saging","Boodle fight ng barkada"],
    ["Barkada","Matatag na samahan ng magkakaibigan","Gimik tawanan at kwentuhan","Laging magkasama"],
    ["Utang na Loob","Taos-pusong pagtanaw sa kabutihang natanggap","Pahalaga sa tulong ng kapwa","Kulturang Pilipino"],
    ["Pamanhikan","Pagharap ng pamilya ng lalaki sa magulang ng babae","Pormal na paghingi ng kamay sa kasal","Salo-salo ng dalawang panig"],
    ["Salo-salo","Masayang kainan ng buong pamilya","Hapag-kainan na puno ng kwento","Pagtitipon sa pista"],
    ["Harana sa Bintana","Tugtog ng gitara sa ilalim ng bintana","Tapat na pag-awit upang manligaw","Tradisyonal na ligawan"],
    ["Santacruzan","Prusisyon ng mga naggagandahang reyna","Arko ng bulaklak sa gabi ng Mayo","Reyna Elena"]
  ],
  "Pinoy Slang": [
    ["Lodi","Idol","Inspirasyon","Role model"],
    ["Petmalu","Malupit","Grabe","Sobrang galing"],
    ["Sana All","Sana din ako","Inggit","Goals"],
    ["Charot","Biro","Joke","Wag seryosohin"],
    ["Jowa","Kasintahan","Syota","Partner"],
    ["Werpa","Lakas","Lakasan","Power"],
    ["Kilig","Ngiti","Puso","Crush"],
    ["Gigil","Pisngi","Sobrang cute","Kiligin"],
    ["Budol","Bili","Natukso","Impulse buy"],
    ["Marites","Tsismis","Chika","Gossip"],
    ["Awit","Sayang","Hinaing","Nakaka-stress"],
    ["Dasurv","Karapat-dapat","Deserved","Panalo"],
    ["Gora","Tara","Alis na","Let's go"],
    ["Chika","Kwento","Tsismis","Gossip"],
    ["Beshie","Kaibigan","BFF","Bestie"],
    ["Kalerki","Nakakagulat at nakakalokang sitwasyon","Grabe ang reaksyon sa balita","Sobrang drama"],
    ["Waley","Hindi benta at walang kwentang biro","Bagsak na patawa sa usapan","Walang dating"],
    ["Havey","Sobrang benta at nakakatawang hirit","Panalo ang joke sa kwentuhan","Tawanan ang lahat"],
    ["Mumshie","Tawag sa nanay o malapit na kaibigan","Lambingang tawag ng magkakaibigan","Momsy"],
    ["Erpat","Salitang baligtad para sa tatay","Padre de pamilya sa bahay","Haligi ng tahanan"],
    ["Ermat","Salitang baligtad para sa nanay","Ilaw ng tahanan sa pamilya","Ina"],
    ["Yosi","Tingi-tinging sigarilyo sa kanto","Buga ng usok","Tindahan"],
    ["Dehins","Baligtad na salita para sa hindi","Pag-ayaw o pagtanggi sa alok","Ayoko"],
    ["Astig","Tindig na matapang at kahanga-hanga","Sobrang porma at lupit","Lodi sa galing"],
    ["GG","Gandang-ganda sa sariling hitsura","Good game o talo na sa laro","Game over"],
    ["Chibog","Masarap na kainan ng barkada","Pagkain sa mesa","Lamon ng ulam"],
    ["Epal","Taong mahilig pumapel sa usapan","Sali nang sali kahit hindi tinatawag","Kulang sa pansin"],
    ["KSP","Kulang sa pansin sa barkada","Laging nagpapapansin sa iba","Pumapapel"],
    ["Praning","Labis na nag-aalala at natatakot","Nababaliw sa kaba at pagdududa","Masyadong nag-iisip"],
    ["Taray","Matapang ang dating at porma","Suplada pero maganda ang tindig","Palaban ang awra"]
  ],
  "Artista at Aliwan": [
    ["Teleserye","Episode","Afternoon","Prime time"],
    ["Loveteam","Kilig","Tandem","Shipping"],
    ["Noontime Show","Tanghali","Sayawan","Noontime"],
    ["Karaoke","Kanta","Puntos","Videoke"],
    ["Komedyante","Tawa","Punch line","Stand-up"],
    ["Kontrabida","Galit","Bida","Villain"],
    ["Leading Lady","Bida","Kontrabida","Star"],
    ["Pelikula","Sine","Screenplay","Direktor"],
    ["Konsiyerto","Entablado","Soundcheck","Setlist"],
    ["Sayawan","Indak","Choreographer","Count"],
    ["Audition","Pili","Callback","Screen test"],
    ["Eksena","Kamera","Blocking","Take"],
    ["Premiere","Unang palabas","Premiere night","Red carpet"],
    ["Tagahanga","Idolo","Fan mail","Fandom"],
    ["Palabas","Telebisyon","Pilot","Renewal"],
    ["Primetime Bida","Mga teleseryeng sumasahimpapawid sa gabi","Mataas na viewership ratings","Pangunahing palabas"],
    ["Patalastas","Komersyal na nagpapakilala ng produkto","Tampok ang mga sikat na artista","Paluwa sa telebisyon"],
    ["Fan Club","Organisadong grupo ng mga tagahanga","May dalang banner sa studio","Todo suporta sa idolo"],
    ["Talk Show Showbiz","Panayam sa buhay at tsismis ng mga artista","Eksklusibong pag-amin sa telebisyon","Mainit na usapan"],
    ["Reality TV","Bahay ni Kuya at mga pagsubok","Boto ng taumbayan sa mananalo","Walang sinusundang script"],
    ["Bida ng Kwento","Mabait at inaaping bida na lalaban sa huli","Sentro ng pagmamahal ng manonood","Laging panalo sa dulo"],
    ["Dubber","Boses sa Tagalog na bersyon ng anime","Pagsasalin ng banyagang serye","Pagsasalita sa mikropono"],
    ["Soundtrack ng Pelikula","Emosyonal na kantang tumatatak sa manonood","Theme song ng teleserye","Tugtog sa mga eksena"],
    ["Red Carpet Gala","Nagniningning na kasuotan ng mga bituin","Flashing ng kamera ng mga paparazzi","Gabi ng parangal"],
    ["Blooper Reel","Kakatawang pagkakamali sa pagkuha ng eksena","Tawanan ng mga artista sa shooting","Nakalabas sa dulo ng palabas"],
    ["Matinee Idol","Guwapong artistang paborito ng kabataan","Tinitilian ng mga tagahanga sa mall show","Bata at sumisikat"],
    ["Direktor ng Pelikula","Sumisigaw ng 'action' at 'cut' sa set","May hawak ng buong artistikong pananaw","Nagpapatakbo sa eksena"],
    ["Extra","Taong-bayan na nakatayo sa likod ng bida","Walang sariling linya sa eksena","Karagdagang tao sa shooting"],
    ["Endorser","Mukhang nakapaskil sa mga higanteng billboard","Nakatali ang pangalan sa isang tatak","Model ng komersyal"],
    ["Viral Video","Mabilis na kumakalat na bidyo sa internet","Milyun-milyong views at shares","Trending sa buong bansa"]
  ],
  "Artista": [
    ["Kathryn Bernardo","KathNiel","Joy","Box Office"],
    ["Daniel Padilla","Supremo","Gitara","Pangako Sa 'Yo"],
    ["Vice Ganda","Unkabogable","Comedy Bar","It's Showtime"],
    ["Anne Curtis","Dyosa","Dyesebel","Australia"],
    ["Coco Martin","Cardo","Ang Probinsyano","Batang Quiapo"],
    ["Bea Alonzo","One More Chance","Basha","The Mistress"],
    ["Piolo Pascual","Papa P","ASAP","Milan"],
    ["Sarah Geronimo","Popstar Royalty","Tala","The Voice"],
    ["Alden Richards","Pambansang Bae","Hello, Love, Goodbye","AlDub"],
    ["Marian Rivera","Darna","Dyesebel","Sabay Sabay Tayo"],
    ["Dingdong Dantes","Descendants of the Sun","Motorcycle","Primetime King"],
    ["Nadine Lustre","President Nadine","Siargao","Diary ng Panget"],
    ["James Reid","Careless Music","Palm Dreams","Australia"],
    ["Kim Chiu","Chinita Princess","Pinoy Big Brother","Fit Check"],
    ["Paulo Avelino","Heneral Luna","Goyo","Bridges of Love"],
    ["Judy Ann Santos","Teleserye Queen","Judy Ann's Kitchen","Mara"],
    ["Regine Velasquez","Asia's Songbird","High Notes","R2K"],
    ["Jose Manalo","Juan for All","Lola Tinidora","Kalyeserye"],
    ["Empoy Marquez","Kita Kita","Tonyo","Japan"],
    ["Dolly de Leon","Triangle of Sadness","Golden Globe","Abigail"],
    ["Manny Pacquiao","Pambansang Kamao ng Pilipinas","Kampeon sa walong dibisyon ng boksing","Matinding suntok sa lona"],
    ["Sharon Cuneta","Nag-iisang Megastar ng pelikula","Bantog na kantang Bituing Walang Ningning","Mr. DJ sa radyo"],
    ["Vilma Santos","Star for All Seasons ng industriya","Gumanap bilang Darna sa takilya","Gobernadora ng Batangas"],
    ["Nora Aunor","Superstar at Pambansang Alagad ng Sining","Walang himala sa pelikulang Himala","Gintong boses sa entablado"],
    ["Lea Salonga","Bumida bilang Kim sa Miss Saigon","Nagwagi ng prestihiyosong Tony Award","Boses ng Disney Princesses"],
    ["Michael V.","Haligi ng Bubble Gang at komedya","Malikhaing lumilikha ng mga parody songs","Kilala bilang si Bitoy"],
    ["John Lloyd Cruz","Gumanap bilang Popoy sa One More Chance","Hari ng romantic comedy sa sine","Araw-gabi sa teleserye"],
    ["Jericho Rosales","Bida sa klasikong Pangako Sa 'Yo","Kilala sa bansag na Echo sa showbiz","Pang-internasyonal na aktor"],
    ["Liza Soberano","Kalahati ng sikat na tambalang LizQuen","Gumanap sa pelikulang My Ex and Whys","Hollywood debut sa acting"],
    ["Enrique Gil","Tinaguriang King of the Gil sa sayaw","Bida sa teleseryeng Forevermore","Kasosyo ni Liza Soberano"],
    ["Maine Mendoza","Sumikat bilang Yaya Dub sa Kalyeserye","Reyna ng Dubsmash at komedya","Paborito ng AlDub nation"],
    ["Ivana Alawi","Sikat na vlogger at aktres","Kilala sa kanyang mga prank at pagtulong","Bida sa teleserye"],
    ["Moira Dela Torre","Reyna ng mga kantang mapanakit at hugot","Mang-aawit ng Tagpuan at Paubaya","Malumanay at madamdaming tinig"],
    ["Ogie Alcasid","Mabunying kompositor ng OPM hits","Pilyong komedyante sa telebisyon","Hurado sa It's Showtime"],
    ["Eugene Domingo","Bida sa serye ng pelikulang Kimmy Dora","Mahusay na komedyante at karakter aktres","Ang Babae sa Septic Tank"]
  ],
  "Larong Pinoy": [
    ["Patintero","Guhit","Tagapagtanggol","Pumalo"],
    ["Tumbang Preso","Lata","Pamato","Bantay"],
    ["Luksong Baka","Yuko","Lumukso","Kasamahan"],
    ["Piko","Kahon","Bato","Isang paa"],
    ["Sipa","Tingga","Tuhod","Sepak takraw"],
    ["Agawan Base","Kampo","Takbo","Agaw"],
    ["Langit-Lupa","Taya","Mataas","Ligtas"],
    ["Taguan","Hanap","Nag-iisa","Seeker"],
    ["Holen","Bilog","Marble","Cubit"],
    ["Trumpo","Ikot","Sinulid","Spin"],
    ["Luksong Tinik","Talon","Tuhod","Dalawang bata"],
    ["Dama","Piyesa","Checkers","Diagonal"],
    ["Sungka","Kabibe","Bilog na kahon","Mancala"],
    ["Jackstone","Hagis","Bola","Tig-isa"],
    ["Chinese Garter","Goma","Taas","Elastic"],
    ["Palo Sebo","Madulas na matayog na kawayan","Bandilang inaabot sa tuktok","Tradisyonal na palaro sa fiesta"],
    ["Kadang-kadang","Bao ng niyog na may hawakang tali","Mabilis na paghakbang at pagtakbo","Katutubong laro sa pista"],
    ["Pitik-bulag","Pagtakip sa mga mata ng taya","Pagtatantiya sa daliring ipinitik","Hulaan kung ilang daliri"],
    ["Shatong","Maikling patpat na pinalilipad ng mahaba","Pagsukat ng layo gamit ang patpat","Laro sa bakanteng lote"],
    ["Bahay-bahayan","Pagkukunwaring nanay at tatay","Luto-lutuan gamit ang mga dahon at lupa","Paboritong laro ng mga paslit"],
    ["Doctor Kwak-Kwak","Buhol-buhol na braso ng mga manlalaro","Panghuhula kung paano kakalasin ang hawak","Gamutan ng buhol"],
    ["Teks","Maliliit na kard na may komiks","Pina-iikot at pinipitik sa hangin","Cha-ba at panalo sa bilang"],
    ["Siato","Pukpok sa patpat na nakapatong sa hukay","Takbuhan habang sumisigaw","Tradisyonal na laro sa probinsya"],
    ["Ubusan ng Lahi","Habulan kung saan nagiging kakampi ang nahuli","Hanggang maubos ang buong grupo","Walang-sawang takbuhan"],
    ["Agawan Panyo","Panyong nakabitin sa kamay ng tagapamagitan","Mabilis na pagsunggab at pagtakbo sa linya","Tawag ng numero"],
    ["Sipa sa Lata","Pagsipa sa lata nang malakas palayo","Mabilis na pagtakbo bago maibalik ang lata","Larong kalye sa hapon"],
    ["Bulong-Pari","Pari na nakikinig sa ibinubulong na pangalan","Hulaan kung sino ang nagparusa","Palitan ng taya"],
    ["Tumbang Lata","Paggamit ng tsinelas bilang pamato","Pagpatumba sa lata ng gatas","Bantay na nagpapatayo"],
    ["Sawsaw-Suka","Daliring nakasawsaw sa nakabukas na palad","Mabilis na pag-iwas kapag kumuyom ang kamay","Awit na sawsaw suka mahuli taya"],
    ["Piko-piko","Mga kahong iginuhit gamit ang tisa o uling","Paglukso gamit ang isang paa","Pamato sa bawat numero"]
  ],
  "Paaralan": [
    ["Guro","Aralin","Rubric","Pedagogy"],
    ["Mag-aaral","Klase","Desk","Cohort"],
    ["Pagsusulit","Iskor","Proctor","Rubric"],
    ["Silid-aralan","Upuan","Rows","Acoustics"],
    ["Takdang-Aralin","Deadline","Assignment","Prompt"],
    ["Pisara","Tisa","Dust","Squeaky"],
    ["Aklatan","Libro","Dewey","Catalog"],
    ["Punong-guro","Opisina","Discipline","Tenure"],
    ["Kard ng Marka","Grado","Comments","Transcript"],
    ["Oras ng Pahinga","Meryenda","Unstructured","Playground"],
    ["Kuwaderno","Linya","Margin","Spiral"],
    ["Laboratoryo","Eksperimento","Reagent","Fume hood"],
    ["Pagtatapos","Diploma","Regalia","Commencement"],
    ["Uniporme","Kulay","Insignia","Regulation"],
    ["Proyekto","Grupo","Rubric","Presentation"],
    ["Lapis","Pansulat na may itim na graphite","Pambura sa kabilang dulo","Pang-drawing at pagsulat"],
    ["Papel","Linyadong pad paper sa silid-aralan","Sinusulatan ng mga sanaysay at takda","Punit sa kwaderno"],
    ["Bag","Pasan sa likod papuntang paaralan","Lalagyan ng mga mabibigat na libro","Lagayan ng baon"],
    ["Baon","Barya o pagkaing bigay ng magulang","Kinakain tuwing recess sa kantina","Badyet ng estudyante"],
    ["Bandila ng Pilipinas","Itinataas tuwing Lunes sa flag ceremony","Koro ng pambansang awit","Nasa gitna ng quadrangle"],
    ["Pisara at Tisa","Puting tisa na sumusulat sa itim na board","Binubura ng eraser sa pagtatapos ng klase","Aralin ng guro"],
    ["Gunting sa Sining","Panggupit sa mga makukulay na kartolina","Kagamitan sa gawaing-sining","Matulis na talim"],
    ["Pandikit","Pandidikit ng mga ginupit na larawan","Glue sa mga proyektong pampaaralan","Puting likido"],
    ["Pantasa","Pampatalas sa pudpod na dulo ng lapis","Kolektor ng mga pinagtasahan","Nasa loob ng pencil case"],
    ["Kantina","Bilihan ng meryenda at inumin","Pila ng mga mag-aaral tuwing recess","Tindahan sa paaralan"],
    ["Kwaderno","Kwaderno na may mga guhit at linya","Lalagyan ng mga lektyur at tala","Pahina ng aralin"],
    ["ID ng Mag-aaral","Kard na nakasabit sa leeg","Litrato at numero ng mag-aaral","Ipinapakita sa guwardiya"],
    ["Pambura","Gomang pambura ng maling sulat","Panglinis ng dumi ng lapis sa papel","Walang bakas"],
    ["Flag Ceremony","Pagsasaludo sa bandila tuwing umaga","Pagbigkas ng Panatang Makabayan","Maayos na pila ng bawat klase"],
    ["Pagsasanay","Maikling pagsusulit pagkatapos ng talakayan","Pagsusuri sa natutunan ng estudyante","Iskor sa pagsusulit"]
  ],
  "Palakasan": [
    ["Basketbol","Ring","Dribble","Pick-and-roll"],
    ["Boksing","Guwantes","Jab","Southpaw"],
    ["Langoy","Laps","Stroke","Tumble turn"],
    ["Badminton","Shuttlecock","Smash","Rally"],
    ["Bilyar","Tisa","Cue","English"],
    ["Takbuhan","Finish Line","Stride","Cadence"],
    ["Volleyball","Spike","Libero","Rally"],
    ["Arnis","Baston","Defensa","Pambansang"],
    ["Sipa","Bola","Tingga","Sepak takraw"],
    ["Sepak Takraw","Sipa","Net","Acrobatic"],
    ["Padyak","Pedal","Cadence","Peloton"],
    ["Bowling","Pin","Spare","Lane"],
    ["Chess","Hari","Gambit","Endgame"],
    ["Surfing","Alon","Barrel","Quiver"],
    ["Weightlifting","Barbel","Snatch","Clean and jerk"],
    ["Karera sa Takbuhan","Mabilis na sprint patungo sa finish line","Pagsisimula sa putok ng baril","Labanan ng bilis"],
    ["Sungkaan","Tradisyonal na larong pampatalas ng isip","Kabibeng inililipat sa mga butas","Labanan ng taktika"],
    ["Dama sa Kanto","Piyesang korona kapag nakaabot sa dulo","Laro sa mesang gawa sa kahoy","Talon sa piyesa ng kalaban"],
    ["Siklista","Mabilis na pagpadyak sa kabundukan","Kasuotang pang-karera at helmet","Kumpetisyon sa highway"],
    ["Manlalangoy","Sumisisid at humahawi sa tubig ng pool","Suot ang goggles at swim cap","Laps sa paligsahan"],
    ["Boksingero","Mandirigma sa loob ng square ring","Naghahagis ng mga suntok at uppercut","Pagpatumba sa kalaban"],
    ["Futbol sa Damo","Pagsipa ng bola sa malaking net","Bawal hawakan gamit ang kamay","Laro sa football field"],
    ["Taekwondo","Matataas na sipa sa ere at pagsangga","Puting dobok at may kulay na sinturon","Puntos sa katawan at ulo"],
    ["Judo","Paghagis at pagbuno sa kalaban sa banig","Hawak sa kwelyo ng kimono","Tatami mat sa dojo"],
    ["Table Tennis Pingpong","Maliit na raket at bolang seluloyd","Mabilis na talbog sa berdeng lamesa","Spin sa pagpalo"],
    ["Baston ng Arnis","Pares ng yantok na pampalo at panangga","Pambansang sining ng pagtatanggol","Sinawali at anyo"],
    ["Basketbolista","Naglulubog ng bola sa sampung talampakang ring","Pasa at dribol sa court ng barangay","Suot ang jersey"],
    ["Archer sa Palaso","Paghila sa bagting ng busog","Tudla sa dilaw na gitna ng target","Pana at palaso"],
    ["Gymnast sa Balance Beam","Kahanga-hangang pagbaluktot at tumbling","Paglapag nang walang galaw sa kutson","Pagsayaw sa baras"],
    ["Atleta sa Palarong Pambansa","Nagsasanay araw-araw upang manalo","Kumakatawan sa kanilang probinsya","Pangarap ang gintong medalya"]
  ],
  "Pista at Tradisyon": [
    ["Sinulog","Sto. Niño","Cebu","Pit Senyor"],
    ["Ati-Atihan","Itim","Kalibo","Aklan"],
    ["Pahiyas","Kiping","Lucban","Quezon"],
    ["Panagbenga","Bulaklak","Baguio","Float"],
    ["MassKara","Maskara","Bacolod","Negros"],
    ["Kadayawan","Davao","Bunga","Pagdiriwang"],
    ["Dinagyang","Sayaw","Iloilo","Street"],
    ["Higantes","Angono","Papier-mâché","Rizal"],
    ["Moriones","Helmet","Marinduque","Centurion"],
    ["Simbang Gabi","Madaling-araw","Misa de Gallo","Siyam na gabi"],
    ["Noche Buena","Hatinggabi","Media noche","Handaan"],
    ["Flores de Mayo","Bulaklak","Reyna Elena","Mayo"],
    ["Santacruzan","Reyna","Prusisyon","Reynas"],
    ["Bisperas","Paghahanda","Pasko Eve","Beams"],
    ["Pasko","Parol","Simbang Gabi","December"],
    ["Bagong Taon","Pagsalubong sa unang araw ng Enero","Labindalawang bilog na prutas sa mesa","Ingay ng torotot at paputok"],
    ["Undas","Pag-alaala sa mga yumao sa sementeryo","Pagsisindi ng kandila sa tapat ng puntod","Pagsasama-sama ng pamilya"],
    ["Mahal na Araw","Panahon ng pagninilay at penitensya","Pag-awit ng pasyon at Visita Iglesia","Biyernes Santo"],
    ["Araw ng Kalayaan","Ika-labindalawa ng Hunyo sa kasaysayan","Pagwagayway ng watawat sa Kawit Cavite","Paggunita sa mga bayani"],
    ["Buwan ng Wika","Pagdiriwang sa wikang Filipino tuwing Agosto","Pagsusuot ng barong at filipiniana","Tula at balagtasan sa paaralan"],
    ["Todos Los Santos","Unang araw ng Nobyembre","Misa para sa lahat ng mga banal","Pagbisita sa mga libingan"],
    ["Balagtasan","Makabayang debate gamit ang tula","Lakandiwa na namamagitan sa dalawang makata","Sining ng tugma at sukat"],
    ["Pagpasan ng Santo","Pagbubuhat sa karosa ng imahen ng patron","Prusisyon sa buong kabayanan","Debosyon ng mga mananampalataya"],
    ["Visita Iglesia","Pagbisita sa pitong magkakaibang simbahan","Pagdarasal sa mga estasyon ng krus","Tradisyon sa Semana Santa"],
    ["Pabasa ng Pasyon","Walang-himpil na pag-awit ng buhay ni Hesus","Tradisyonal na tono ng pasyon","Tahanan ng deboto"],
    ["Senakulo","Pagsasadula ng paghihirap at kamatayan ni Kristo","Komedya at drama sa lansangan","Pako sa krus"],
    ["Salubong sa Pasko ng Pagkabuhay","Pagtatagpo ng muling nabuhay na Kristo at Maria","Pagtatanggal ng itim na belo ng anghel","Madaling-araw ng Linggo"],
    ["Kaamulan Festival","Pista ng pitong katutubong tribu sa Bukidnon","Tradisyonal na sayaw at tugtugin","Makulay na habi"],
    ["Pintados Festival","Pagpapakita ng sinaunang tato ng mga mandirigma","Pista ng Tacloban sa Leyte","Makulay na parada"],
    ["Lanzones Festival","Pasasalamat sa masaganang ani ng lanzones","Pista sa isla ng Camiguin","Sayawan sa kalsada"]
  ],
  "Bahay": [
    ["Kusina","Luto","Kalan","Exhaust"],
    ["Sala","Sofa","Sala set","Living"],
    ["Kuwarto","Kama","Privacy","Bedside"],
    ["Banyo","Shower","Grout","Drain"],
    ["Bubong","Ulan","Gutters","Rafter"],
    ["Bintana","Kurtina","Sill","Casement"],
    ["Pinto","Susi","Jamb","Threshold"],
    ["Hagdan","Akyat","Railing","Stringer"],
    ["Bakuran","Halaman","Fence","Perimeter"],
    ["Garahe","Sasakyan","Bay","Overhead"],
    ["Lababo","Hugas","Faucet","Basin"],
    ["Pridyider","Lamig","Compressor","Thermostat"],
    ["Kalan","Apoy","Burner","BTU"],
    ["Aparador","Damit","Shelves","Wardrobe"],
    ["Hapag-kainan","Salo-salo","Leaves","Dining"],
    ["Balkonahe","Tambayan sa labas ng ikalawang palapag","Rehas na bakal kung saan sumisimoy ang hangin","Tanawin sa kalsada"],
    ["Kisame","Itaas na bahagi ng bawat silid","Lalagyan ng ilaw at bentilador","Harang sa init ng bubong"],
    ["Sahig","Makintab na sahig na tabla o tiles","Binubunot upang kumintab","Nilalakaran sa loob ng tahanan"],
    ["Dingding","Matibay na pader na naghihiwalay sa mga kwarto","Sabitan ng mga kwadro at litrato ng pamilya","Pader ng bahay"],
    ["Altar sa Tahanan","Lalagyan ng mga imahen ng santo at krus","Lugar ng taimtim na panalangin ng pamilya","Kandila at rosaryo"],
    ["Labahan","Lugar kung saan naglalaba ng maruruming damit","Planggana sabon at poso","Kusot sa batya"],
    ["Sampayan","Tali o alambre sa bakuran","Sinasampayan ng basang damit sa araw","Sipit ng damit"],
    ["Asotea","Bukas na espasyo sa likod ng lumang bahay","Lugar ng pagpapahinga at taniman ng halaman","Balkonahe sa likod"],
    ["Silong ng Bahay","Lugar sa ilalim ng tradisyonal na bahay-kubo","Taguan ng mga kagamitan at kahoy","Kulungan ng manok"],
    ["Batalan","Hugasang bahagi sa likod ng bahay-kubo","Lalagyan ng tapayan ng tubig","Sinaunang lababo"],
    ["Tarangkahan","Pintuang bakal o kahoy sa bakod","Bungad bago pumasok sa bakuran","May kandado sa gabi"],
    ["Kaban ng Bigas","Malaking kahoy na lalagyan ng butil ng palay","Imbakan ng pagkain ng pamilya","Yaman sa tahanan"],
    ["Dampa","Maliit at payak na tirahan sa bukid","Yari sa pawid kawayan at nipa","Simple at payapang buhay"],
    ["Entreswelo","Mababang palapag na pinauupahan sa mga nangungupahan","Silid sa silong ng malaking gusali","Tirahan"],
    ["Bintana ng Capiz","Tradisyonal na bintanang gawa sa kabibeng capiz","Dumudulas na kahoy na frame","Klasikong disenyong Pilipino"]
  ],
  "Pang-araw-araw na Buhay": [
    ["Gising","Alarm","Snooze","Circadian"],
    ["Ligo","Sabon","Rinse","Exfoliate"],
    ["Almusal","Umaga","Plato","Continental"],
    ["Biyahe","Sakay","Commute","Rush hour"],
    ["Trabaho","Sahod","Shift","Overtime"],
    ["Meryenda","Hapon","Snack","4 o'clock"],
    ["Uwi","Bahay","Commute","Decompression"],
    ["Tulog","Unan","REM","Circadian"],
    ["Laba","Damit","Rinse cycle","Spin"],
    ["Hugas","Plato","Rinse","Lather"],
    ["Luto","Kusina","Prep","Reduction"],
    ["Grocery","Kariton","Aisle","List"],
    ["Bayad","Sukli","Invoice","Receipt"],
    ["Pila","Hintay","Queue","First come"],
    ["Trapik","Kalsada","Rush hour","Bottleneck"],
    ["Pagsasaing","Paghuhugas ng bigas at pagsukat ng tubig","Pagpapakulo sa kaldero hanggang maluto","Pangunahing pagkain sa hapag"],
    ["Pagwawalis ng Bakuran","Pagtanggal ng mga tuyong dahon gamit ang walis-tingting","Paglilinis ng alikabok sa paligid","Gawain tuwing umaga"],
    ["Pamamalengke sa Umaga","Pagtungo sa palengke upang bumili ng sariwang ulam","Pagtatawad sa presyo ng tindera","Bayong na puno ng gulay"],
    ["Tambay sa Kanto","Kwentuhan ng magkakapitbahay sa hapon","Panonood sa mga dumaraang sasakyan","Pampalipas-oras ng barkada"],
    ["Paghahanda ng Handaan","Paghahain ng maraming pagkain para sa bisita","Okasyon tulad ng kaarawan o piyesta","Kasiyahan sa bahay"],
    ["Pagtitingi sa Tindahan","Pagbili ng tingi-tinging mantika o asukal","Sari-sari store sa kapitbahay","Barya-baryang pambili"],
    ["Pagpapalista ng Utang","Pagsulat sa maliit na notebook ng tindahan","Babayaran pagdating ng araw ng sweldo","Listahan sa tindahan"],
    ["Pagsahod sa Trabaho","Araw ng kinsenas at katapusan","Pambayad sa mga gastusin at kuryente","Bunga ng buong buwang pagod"],
    ["Panggatong sa Kusina","Pagsisibak ng kahoy o paggamit ng uling","Pansindi sa kalan para magluto","Usok sa kusina"],
    ["Pagpasok sa Tanggapan","Pagsakay sa jeep patungo sa trabaho","Pagsusuot ng maayos na uniporme","Alas-otso ng umaga"],
    ["Pagsalubong sa Umuuwi","Masayang yakap at 'mano po' sa dumarating","Pag-abot ng tsinelas at malamig na tubig","Pagbabalik mula sa trabaho"],
    ["Pagpapahinga sa Sala","Pag-upo sa sopa pagkatapos ng mahabang araw","Panonood ng balita sa telebisyon","Kwentuhan bago matulog"],
    ["Kwentuhan sa Hapon","Pag-inom ng kape habang nag-uusap sa balkonahe","Kumustahan sa mga nangyari sa maghapon","Relaks na sandali"],
    ["Panonood ng Teleserye","Panonood ng sikat na serye pagkatapos ng hapunan","Pagsusubaybay sa kwento ng bida","Gawain ng buong pamilya"],
    ["Dasal Bago Matulog","Taimtim na pasasalamat sa mga biyaya ng araw","Paghingi ng kapayapaan at gabay","Pikit ng mata sa gabi"]
  ],
  "Mga Lugar sa Pilipinas": [
    ["Boracay","Puting buhangin","Station 2","White beach"],
    ["Palawan","Lagoon","Underground river","El Nido"],
    ["Baguio","Malamig","Session Road","Strawberry"],
    ["Cebu","Lechon","Sinulog","IT Park"],
    ["Vigan","Kalesa","Heritage","Calle Crisologo"],
    ["Davao","Durian","Mount Apo","Kadayawan"],
    ["Bulkang Mayon","Perpektong kono","Albay","Pyroclastic"],
    ["Chocolate Hills","Bohol","Tarsier","Carmen"],
    ["Intramuros","Pader","Fort Santiago","Walled city"],
    ["Rizal Park","Monumento","Manila","Bonifacio"],
    ["Siargao","Surfing","Cloud 9","Teardrop"],
    ["Banaue","Hagdan-hagdang palayan","Ifugao","8th wonder"],
    ["Tagaytay","Taal","Ridge","Picnic Grove"],
    ["Batanes","Bato","Ivatan","Stone houses"],
    ["Coron","Lawa","Kayangan","Busuanga"],
    ["Sagada","Mga nakabiting kabaong sa matarik na bangin","Malamig na simoy at Sumaguing Cave","Mabangong kape sa Cordillera"],
    ["Hundred Islands","Pangkat ng maraming pulo sa Pangasinan","Pagsakay sa bangka at pag-island hopping","Maliit na mga isla sa Alaminos"],
    ["Enchanted River","Hiwagang asul at malalim na ilog sa Hinatuan","Mahiwagang pagpapakain sa mga isda","Likas na ganda ng Surigao del Sur"],
    ["Bulkang Taal","Maliit na bulkan sa gitna ng lawa","Tanawin mula sa Tagaytay ridge","Lawa ng Batangas"],
    ["Mt. Apo","Pinakamataas na bundok sa buong Pilipinas","Matatagpuan sa pagitan ng Davao at Cotabato","Tahanan ng Philippine Eagle"],
    ["Mt. Pulag","Tanyag na dagat ng mga ulap sa tuktok","Napakalamig na temperatura sa kabundukan","Ikalawang pinakamataas na bundok"],
    ["Calle Crisologo","Makasaysayang kalyeng bato sa Vigan","Lumang kalesang dumaraan sa cobblestone","Mga bahay na bato noong panahon ng Kastila"],
    ["Puerto Princesa Underground River","Ilog sa ilalim ng kuweba na UNESCO site","Bangka sa loob ng madilim na kuweba","Likas na kababalaghan ng Palawan"],
    ["San Juan La Union","Bantog na surfing capital ng hilaga","Matatayog na alon sa dalampasigan ng Elyu","Tambayan sa tabi ng dagat"],
    ["El Nido","Matatayog na limestone cliffs sa gitna ng dagat","Nakatagong malinaw na lagoon at baybayin","Paraiso ng mga turista sa Palawan"],
    ["Camiguin Island","Isla kung saan sumisikat ang Lanzones Festival","Sunken Cemetery na may krus sa dagat","Puting buhangin sa White Island"],
    ["Bohol Island","Tahanan ng maliliit na Tarsier","Bantog na Loboc River Cruise at Chocolate Hills","Panglao white beach"],
    ["Luneta Park","Bantayog ng pambansang bayaning si Dr. Jose Rizal","Makasaysayang liwasan sa puso ng Maynila","Pasyalan ng mga pamilya tuwing Linggo"],
    ["Bataan","Dambana ng Kagitingan sa tuktok ng Mt. Samat","Makasaysayang Death March noong digmaan","Lalawigan ng kabayanihan"],
    ["Apo Reef","Pinakamalaking contiguous coral reef sa bansa","Santwaryo ng mga pating pagong at corals","Paraiso ng mga diver sa Occidental Mindoro"]
  ]
};

module.exports = { tagalogCategories };
