const englishCategoriesPart2 = {
  "Jobs": [
    ["Doctor","Stethoscope","Diagnosis","Rounds"],
    ["Nurse","Ward","Vitals","Triage"],
    ["Programmer","Code","Debug","Deploy"],
    ["Teacher","Lesson","Rubric","Scaffolding"],
    ["Engineer","Blueprint","Tolerance","Load"],
    ["Chef","Kitchen","Mise en place","Julienne"],
    ["Pilot","Cockpit","Altitude","Callsign"],
    ["Lawyer","Court","Brief","Precedent"],
    ["Police Officer","Badge","Patrol","Dispatch"],
    ["Farmer","Harvest","Yield","Rotation"],
    ["Architect","Draft","Cantilever","Elevation"],
    ["Designer","Palette","Kerning","Mockup"],
    ["Firefighter","Hose","Suppression","Thermal"],
    ["Dentist","Drill","Plaque","Occlusion"],
    ["Journalist","Headline","Source","Byline"],
    ["Astronaut","Pressurized spacesuit","Zero gravity EVA","Orbital commander"],
    ["Detective","Magnifying case file","Crime scene evidence","Suspect interrogation"],
    ["Vet","Animal healthcare","Clinic examination table","Rabies vaccine"],
    ["Plumber","Pipe wrench grip","Drain blockage clearance","Water valve fit"],
    ["Electrician","Insulated wire stripper","Circuit breaker panel","Multimeter voltage"],
    ["Pharmacist","Medication dispensary","Prescription verification","Dosage label"],
    ["Mechanic","Engine torque wrench","Hydraulic lift bay","Diagnostic scanner"],
    ["Photographer","Shutter aperture lens","Adjustable tripod mount","Studio flash softbox"],
    ["Carpenter","Dovetail joint wood","Chisel hand smoothing","Miter saw bevel"],
    ["Scientist","Sterile lab coat","Hypothesis testing","Petri dish culture"],
    ["Librarian","Decimal catalog index","Quiet archive aisles","Book circulation desk"],
    ["Baker","Flour dusted counter","Kneaded sourdough loaf","Proofing basket"],
    ["Barber","Straight razor fade","Clippers guard trim","Leather strop hone"],
    ["Judge","Wooden gavel strike","Black judicial robe","Courtroom ruling bench"],
    ["Paramedic","Ambulance trauma kit","Emergency defibrillator","First responder triage"]
  ],
  "School": [
    ["Teacher","Lesson","Whiteboard","Pedagogy"],
    ["Student","Class","Desk","Cohort"],
    ["Exam","Score","Proctor","Rubric"],
    ["Classroom","Desks","Rows","Acoustics"],
    ["Homework","Deadline","Assignment","Prompt"],
    ["Blackboard","Chalk","Dust","Squeaky"],
    ["Mathematics","Equation","Proof","Theorem"],
    ["Science","Experiment","Hypothesis","Variable"],
    ["Library","Books","Catalogue","Dewey"],
    ["Principal","Office","Discipline","Tenure"],
    ["Report Card","Grades","Comments","Transcript"],
    ["Recess","Break","Playground","Unstructured"],
    ["Notebook","Lines","Margin","Spiral"],
    ["Laboratory","Goggles","Reagent","Fume hood"],
    ["Graduation","Diploma","Regalia","Commencement"],
    ["Backpack","Shoulder straps","Book compartment","Zipper pocket"],
    ["Pencil","Graphite lead","Pink eraser crown","Sharpened wooden core"],
    ["Cafeteria","Tray lunchline","Hot meal service","Communal dining bench"],
    ["Hallway","Locker rows","Passing period rush","Class corridor"],
    ["Desk","Laminate writing top","Attached chair frame","Book storage cubby"],
    ["Calculator","Scientific keypad","Display LCD screen","Equation solver"],
    ["Attendance","Morning roll call","Present tally mark","Absent record sheet"],
    ["Field Trip","Parent permission slip","Yellow school bus ride","Museum guided tour"],
    ["School Bell","Electromechanical chime","Class dismissal ring","Tardy alert tone"],
    ["Semester","Academic term half","Midterm examination","Credit hours"],
    ["Ruler","Centimeter gradations","Straight drawing edge","Metric measuring stick"],
    ["Eraser","Rubber smudge remover","Friction eraser crumbs","Graphite lifter"],
    ["Textbook","Chapter reading index","Glossary terminology","Hardcover study guide"],
    ["Locker","Combination dial turn","Vented steel door","Personal book locker"],
    ["Playground","Swings and slides","Recess asphalt blacktop","Jungle gym frame"]
  ],
  "Places": [
    ["Airport","Runway","Check-in","Terminal"],
    ["Hospital","Ward","Sterile","Triage"],
    ["School","Bell","Halls","Lockers"],
    ["Mall","Shops","Escalator","Anchor store"],
    ["Beach","Sand","Shore","Undertow"],
    ["Restaurant","Menu","Cover","Reservations"],
    ["Hotel","Key card","Concierge","Occupancy"],
    ["Park","Bench","Green space","Gazebo"],
    ["Museum","Exhibit","Curator","Provenance"],
    ["Library","Shelves","Quiet","Stacks"],
    ["Cinema","Screen","Usher","Projection"],
    ["Bakery","Oven","Proofing","Sourdough"],
    ["Stadium","Crowd","Capacity","Tier"],
    ["Market","Stalls","Vendor","Footfall"],
    ["Zoo","Enclosure","Keeper","Enrichment"],
    ["Supermarket","Aisle grocery carts","Barcode checkout scanner","Produce display"],
    ["Amusement Park","Thrill roller coaster","Carnival games midway","Ferris wheel ride"],
    ["Aquarium","Underwater viewing tunnel","Acrylic marine tank","Coral habitat reef"],
    ["Post Office","Postal stamp window","Package weighing scale","Mail collection box"],
    ["Bank","Secure cash vault","Teller service counter","ATM vestibule lobby"],
    ["Gym","Free weights dumbbell rack","Treadmill cardio row","Locker shower room"],
    ["Theater","Velvet stage curtain","Orchestra pit seats","Live theatrical show"],
    ["Church","Stained glass sanctuary","High steeple bell","Altar wooden pews"],
    ["Forest","Canopy woodland trails","Fallen log ecosystem","Mossy bark grove"],
    ["Harbor","Sheltered boat docks","Mooring bollard posts","Lighthouse beacon signal"],
    ["Pharmacy","Prescription drug counter","Health supplement aisle","Pharmacist consultation"],
    ["Castle","Stone perimeter moat","Defensive crenelations","Iron portcullis gate"],
    ["Campground","Pitched canvas tents","Stone campfire ring","Wilderness trail head"],
    ["Subway Station","Underground turnstile gate","Tiled platform edge","Transit track route"],
    ["Barber Shop","Hydraulic swivel chair","Striped barber pole","Mirror styling station"]
  ],
  "Transportation": [
    ["Car","Steering","Horsepower","Torque"],
    ["Bus","Stop","Route","Bay"],
    ["Train","Tracks","Platform","Gauge"],
    ["Airplane","Wings","Fuselage","Aileron"],
    ["Motorcycle","Helmet","Throttle","Kickstart"],
    ["Bicycle","Pedals","Derailleur","Chainring"],
    ["Ship","Anchor","Hull","Draught"],
    ["Taxi","Meter","Fare","Dispatch"],
    ["Subway","Tunnel","Platform","Pantograph"],
    ["Helicopter","Rotor","Hover","Collective"],
    ["Ferry","Crossing","Ramp","Berth"],
    ["Scooter","Kickstand","Throttle","Moped"],
    ["Truck","Cargo","Payload","Axle"],
    ["Cable Car","Wire","Grip","Counterweight"],
    ["Rocket","Launch","Thrust","Payload fairing"],
    ["Submarine","Periscope ocular lens","Ballast dive tank","Submerged sonar ping"],
    ["Hot Air Balloon","Wicker passenger basket","Propane burner flame","Thermal lift envelope"],
    ["Tram","Electric street rail","Overhead wire catenary","Streetcar stop"],
    ["Hovercraft","Pressurized skirt cushion","Dual terrain glide","Lift fan duct"],
    ["Skateboard","Urethane wheel trucks","Sandpaper grip deck","Tail kick concave"],
    ["Bulldozer","Heavy steel treads","Front earthmoving blade","Hydraulic push ripper"],
    ["Tractor","Treaded rear drive wheels","Farm plow implement","Diesel tractor drawbar"],
    ["Ambulance","Emergency flashing beacons","Siren wail frequency","Stretcher bay interior"],
    ["Firetruck","Telescopic rescue ladder","High-pressure water pump","Fire hydrant coupling"],
    ["Yacht","Polished luxury deck","White fabric mainsail","Marina berth slip"],
    ["Monorail","Elevated straddle beam","Pneumatic tire bogey","Guide rail track"],
    ["Canoe","Carved wooden paddle","Symmetrical lightweight hull","River riverway touring"],
    ["Gondola","Venetian canal hull","Single row oarlock","Traditional ferra bow"],
    ["Rickshaw","Two-wheel passenger carriage","Human-drawn chassis","Canopy shaded cart"],
    ["Spaceship","Rocket boost thrusters","Pressurized cockpit capsule","Thermal heat tiles"]
  ],
  "Clothing": [
    ["Shirt","Collar","Button-down","Placket"],
    ["Pants","Pockets","Waistband","Inseam"],
    ["Jacket","Zipper","Lining","Lapel"],
    ["Shoes","Laces","Sole","Welt"],
    ["Hat","Brim","Crown","Millinery"],
    ["Dress","Hemline","Silhouette","Bodice"],
    ["Socks","Cuff","Moisture-wicking","Hosiery"],
    ["Uniform","Matching","Insignia","Regulation"],
    ["Hoodie","Hood","Kangaroo pocket","Fleece"],
    ["Jeans","Denim","Rivets","Selvedge"],
    ["Scarf","Neck","Drape","Voile"],
    ["Gloves","Fingers","Grip","Gusset"],
    ["Belt","Buckle","Holes","Tongue"],
    ["Suit","Tie","Bespoke","Notch"],
    ["Pajamas","Bedtime","Flannel","Drawstring"],
    ["Sweater","Knitted wool weave","Ribbed collar cuff","Cozy pullover layer"],
    ["Sunglasses","UV polarized lenses","Tinted eye frames","Sun glare protection"],
    ["Raincoat","Waterproof vinyl hood","Sealed rain seams","Yellow storm slicker"],
    ["Sneakers","Cushioned rubber sole","Athletic lace system","Breathable mesh upper"],
    ["Swimsuit","Stretchy nylon fabric","Beach surf wear","Chlorine resistant fit"],
    ["Tie","Silk four-in-hand knot","Formal dress collar","Tapered neck blade"],
    ["Boots","Tough leather upper","Lugged tread outsole","Reinforced ankle collar"],
    ["Coat","Insulated winter outer","Buttoned tailored lapel","Heavy cold-weather drape"],
    ["Vest","Sleeveless torso tailored","Waistcoat button row","Formal layering piece"],
    ["Cap","Adjustable snapback strap","Curved front brim visor","Structured baseball crown"],
    ["Apron","Front chest bib protection","Waist strap tie knots","Kitchen utility pocket"],
    ["Sandals","Open-toe strap design","Flat cork footbed","Casual summer slip-on"],
    ["Shorts","Knee-length cut hem","Warm weather comfort","Elastic waist drawstring"],
    ["Robe","Plush terrycloth collar","Removable waist sash","Comfortable lounge wrap"],
    ["Mittens","Enclosed single finger pocket","Warm fleece lining","Snow winter insulation"]
  ],
  "Household Objects": [
    ["Vase","Flowers","Ceramic","Faience"],
    ["Pillow","Soft","Filling","Pillowcase"],
    ["Umbrella","Rain","Canopy","Ferrule"],
    ["Candle","Flame","Wick","Paraffin"],
    ["Sofa","Cushion","Upholstery","Chaise"],
    ["Refrigerator","Cold","Compressor","Thermostat"],
    ["Mirror","Reflection","Silver backing","Silvering"],
    ["Blanket","Warmth","Weave","Tog"],
    ["Toaster","Bread","Element","Browning"],
    ["Broom","Sweep","Bristles","Dustpan"],
    ["Lamp","Shade","Watt","Lumens"],
    ["Curtain","Window","Rod","Pinch pleat"],
    ["Kettle","Whistle","Limescale","Spout"],
    ["Vacuum","Suction","Filter","Cyclone"],
    ["Bookshelf","Rows","Load-bearing","Dowel"],
    ["Clock","Ticking pendulum swing","Circular hour dial face","Wall gear mechanism"],
    ["Microwave","Rotating glass turntable","Magnetron radiation waves","Preset timer chime"],
    ["Blender","Whirling base blade","Glass measuring jar","Smoothie pulse button"],
    ["Iron","Steaming soleplate holes","Wrinkle smoothing heat","Distilled water tank"],
    ["Fan","Rotating aerodynamic blades","Oscillating motor swivel","Cool airflow speed"],
    ["Mug","Thick ceramic loop handle","Hot coffee vessel","Glazed earthenware cup"],
    ["Scissors","Sharp dual pivot blades","Plastic finger loops","Precision cutting shears"],
    ["Rug","Woven fiber pile floor","Decorative decorative tassel","Non-slip underlay"],
    ["Flashlight","Reflector focus beam","Handheld battery barrel","Emergency LED torch"],
    ["Towel","Absorbent looped cotton","Bathroom drying rack","Soft terrycloth weave"],
    ["Trash Can","Foot pedal flip lid","Lined garbage container","Kitchen waste receptacle"],
    ["Hanger","Contoured shoulder curve","Swivel metal hook","Closet rod organiser"],
    ["Key","Precision cut notches","Tumbler lock cylinder","Brass keychain ring"],
    ["Toothbrush","Nylon cleaning bristles","Ergonomic grip handle","Daily dental hygiene"],
    ["Doorbell","Illuminated chime push","Electronic entry alert","Front door intercom"]
  ],
  "Nature": [
    ["Mountain","Peak","Ascent","Treeline"],
    ["River","Current","Meander","Watershed"],
    ["Ocean","Tide","Salinity","Thermocline"],
    ["Forest","Canopy","Understory","Duff"],
    ["Volcano","Lava","Vent","Caldera"],
    ["Waterfall","Drop","Plunge pool","Cataract"],
    ["Desert","Dunes","Arid","Erg"],
    ["Island","Shore","Atoll","Littoral"],
    ["Cloud","Sky","Cumulus","Virga"],
    ["Rain","Puddle","Drizzle","Petrichor"],
    ["Thunder","Rumble","Lightning rod","Cumulonimbus"],
    ["Cave","Echo","Stalactite","Karst"],
    ["Rainbow","Colors","Refraction","Arc"],
    ["Glacier","Ice","Moraine","Crevasse"],
    ["Meadow","Wildflowers","Grassland","Vernal"],
    ["Canyon","Eroded gorge cliff","Stratified stone walls","Deep river canyon"],
    ["Tornado","Violent rotating vortex","Funnel cloud touchdown","High-speed cyclonic gale"],
    ["Jungle","Dense tropical rainforest","Thick liana vines","Biodiverse canopy"],
    ["Geyser","Boiling geothermal plume","Superheated ground vent","Periodic pressure eruption"],
    ["Swamp","Stagnant marsh wetland","Waterlogged cypress trees","Peat bog mud"],
    ["Cliff","Perpendicular rock face","Sheer precipice drop","Coastal headland crag"],
    ["Oasis","Desert palm spring","Natural groundwater basin","Arid trade haven"],
    ["Coral Reef","Calcium carbonate colony","Vibrant marine polyps","Underwater barrier reef"],
    ["Iceberg","Calved glacial shelf","Floating submerged mass","Frigid ocean drift"],
    ["Aurora","Atmospheric solar curtains","Polar magnetic glow","Boreal green light"],
    ["Sand Dune","Wind-sculpted sand ridge","Shifting slip face","Desert wave crest"],
    ["Lagoon","Shallow coastal water","Coral reef barrier","Quiet seawater pool"],
    ["Pond","Small tranquil waterbody","Floating lily pads","Freshwater ecosystem"],
    ["Hot Spring","Mineral thermal pool","Volcanic ground heat","Soothing natural bath"],
    ["Valley","Lowland between ranges","Fertile river basin","Scenic mountain hollow"]
  ],
  "Music": [
    ["Guitar","Strings","Chord","Fretboard"],
    ["Piano","Keys","Hammer","Sostenuto"],
    ["Drums","Beat","Snare","Polyrhythm"],
    ["Violin","Bow","Rosin","Vibrato"],
    ["Hip-Hop","Rap","Sample","Breakbeat"],
    ["Jazz","Improvisation","Swing","Bebop"],
    ["Concert","Stage","Setlist","Soundcheck"],
    ["Microphone","Voice","Phantom power","Cardioid"],
    ["Playlist","Queue","Shuffle","Curation"],
    ["Chorus","Repeat","Hook","Refrain"],
    ["Melody","Tune","Interval","Motif"],
    ["Bass","Low","Groove","Slap"],
    ["DJ","Turntable","Crossfade","BPM"],
    ["Album","Tracks","Mastering","Liner notes"],
    ["Encore","Again","Standing ovation","Bow"],
    ["Saxophone","Curved brass body","Single wooden reed","Expressive jazz horn"],
    ["Trumpet","Three piston valves","Bright brass flare bell","Fanfare lip buzz"],
    ["Flute","Slender silver pipe","Side-blown embouchure","Keyed woodwind trill"],
    ["Symphony","Full orchestra score","Four formal movements","Conductor baton cue"],
    ["Metronome","Ticking tempo pendulum","Audible beat counter","Rhythm practice guide"],
    ["Harmonizer","Layered vocal intervals","Polyphonic pitch blending","Choral chord blend"],
    ["Harp","Triangular wooden frame","Plucked nylon strings","Sweeping angel glissando"],
    ["Solo","Featured instrumental break","Virtuoso spotlight melody","Expressive lead run"],
    ["Accordion","Pleated wind bellows","Treble button keyboard","Folk squeeze box"],
    ["Autotune","Digital pitch correction","Electronic vocal timbre","Studio scale snap"],
    ["Turntable","Vinyl needle stylus","Rotating slipmat platter","Hip-hop scratch audio"],
    ["Acoustic","Non-electric instrument resonance","Natural wood chamber","Unamplified pure sound"],
    ["Tempo","Metronome beat speed","Pace beats per minute","Allegro timing tempo"],
    ["Ukulele","Four nylon strings","Hawaiian island strum","Small wooden resonance"],
    ["Orchestra","Concert master violin","Sectional acoustic arrangement","Grand philharmonic hall"]
  ],
  "Internet Culture": [
    ["Meme","Template","Remix","Spread"],
    ["Going Viral","Shares","Trending","Algorithm"],
    ["Clickbait","Headline","Title","Engagement bait"],
    ["Reaction Video","Response","Commentary","Watch time"],
    ["Thread","Replies","Nested","Sub-reply"],
    ["Lurker","Silent","Read-only","Passive"],
    ["Troll","Provoke","Bait","Flame war"],
    ["Screenshot","Capture","Evidence","Crop"],
    ["Fan Edit","Montage","Clip","Tributes"],
    ["Unboxing","Package","First look","Reveal"],
    ["POV","Perspective","First-person","Immersive"],
    ["Influencer","Following","Sponsorship","Niche"],
    ["Livestream","Real-time","Donations","Chat"],
    ["Username","Handle","@","Identity"],
    ["Trending Page","Popular","Moment","Spike"],
    ["Hashtag","Metadata search tag","Pound symbol prefix","Categorized topic trend"],
    ["Emoji","Graphic pictogram icon","Expressive smileys face","Digital keyboard reaction"],
    ["Podcast","Serialized audio show","On-demand episode feed","Host conversational studio"],
    ["Rickroll","Deceptive hyperlink prank","Never Gonna Give You Up","Classic viral bait"],
    ["Avatar","Online profile representation","Digital user likeness","Account icon graphic"],
    ["Gif","Short looping animation","Soundless image sequence","Reaction clip format"],
    ["Notification","Audible ping alert","Red badge counter icon","Mobile push message"],
    ["DM","Private direct message","One-to-one inbox chat","Confidential text reply"],
    ["Feed","Algorithmic content stream","Endless vertical scroll","Personalized social timeline"],
    ["Clicker","Idle incremental tapping","Multiplier upgrades loop","Screen click count"],
    ["Subscribe","Account follow bell","Subscriber metric tier","Channel update opt-in"],
    ["Vlogger","Personal video diary","Handheld camera vlog","Daily creator life"],
    ["Spoilers","Crucial plot detail leak","Endgame secret revelation","Spoiler warning tag"],
    ["Ban","Account suspension notice","Forum access restriction","Moderator ban hammer"],
    ["Shadowban","Undisclosed visibility throttle","Silent reach suppression","Hidden search profile"]
  ],
  "Fantasy": [
    ["Dragon","Scales","Hoard","Wyvern"],
    ["Wizard","Wand","Tome","Arcane"],
    ["Knight","Armor","Oath","Pauldron"],
    ["Castle","Turret","Drawbridge","Battlement"],
    ["Magic","Spell","Mana","Incantation"],
    ["Sword","Blade","Hilt","Cruciform"],
    ["Dungeon","Cells","Torch","Keep"],
    ["Potion","Bottle","Elixir","Alchemist"],
    ["Monster","Roar","Lair","Bestiary"],
    ["Princess","Crown","Tower","Consort"],
    ["Elf","Pointed ears","Lithe","Sylvan"],
    ["Goblin","Cave","Green","Cunning"],
    ["Spellbook","Runes","Glyphs","Codex"],
    ["Crystal Ball","Gaze","Divination","Scrying"],
    ["Portal","Gateway","Vortex","Rift"],
    ["Unicorn","Spiraled forehead horn","Pure white mythical horse","Untamable forest beast"],
    ["Griffin","Eagle wings and talons","Noble lion hindquarters","Gold hoard guardian"],
    ["Mermaid","Glistening ocean tail","Submarine siren song","Undersea royal domain"],
    ["Phoenix","Radiant fire plumage","Ash nest rebirth cycle","Immortal sun bird"],
    ["Wand","Carved wooden magical focus","Channeled spell core","Somatic flick gesture"],
    ["Shield","Heraldic steel emblem","Defensive arrow deflection","Sturdy arm strap"],
    ["Vampire","Nocturnal sharp fangs","Bloodlust immortality","Shadow cloaked aristocrat"],
    ["Werewolf","Full moon transformation","Feral lupine howling","Beast claw fury"],
    ["Golem","Animated mud and clay","Carved rune forehead","Silent guardian construct"],
    ["Magic Carpet","Airborne woven tapestry","Levitating sky transit","Enchanted thread weave"],
    ["Enchantress","Mesmerizing charm hex","Fey spellcraft mistress","Arcane glamour aura"],
    ["Dwarves","Underground mountain forge","Braided beard lineage","Master gem smiths"],
    ["Necromancer","Bone reanimation ritual","Dark soul binding","Forbidden crypt rites"],
    ["Grail","Sacred golden chalice","Eternal life relic","Legendary knight quest"],
    ["Fairy","Gossamer iridescent wings","Luminescent fairy dust","Enchanted woodland sprite"]
  ],
  "Science & Space": [
    ["Atom","Nucleus","Electron","Valence"],
    ["Gravity","Fall","Acceleration","Geodesic"],
    ["DNA","Helix","Nucleotide","Chromosome"],
    ["Microscope","Lens","Resolution","Magnification"],
    ["Experiment","Hypothesis","Control","Variable"],
    ["Electricity","Current","Conductor","Ohm"],
    ["Fossil","Ancient","Strata","Amber"],
    ["Telescope","Stars","Aperture","Refraction"],
    ["Astronaut","Spacesuit","EVA","Microgravity"],
    ["Moon","Crater","Phases","Libration"],
    ["Mars","Red","Dust storm","Olympus Mons"],
    ["Black Hole","Singularity","Event horizon","Hawking"],
    ["Galaxy","Spiral","Disk","Nebula"],
    ["Satellite","Orbit","Telemetry","Geostationary"],
    ["Comet","Tail","Nucleus","Coma"],
    ["Supernova","Cataclysmic stellar explosion","Expanding shockwave flash","Heavy element forge"],
    ["Nebula","Glowing interstellar dust cloud","Stellar nursery incubator","Ionized gas pillars"],
    ["Planet","Gravitational clearing sphere","Solar orbital path","Atmospheric planetary body"],
    ["Asteroid","Irregular space rock","Main asteroid belt","Impact crater geology"],
    ["Molecule","Covalently bonded atoms","Chemical structural formula","Molecular compound mass"],
    ["Quantum","Subatomic wave packet","Superposition probability","Particle spin duality"],
    ["Solar Eclipse","Moon solar disc alignment","Total darkness corona","Umbral shadow path"],
    ["Meteor","Atmospheric entry streak","Blazing shooting star","Melted friction fireball"],
    ["Magnetism","Magnetic flux lines","Attracting opposing poles","Ferromagnetic alignment"],
    ["Photon","Discrete light packet","Zero rest mass quantum","Speed of light wave"],
    ["Evolution","Generational natural selection","Adaptation survival trait","Ancestral cladogram tree"],
    ["Radioactivity","Atomic nuclear decay","Ionizing alpha emission","Half-life decay clock"],
    ["Microbiology","Bacterial cell culture","Petri dish agar colony","Microscopic pathogen study"],
    ["Vacuum","Absolute pressure void","Zero air matter density","Cosmic outer expanse"],
    ["Rover","Wheeled robotic explorer","Autonomous planetary drill","Sample analysis sensor"]
  ],
  "Brands & Social Media": [
    ["Apple","iPhone","Bitten logo","Cupertino"],
    ["Samsung","Galaxy","AMOLED","Chaebol"],
    ["Microsoft","Windows","Redmond","Enterprise"],
    ["Google","Search","Crawl","PageRank"],
    ["Sony","PlayStation","Kazuo","Trinitron"],
    ["Nintendo","Switch","Joy-Con","Kyoto"],
    ["TikTok","Short video","FYP","ByteDance"],
    ["Instagram","Stories","Grid","Reels"],
    ["YouTube","Subscribe","Thumbnail","AdSense"],
    ["Facebook","Friends","News feed","Zuckerberg"],
    ["Reddit","Subreddit","Upvote","Karma"],
    ["Discord","Server","Bot","Nitro"],
    ["Snapchat","Streak","Snap map","Lenses"],
    ["Spotify","Playlist","Wrapped","Discover Weekly"],
    ["Adobe","Creative","Illustrator","Raster"],
    ["Netflix","Red N streaming logo","Binge watching platform","Original content studio"],
    ["Amazon","Smiley arrow delivery box","Prime shipping membership","Global cloud retail"],
    ["Twitter","Blue bird microblog","Character tweet limit","Retweet quote thread"],
    ["Tesla","Electric powertrain motor","Autopilot camera array","Falcon wing doors"],
    ["Nike","Iconic swoosh emblem","Athletic performance footwear","Just Do It campaign"],
    ["McDonald's","Golden arches sign","Happy meal packaging","Big Mac special sauce"],
    ["Starbucks","Green twin-tail siren","Custom Frappuccino roast","Espresso cafe franchise"],
    ["Disney","Mickey silhouette ears","Cinderella castle kingdom","Animated film empire"],
    ["Lego","Interlocking plastic bricks","Studded building plates","Custom modular minifigure"],
    ["Coca-Cola","Iconic dynamic ribbon","Contour glass bottle","Secret caramel soda recipe"],
    ["WhatsApp","Green phone speech icon","End-to-end chat encryption","Instant voice messaging"],
    ["PlayStation","Geometric button symbols","DualSense haptic feedback","Flagship gaming console"],
    ["Xbox","Luminous green sphere","Game Pass subscription","Modular wireless controller"],
    ["Twitch","Purple live streaming icon","Real-time chat emotes","Broadcast streamer community"],
    ["Pinterest","Visual idea board pinning","DIY inspiration gallery","Curated image collection"]
  ],
  "Hobbies": [
    ["Painting","Canvas","Brush","Impasto"],
    ["Photography","Lens","Exposure","Bokeh"],
    ["Gardening","Soil","Mulch","Propagation"],
    ["Reading","Pages","Annotation","Deep reading"],
    ["Cooking","Recipe","Mise en place","Reduction"],
    ["Hiking","Trail","Elevation","Switchback"],
    ["Fishing","Hook","Cast","Tippet"],
    ["Knitting","Yarn","Needle","Purl"],
    ["Chess","Checkmate","Gambit","Zugzwang"],
    ["Camping","Tent","Bivouac","Deadfall"],
    ["Pottery","Clay","Wheel","Kiln"],
    ["Cycling","Pedals","Cadence","Chainring"],
    ["Dancing","Rhythm","Count","Musicality"],
    ["Collecting","Shelf","Provenance","Mint"],
    ["Woodworking","Sawdust","Grain","Dovetail"],
    ["Baking","Oven sourdough rise","Accurate gram flour measure","Golden pastry crust"],
    ["Calligraphy","Chisel edged calligraphy nib","Drawn ornamental flourishes","Sumi black ink"],
    ["Birdwatching","Compact field binoculars","Species life list tracker","Feather plumage spotting"],
    ["Scrapbooking","Photo cutout collage","Archival glue stickers","Personal memory book"],
    ["Origami","Square un-cut paper fold","Folded paper crane","Sharp crease technique"],
    ["Archery","Recurve target bow","Quiver with carbon arrows","Finger tab release"],
    ["Quilting","Patchwork textile pieces","Layered thermal batting","Decorative geometric stitching"],
    ["Astronomy","Deep sky star chart","Refractor optical mount","Constellation night gaze"],
    ["Bowling","Polished wooden ball track","Hook curve spin delivery","Ten pin spare pick"],
    ["Juggling","Three-ball cascade pattern","Rhythmic hand-eye coordination","Airborne toss trajectory"],
    ["Model Building","Injection molded sprues","Plastic cement adhesive","Precision hobby scalpel"],
    ["Candle Making","Melted natural soy wax","Centered cotton wick clip","Aromatic fragrance oil"],
    ["Skateboarding","Grip tape kicktail snap","Polyurethane curb slide","Ollie jump control"],
    ["Puzzles","Interlocking cardboard tabs","Frame border edge assembly","1000 piece illustration"],
    ["Writing","Structured story chapter drafts","Creative prose dialogue","Character development notes"]
  ],
  "Extreme Ideas": [
    ["Déjà Vu","Familiar","Memory","Cryptomnesia"],
    ["Paradox","Contradiction","Self-referential","Zeno"],
    ["Nostalgia","Past","Longing","Anemoia"],
    ["Butterfly Effect","Ripple","Sensitivity","Lorenz"],
    ["Identity","Self","Continuity","Theseus"],
    ["Free Will","Choice","Determinism","Compatibilism"],
    ["Parallel Universe","Alternate","Branching","Everett"],
    ["Collective Memory","Shared","Oral history","Halbwachs"],
    ["Optical Illusion","Perception","Gestalt","Ambiguous figure"],
    ["Social Contract","Agreement","Hobbes","Leviathan"],
    ["Infinite Loop","Repeat","Recursion","Stack overflow"],
    ["Uncanny Valley","Almost human","Robotics","Mori"],
    ["Moral Dilemma","Trolley problem","Consequentialism","Deontology"],
    ["Placebo Effect","Belief","Nocebo","Expectation"],
    ["Time Perception","Duration","Chronostasis","Tachypsychia"],
    ["Quantum Entanglement","Spooky action at distance","Instantaneous state collapse","Paired spin particles"],
    ["Simulation Hypothesis","Algorithmic matrix reality","Virtual universe construct","Base reality riddle"],
    ["Solipsism","Only one conscious mind","Unverifiable external world","Self alone is real"],
    ["Schrödinger's Cat","Boxed quantum superposition","Simultaneously alive and dead","Wave function collapse"],
    ["Ship of Theseus","Gradual plank replacement","Persistent object identity","Metaphysical continuity paradox"],
    ["Fermi Paradox","Eerie cosmic silence","High extraterrestrial probability","Great Filter barrier"],
    ["Existential Dread","Cosmic insignificance realization","Search for objective meaning","Void of the cosmos"],
    ["Multiverse","Infinite branching cosmos","Bubble universe cosmology","Many-worlds interpretation"],
    ["Epiphany","Sudden lightning clarity","Profound mental breakthrough","Eureka intuitive leap"],
    ["Singularity","Runaway superintelligence dawn","Technological threshold point","Post-biological horizon"],
    ["Determinism","Unbroken cause and effect","Pre-determined cosmic path","Absence of true randomness"],
    ["Lucid Dreaming","Conscious sleep awareness","Active dream manipulation","Reality check trigger"],
    ["Black Swan Event","Extreme outlier rarity","Massive historical impact","Retrospective rationalization"],
    ["Echo Chamber","Isolated opinion reinforcement","Divergent voice exclusion","Confirmation bias spiral"],
    ["Nihilism","Rejection of intrinsic purpose","Cosmic indifference reality","Deconstruction of morals"]
  ],
  "Celebrity": [
    ["Taylor Swift","Eras","Songwriter","Thirteen"],
    ["Beyoncé","BeyHive","Renaissance","Destiny's Child"],
    ["Dwayne Johnson","The Rock","WWE","Jumanji"],
    ["Tom Cruise","Ethan Hunt","Mission: Impossible","Top Gun"],
    ["Ariana Grande","Ponytail","Whistle Notes","Positions"],
    ["Ed Sheeran","Loop Pedal","Red Hair","Shape of You"],
    ["Lady Gaga","Little Monsters","Poker Face","Chromatica"],
    ["Bruno Mars","Hawaii","Uptown Funk","Silk Sonic"],
    ["Rihanna","Umbrella","Fenty","Barbados"],
    ["Leonardo DiCaprio","Titanic","Oscar","Iceberg"],
    ["Selena Gomez","Rare Beauty","Wizards of Waverly Place","Selena + Chef"],
    ["Zendaya","Euphoria","Dune","Met Gala"],
    ["Chris Hemsworth","Mjolnir","Australia","Thor"],
    ["Billie Eilish","Green Hair","Whisper Vocals","Ocean Eyes"],
    ["Ryan Reynolds","Deadpool Suit","Canada","Deadpool"],
    ["Adele","Hello","Someone Like You","London"],
    ["Keanu Reeves","The Matrix","Motorcycle","John Wick's Pencil"],
    ["Jennifer Lopez","Bronx","On the Floor","J.Lo"],
    ["Justin Bieber","Beliebers","Canada","Peaches"],
    ["Morgan Freeman","March of the Penguins","Deep Voice","Shawshank"],
    ["Lionel Messi","Number ten playmaker","World Cup golden ball","Argentine football maestro"],
    ["Cristiano Ronaldo","SIUU jump celebration","Five Champions League titles","Portuguese goal legend"],
    ["Emma Watson","Hermione spellbook charm","UN HeForShe ambassador","Belle in Beauty and the Beast"],
    ["Robert Downey Jr.","Iron Man arc reactor","Charismatic fast-talking lead","Sherlock Holmes deduction"],
    ["Gordon Ramsay","Michelin star standards","Hell's Kitchen shouting","Signature beef wellington"],
    ["Shakira","Hips Don't Lie rhythm","Latin belly dance pop","Waka Waka anthem"],
    ["Jackie Chan","Unassisted death-defying stunts","Choreographed martial arts comedy","Police Story acrobatics"],
    ["Will Smith","Fresh Prince of Bel-Air","Charismatic blockbuster icon","Men in Black neuralyzer"],
    ["Scarlett Johansson","Black Widow combat stance","Sensory voice in Her","Lost in Translation lead"],
    ["Eminem","Hyperspeed Rap God flow","8 Mile rap battle stage","Slim Shady alter ego"],
    ["Michael Jordan","Air Jordan free throw dunk","Six Chicago Bulls rings","Legendary jersey number 23"],
    ["Tom Hanks","Forrest Gump park bench","Cast Away volleyball friend","Beloved American everyman"],
    ["Oprah Winfrey","Historic daytime talk couch","Influence book club choice","Media empire trailblazer"],
    ["Johnny Depp","Captain Jack Sparrow swagger","Eccentric Tim Burton muse","Edward Scissorhands blades"],
    ["Cillian Murphy","Hypnotic blue eye gaze","Oppenheimer fedora silhouette","Peaky Blinders razor flat cap"]
  ]
};

module.exports = { englishCategoriesPart2 };
