const fs = require('fs');

// Helper to build word entries: [word, easy, normal, hard]
// and automatic/explicit detailed explanations for each hint
const englishCategories = {
  "Food": [
    ["Pizza","Round","Delivery","Margherita"],
    ["Burger","Patty","Drive-thru","Smash"],
    ["Sushi","Seaweed","Omakase","Nigiri"],
    ["Ramen","Noodles","Tonkotsu","Tare"],
    ["Fried Chicken","Crispy","Southern","Batter"],
    ["Ice Cream","Scoop","Gelato","Churn"],
    ["Pancakes","Stack","Griddle","Crêpe"],
    ["Donut","Glazed","Yeast","Proofing"],
    ["Chocolate","Cocoa","Tempering","Ganache"],
    ["Spaghetti","Twirl","Al dente","Carbonara"],
    ["Tacos","Tortilla","Carne","Nixtamal"],
    ["Sandwich","Layers","Pressed","Croque"],
    ["Steak","Grill","Marbling","Wagyu"],
    ["Popcorn","Kernel","Hulless","Flint corn"],
    ["Hot Chocolate","Mug","Cacao","Xocolatl"],
    ["Curry","Spice","Turmeric","Massaman"],
    ["Lasagna","Layers","Baked pasta","Bechamel"],
    ["Croissant","Flaky","Butter pastry","Lamination"],
    ["Burrito","Foil wrap","Flour tortilla","Mission style"],
    ["Dim Sum","Bamboo steamer","Tea pairing","Har Gow"],
    ["Waffles","Grid pockets","Iron batter","Belgian style"],
    ["Cheesecake","Graham crust","Dense cream","New York slice"],
    ["Shawarma","Spit roasted","Garlic toum","Middle Eastern wrap"],
    ["Guacamole","Mashed avocado","Lime citrus","Molcajete bowl"],
    ["Paella","Saffron rice","Crispy socarrat","Valencian pan"],
    ["Pretzel","Twisted knot","Coarse rock salt","Lye dipped"],
    ["Churros","Cinnamon sugar","Fluted stick","Dulce de leche"],
    ["Macaroni","Curved elbows","Melted cheddar","Roux sauce"],
    ["Risotto","Arborio rice","Slow stirred","All onda"],
    ["Gyoza","Pan-fried dumpling","Pleated edge","Soy dip"],
    ["Falafel","Fried chickpea ball","Tahini pita","Herb seasoned"]
  ],
  "Drinks": [
    ["Coke","Bubbles","Dark liquid","Phosphoric"],
    ["Coffee","Caffeine","Roasted","Crema"],
    ["Tea","Leaves","Steep","Tannin"],
    ["Milk","White","Pasteurized","Homogenized"],
    ["Lemonade","Citrus","Tart","Muddled"],
    ["Smoothie","Blended","Thick","Cold-pressed"],
    ["Water","Clear","Still","Mineral"],
    ["Juice","Pulp","Squeezed","Pressed"],
    ["Soda","Fizzy","Carbonated","Syrup"],
    ["Milkshake","Thick","Straw","Frosted"],
    ["Espresso","Shot","Demitasse","Ristretto"],
    ["Coconut Water","Tropical","Electrolytes","Endosperm"],
    ["Energy Drink","Wings","Taurine","Guarana"],
    ["Iced Tea","Pitcher","Brewed","Sweet tea"],
    ["Root Beer","Foam","Sassafras","Sarsaparilla"],
    ["Matcha","Green powder","Bamboo whisk","Ceremonial grade"],
    ["Hot Toddy","Honey lemon","Warm whiskey","Spiced clove"],
    ["Kombucha","Fermented tea","Tart SCOBY","Live probiotic"],
    ["Chai Latte","Spiced brew","Cardamom aroma","Steamed milk"],
    ["Mojito","Fresh mint","Lime wedges","Muddled rum"],
    ["Boba Tea","Chewy tapioca","Wide straw","Brown sugar milk"],
    ["Hot Cider","Spiced apple","Cinnamon stick","Mulling spices"],
    ["Frappe","Blended ice","Whipped topping","Foam head"],
    ["Ginger Ale","Spicy root","Pale bubbly","Dry mixer"],
    ["Latte","Espresso base","Velvet microfoam","Steamed pitcher"],
    ["Sparkling Water","Effervescent fizz","Zero calorie","Mineral source"],
    ["Cappuccino","Equal thirds","Cocoa dusting","Thick foam cap"],
    ["Tonic Water","Quinine bitterness","Botanical blend","UV glow"],
    ["Horchata","Cinnamon rice milk","Sweetened vanilla","Mexican spiced"],
    ["Chamomile","Sleepytime brew","Daisy blossoms","Herbal infusion"]
  ],
  "Animals": [
    ["Dog","Tail","Loyal","Canine"],
    ["Cat","Purr","Independent","Feline"],
    ["Lion","Roar","Pride","Mane"],
    ["Tiger","Stripes","Stalk","Bengal"],
    ["Elephant","Trunk","Herd","Pachyderm"],
    ["Giraffe","Neck","Spots","Acacia"],
    ["Monkey","Climb","Troop","Primate"],
    ["Penguin","Waddle","Colony","Flippers"],
    ["Dolphin","Echo","Pod","Sonar"],
    ["Shark","Fin","Cartilage","Ampullae"],
    ["Eagle","Soar","Talon","Raptor"],
    ["Snake","Slither","Venom","Constrictor"],
    ["Turtle","Shell","Slow","Carapace"],
    ["Panda","Bamboo","Reserve","Ailuropoda"],
    ["Kangaroo","Pouch","Mob","Marsupial"],
    ["Wolf","Howling pack","Winter stalker","Alpha canine"],
    ["Owl","Night hunter","Silent feathers","Swivel neck"],
    ["Cheetah","Sprint speed","Teardrop face marks","Savanna sprint"],
    ["Octopus","Eight tentacles","Ink cloud escape","Chromatophores"],
    ["Bear","Winter hibernation","Heavy claws","Grizzly coat"],
    ["Crocodile","V-shaped snout","Ambush hunter","Death roll"],
    ["Flamingo","Pink feathers","Standing on one leg","Filter beak"],
    ["Gorilla","Chest beating","Silverback leader","Troop primate"],
    ["Chameleon","Color camouflage","Tongue flick","Zygodactyl feet"],
    ["Hedgehog","Spiky quills","Rolling into a ball","Nocturnal insectivore"],
    ["Hippo","Mud soaking","River territory","Massive jaw"],
    ["Platypus","Duck-billed","Egg-laying mammal","Venom spur"],
    ["Koala","Eucalyptus leaves","Tree hugger","Marsupial pouch"],
    ["Sloth","Slow motion","Hanging upside down","Canopy algae"],
    ["Beaver","Dam architect","Flat paddle tail","Felled logs"]
  ],
  "Countries": [
    ["Philippines","Islands","Jeepney","Archipelago"],
    ["Japan","Sakura","Bullet train","Wabi-sabi"],
    ["Canada","Maple","Vast","Tundra"],
    ["Brazil","Carnival","Amazon","Cerrado"],
    ["France","Baguette","Chic","Terroir"],
    ["Egypt","Pyramid","Nile","Pharaoh"],
    ["Australia","Outback","Marsupials","Dreamtime"],
    ["India","Spices","Monsoon","Subcontinent"],
    ["Mexico","Tacos","Mariachi","Mesoamerica"],
    ["Thailand","Temple","Pad Thai","Wai"],
    ["Norway","Fjord","Aurora","Hygge"],
    ["Argentina","Tango","Pampas","Asado"],
    ["Kenya","Safari","Savanna","Maasai"],
    ["Italy","Pasta","Renaissance","Campanile"],
    ["Spain","Flamenco","Siesta","Iberian"],
    ["Germany","Speedy Autobahn","Oktoberfest beer","Brandenburg Gate"],
    ["Greece","Acropolis columns","Mediterranean islands","Ancient philosophy"],
    ["Switzerland","Alpine peaks","Neutral diplomacy","Chalet watches"],
    ["South Korea","K-pop fever","Seoul metropolis","Hangeul script"],
    ["United Kingdom","Big Ben chime","Royal monarchy","Union Jack"],
    ["New Zealand","Kiwi wildlife","Southern fjords","Maori Haka"],
    ["Netherlands","Windmill blades","Tulip gardens","Canal dykes"],
    ["Turkey","Bosphorus strait","Bazaar spices","Hagia Sophia dome"],
    ["Iceland","Geyser steam","Volcanic glaciers","Aurora skies"],
    ["Peru","Machu Picchu ruins","Andes altitude","Incan empire"],
    ["Morocco","Sahara gateway","Medina spices","Kasbah clay"],
    ["South Africa","Table Mountain vista","Cape coast","Big Five safari"],
    ["Sweden","Fika coffee ritual","Stockholm islands","Midnight sun"],
    ["Vietnam","Ha Long Bay isles","Lantern town","Mekong river delta"],
    ["Ireland","Emerald Isle hills","Shamrock green","Cliffs of Moher"]
  ],
  "Cities": [
    ["Manila","Bay","Jeepney","Intramuros"],
    ["Tokyo","Shibuya","Meiji","Shinjuku"],
    ["Paris","Eiffel","Arrondissement","Haussmann"],
    ["Seoul","Han River","Hanbok","Gwanghwamun"],
    ["Singapore","Merlion","Hawker","Sentosa"],
    ["London","Tube","Thames","Cockney"],
    ["New York","Skyline","Yellow cab","Boroughs"],
    ["Sydney","Opera House","Harbour","Sandstone"],
    ["Dubai","Burj","Gold souk","Abra"],
    ["Rome","Colosseum","Cobblestone","Forum"],
    ["Bangkok","Tuk-tuk","Wat","Chao Phraya"],
    ["Toronto","CN Tower","Multicultural","Raptors"],
    ["Cairo","Nile","Bazaar","Khedive"],
    ["Barcelona","Gaudí","Ramblas","Modernisme"],
    ["Amsterdam","Canals","Bicycles","Grachten"],
    ["Venice","Gondola waterway","Grand Canal","Campanile square"],
    ["Los Angeles","Hollywood hills","Palm boulevards","Film studios"],
    ["Rio de Janeiro","Christ the Redeemer","Copacabana sands","Sugarloaf mountain"],
    ["Istanbul","Bosphorus bridge","Grand Bazaar maze","Two continent hub"],
    ["San Francisco","Golden Gate bridge","Cable car hills","Foggy bay"],
    ["Berlin","Brandenburg Gate","Historic wall murals","Museum Island"],
    ["Hong Kong","Victoria Harbour","Dense skyline","Star Ferry crossing"],
    ["Las Vegas","Neon Strip casinos","High roller bets","Bellagio fountains"],
    ["Kyoto","Bamboo forest path","Golden Pavilion shrine","Gion geisha district"],
    ["Cape Town","Table Mountain peak","Two oceans shore","Robben Island"],
    ["Prague","Charles Bridge statues","Astronomical clock chime","Old Town square"],
    ["Chicago","Windy City skyline","Deep dish pizza","Millennium park bean"],
    ["Athens","Parthenon ruins","Acropolis rock","Ancient agora"],
    ["Vienna","Classical waltzes","Imperial palaces","Historic coffeehouses"],
    ["Mumbai","Gateway of India","Bollywood cinema","Marine Drive curve"]
  ],
  "Sports": [
    ["Basketball","Hoop","Dribble","Pick-and-roll"],
    ["Football","Touchdown","Snap","Blitz"],
    ["Soccer","Goal","Dribble","Offsides"],
    ["Volleyball","Spike","Rally","Libero"],
    ["Tennis","Racket","Deuce","Topspin"],
    ["Baseball","Diamond","Pitch","ERA"],
    ["Boxing","Gloves","Jab","Southpaw"],
    ["Swimming","Laps","Stroke","Tumble turn"],
    ["Golf","Caddy","Birdie","Handicap"],
    ["Badminton","Shuttlecock","Smash","Rally"],
    ["Cycling","Pedals","Peloton","Cadence"],
    ["Skateboarding","Kickflip","Ollie","Griptape"],
    ["Archery","Bullseye","Draw","Fletching"],
    ["Surfing","Wave","Barrel","Quiver"],
    ["Fencing","Foil","Parry","En garde"],
    ["Hockey","Ice rink surface","Sliding puck","Slapshot power"],
    ["Rugby","Oval leather ball","Scrum pack","Try zone ground"],
    ["Gymnastics","Balance beam","Somersault twist","Chalked vault"],
    ["Bowling","Ten wooden pins","Strike pocket","Polished lane"],
    ["Table Tennis","Rubber paddle","Lightweight ping pong","Spin return"],
    ["Cricket","Wooden wicket","Fast bowler","Crease stance"],
    ["Skiing","Snow slope trail","Carving poles","Slalom gates"],
    ["Track and Field","Baton handover","Sprint starting block","Hurdle clear"],
    ["Rowing","Synchronized oars","Coxswain cadence","Regatta shell"],
    ["Figure Skating","Axel revolution","Gliding steel blade","Choreographed spin"],
    ["Martial Arts","Dojo training mat","Black belt ranking","Kata form"],
    ["Rock Climbing","Belay harness","Safety carabiner","Chalk grip"],
    ["Snowboarding","Halfpipe air","Edge carving","Bindings flex"],
    ["Handball","Fast transition","Goal perimeter crease","Bouncing shot"],
    ["Water Polo","Continuous treading","Cap ear guards","Shot clock whistle"]
  ],
  "Movies": [
    ["Cinema","Screen","Projection","Proscenium"],
    ["Director","Cut","Blocking","Mise en scène"],
    ["Actor","Role","Monologue","Method"],
    ["Villain","Plan","Motive","Antagonist"],
    ["Superhero","Cape","Alter ego","Vigilante"],
    ["Plot Twist","Surprise","Revelation","MacGuffin"],
    ["Soundtrack","Score","Motif","Leitmotif"],
    ["Sequel","Return","Franchise","Canon"],
    ["Animation","Frames","Rigging","Keyframe"],
    ["Documentary","Real","Narration","Cinéma vérité"],
    ["Horror","Scream","Jump scare","Dread"],
    ["Comedy","Laugh","Timing","Pratfall"],
    ["Stunt Double","Danger","Wire","Practical"],
    ["Red Carpet","Premiere","Gown","Paparazzi"],
    ["Credits","Ending","Scroll","Post-credits"],
    ["Cliffhanger","Unresolved finale","Edge of seat suspense","Story pause"],
    ["Prequel","Backstory lore","Early origin","Timeline root"],
    ["Box Office","Ticket revenues","Opening weekend gross","Blockbuster tier"],
    ["Cameo","Surprise celebrity","Uncredited star","Brief appearance"],
    ["Teaser","Short preview","First footage look","Hype trailer"],
    ["Green Screen","Chroma key backdrop","Digital compositing","CGI background"],
    ["Bloopers","Outtake reel","Flubbed dialogue","Laughter breakdown"],
    ["Genre","Stylistic theme","Film category","Narrative tone"],
    ["Protagonist","Lead character journey","Central hero arc","Story guide"],
    ["Climax","Peak confrontation","Decisive moment","Tension summit"],
    ["Scriptwriter","Screenplay pages","Scene sluglines","Dialogue drafts"],
    ["Film Reel","Celluloid strip","Projector spool","Sprocket holes"],
    ["CGI","Digital visual effect","3D computer render","VFX pipeline"],
    ["Studio","Soundstage lot","Production backlot","Executive greenlight"],
    ["Premiere","Gala first screening","Exclusive red carpet","Cast debut"]
  ],
  "TV Shows": [
    ["Episode","Weekly","Runtime","Cliffhanger"],
    ["Season Finale","Ending","Renewal","Wrap"],
    ["Sitcom","Laugh track","Ensemble","Network"],
    ["Reality Show","Voting","Confessional","Elimination"],
    ["Game Show","Prize","Buzzer","Categories"],
    ["Talk Show","Host","Couch","Monologue"],
    ["Streaming","Binge","Autoplay","Buffering"],
    ["Pilot Episode","First","Pickup","Greenlight"],
    ["Cartoon","Animated","Cell","Voice cast"],
    ["Commercial Break","Sponsor","Airtime","Rating"],
    ["Series","Seasons","Renewal","Showrunner"],
    ["Contestant","Challenge","Eliminated","Wild card"],
    ["Subtitle","Caption","Closed","SDH"],
    ["Remote Control","Buttons","Channel","Infrared"],
    ["Studio Audience","Applause","Live","Warmup"],
    ["Binge Watching","Consecutive viewing","Next episode countdown","All night stream"],
    ["Prime Time","Evening broadcast slot","Peak audience share","Flagship lineup"],
    ["Teleprompter","Scrolling presenter script","Glass camera reflector","Live speech prompt"],
    ["Spin-off","Branch character series","New narrative focus","Origin branch"],
    ["Soap Opera","Long-running melodrama","Daily serial twists","Dramatic confrontations"],
    ["Laugh Track","Recorded audience laughter","Audio cue chuckle","Sitcom timing"],
    ["News Anchor","Desk presenter","Breaking news broadcast","Evening bulletin"],
    ["Miniseries","Limited episode run","Self-contained story","Compact season"],
    ["Broadcaster","Television network","Transmission tower","Program distributor"],
    ["Sponsor","Commercial backer","Brand partner funding","Product placement"],
    ["Reruns","Syndicated encore","Nostalgic repeat","Off-prime slot"],
    ["Theme Song","Opening sequence tune","Catchy title melody","Intro chords"],
    ["Voiceover","Narration audio","Off-camera commentary","Story vocal track"],
    ["Spoiler","Unwanted plot leak","Revealed ending twist","Secret ruin"],
    ["Syndication","Local channel rights","Rerun distribution package","Second-run market"]
  ],
  "Video Games": [
    ["Checkpoint","Save","Progress","Autosave"],
    ["Boss Battle","Health bar","Final","Phase"],
    ["Power-Up","Boost","Collect","Mushroom"],
    ["Controller","Buttons","Analog","Haptic"],
    ["Respawn","Return","Spawn point","Cooldown"],
    ["Multiplayer","Lobby","Ping","Matchmaking"],
    ["Quest","Objective","Journal","Waypoint"],
    ["Avatar","Character","Customise","Emote"],
    ["Inventory","Items","Slots","Encumbrance"],
    ["Leaderboard","Rank","Season","ELO"],
    ["Speedrun","Timer","Any%","Glitch"],
    ["Cutscene","Story","Skip","Motion capture"],
    ["Open World","Explore","Sandbox","Emergent"],
    ["Achievement","Unlocked","Trophy","Platinum"],
    ["Final Boss","Ending","Phase","Health gate"],
    ["Loot Box","Random reward chest","Cosmetic drop chance","Microtransaction"],
    ["Game Over","Life pool depleted","Retry prompt screen","Defeat screen"],
    ["Side Quest","Optional task mission","Extra experience points","Non-linear reward"],
    ["Mana","Magical spell pool","Blue resource bar","Arcane energy"],
    ["Stealth","Crouched footstep","Shadow concealment","Silent ambush"],
    ["NPC","Non-player character","Dialogue choice tree","Vendor interaction"],
    ["Co-op","Cooperative party mode","Shared screen partner","Duo campaign"],
    ["Sandbox","Unrestricted building","Physics playground","Open-ended freedom"],
    ["Hit Points","Damage counter pool","Vitality bar","Combat survival"],
    ["Glitch","Code clipping bug","Unexpected collision error","Texture seam"],
    ["Patch","Downloadable update","Balance adjustment notes","Bug resolution"],
    ["Crafting","Resource gathering recipe","Forge combining","Blueprint item"],
    ["Skill Tree","Perk progression path","Ability unlock points","Build specialization"],
    ["Easter Egg","Concealed developer secret","Hidden pop-culture nod","Surprise unlock"],
    ["DLC","Downloadable expansion pack","Bonus map content","Post-release pack"]
  ],
  "Technology": [
    ["Smartphone","Screen","Unlock","Touchscreen"],
    ["Laptop","Portable","Lid","Trackpad"],
    ["Keyboard","Keys","Mechanical","Actuation"],
    ["Mouse","Click","DPI","Optical"],
    ["Internet","Browser","Protocol","Packet"],
    ["Wi-Fi","Signal","Router","SSID"],
    ["Bluetooth","Pair","Wireless","Codec"],
    ["Server","Rack","Hosting","Uptime"],
    ["Programming","Code","Compiler","Syntax"],
    ["Robot","Automated","Servo","Actuator"],
    ["Artificial Intelligence","Model","Training","Transformer"],
    ["Camera","Lens","Aperture","Bokeh"],
    ["Password","Login","Hash","Entropy"],
    ["Database","Records","Query","Schema"],
    ["Algorithm","Steps","Complexity","Heuristic"],
    ["Microchip","Silicon semiconductor","Etched transistor gate","Integrated circuit wafer"],
    ["Cloud Computing","Remote data center","Synchronized storage","Virtual computing"],
    ["Virtual Reality","Stereoscopic headset","Immersive 3D space","Motion tracking visor"],
    ["Drone","Quadcopter propellers","Remote flight pilot","Aerial stabilization"],
    ["Cybersecurity","Firewall barrier","Encrypted protection","Threat defense protocol"],
    ["Smartwatch","Wrist biometric sensor","Step count tracker","Wearable notification"],
    ["Battery","Rechargeable energy cell","Lithium-ion pack","Power reserve amp"],
    ["Touchscreen","Capacitive glass panel","Multi-touch gesture","Haptic feedback surface"],
    ["Satellite","Geostationary orbit","Solar panel array","Signal relay transceiver"],
    ["Operating System","Kernel core manager","Desktop graphical interface","Process scheduler"],
    ["USB","Universal connector port","Removable flash storage","High-speed data bus"],
    ["Browser","URL address navigation","Rendered HTML engine","Multi-tab browsing"],
    ["Router","Packet routing switch","Ethernet cable ports","Local gateway bridge"],
    ["Headphones","Acoustic driver earcups","Noise cancelling circuit","Spatial audio profile"],
    ["3D Printer","Heated extruder nozzle","Layer-by-layer filament","CAD model slicer"]
  ]
};

console.log('Definitions part 1 written.');
module.exports = { englishCategories };
