import {useEffect,useMemo,useState} from "react";
import {categories as dataCategories,forLanguage} from "./word-data";
type Screen="home"|"setup"|"topics"|"reveal"|"firstPlayer"|"imposterReveal"|"clue"|"discussion"|"voting"|"guess"|"result"|"scores"|"settings"|"stats"|"help";
type Player={id:string,name:string,points:number,wins:number,correct:number,rounds:number};
const names=["Alex","Sam","Jordan","Taylor"];
const starters=["Food","Animals","Countries","World Cities","Sports","Movies","TV Shows","Video Games","Technology","School","Jobs","Places","Household Objects","Transportation","Nature","Clothing","Technology Brands","Social Media","Philippine Food","Philippine Cities","Philippine Provinces","Filipino Culture","Filipino Festivals","Filipino Slang","Internet Culture","Fantasy","Block Worlds","Roblox Worlds","Anime","Music","Space","Science","Health","Weather","Holidays","Ocean Life","Travel","Art","Books","Superpowers","Mystery","Camping","Garden","Farm","Office","Kitchen","Bathroom","Party","Childhood","Feelings","Actions","Sounds","Shapes & Colors","Money","Shopping","Construction","Crime & Law","History","Campus Life","Programming","Board Games","Photography","Extreme Ideas"];
const banks=[
["Pizza","Burger","Sushi","Ramen","Fried Chicken","Ice Cream","Pancakes","Donut","Chocolate","Spaghetti","Tacos","Sandwich","Steak","Noodles","Popcorn","Lasagna","Curry","Dumplings","Salad","Waffles"],
["Dog","Cat","Lion","Tiger","Elephant","Giraffe","Monkey","Penguin","Dolphin","Shark","Eagle","Snake","Turtle","Panda","Kangaroo","Otter","Wolf","Owl","Octopus","Cheetah"],
["Philippines","Japan","Canada","Brazil","France","Egypt","Australia","India","Mexico","Thailand","Norway","Argentina","Kenya","Italy","Spain","Germany","Vietnam","Morocco","Chile","Indonesia"],
["Manila","Tokyo","Paris","Seoul","Singapore","London","New York","Sydney","Dubai","Rome","Bangkok","Toronto","Cairo","Mumbai","Barcelona","Nairobi","Lima","Amsterdam","Istanbul","Auckland"],
["Basketball","Football","Soccer","Volleyball","Tennis","Baseball","Boxing","Swimming","Golf","Badminton","Cycling","Skateboarding","Archery","Surfing","Fencing","Rugby","Bowling","Gymnastics","Hockey","Wrestling"],
["Smartphone","Laptop","Keyboard","Mouse","Internet","Wi-Fi","Bluetooth","Server","Programming","Robot","Artificial Intelligence","Camera","Password","Database","Algorithm","Touchscreen","Web Browser","Microchip","Cloud Storage","USB Cable"],
["Teacher","Student","Exam","Classroom","Homework","Blackboard","Mathematics","Science","Library","Principal","Report Card","Recess","Notebook","Pencil","Laboratory","Graduation","Uniform","Project","Attendance","Field Trip"],
["Doctor","Nurse","Programmer","Teacher","Engineer","Chef","Pilot","Lawyer","Police Officer","Farmer","Architect","Designer","Firefighter","Dentist","Journalist","Mechanic","Photographer","Accountant","Barber","Scientist"],
["Airport","Hospital","School","Mall","Beach","Restaurant","Hotel","Park","Museum","Library","Cinema","Bakery","Stadium","Market","Zoo","Pharmacy","Office","Church","Campsite","Playground"],
["Adobo","Sinigang","Lechon","Kare-Kare","Lumpia","Halo-Halo","Pancit","Sisig","Balut","Taho","Bibingka","Champorado","Tinola","Turon","Dinuguan","Longganisa","Puto","Bicol Express","Laing","Chicken Inasal"],
["Dragon","Wizard","Knight","Castle","Magic","Sword","Dungeon","Potion","Monster","Princess","Elf","Goblin","Spellbook","Crystal Ball","Treasure Chest","Unicorn","Fairy","Crown","Quest","Portal"],
["Guitar","Piano","Drums","Violin","Hip-Hop","Jazz","Pop Music","Rock Band","Concert","Microphone","Playlist","Chorus","Melody","Bass","DJ","Album","Encore","Singer","Headphones","Music Festival"],
["Passport","Suitcase","Boarding Pass","Tour Guide","Souvenir","Hostel","Itinerary","Road Trip","Map","Tourist","Currency Exchange","Backpack","Landmark","Flight","Cruise","Reservation","Customs","Adventure","Postcard","Jet Lag"],
["Meme","Going Viral","Clickbait","Reaction Video","Thread","Lurker","Troll","Screenshot","Fan Edit","Unboxing","POV","Challenge","Influencer","Livestream","Copypasta","Avatar","Username","Comment War","Trending Page","Notification"],
["Déjà Vu","Paradox","Nostalgia","Gravity Well","Butterfly Effect","Identity","Free Will","Parallel Universe","Collective Memory","Optical Illusion","Social Contract","Infinite Loop","Uncanny Valley","Moral Dilemma","Placebo Effect","Time Perception","Chaos Theory","Confirmation Bias","Lost Civilization","Simulation"]
];
const legacyCategories=starters.map((name,i)=>({name,words:banks[i%banks.length].map((w,j)=>i>14&&j%4===0?`${w} · ${name}`:w)}));
const ico=(n:string)=>{
 if(n==="gear") return <i className="fa-solid fa-gear" aria-hidden="true"/>;
 if(n==="sun") return <i className="fa-solid fa-sun" aria-hidden="true"/>;
 if(n==="moon") return <i className="fa-solid fa-moon" aria-hidden="true"/>;
 if(n==="play") return <i className="fa-solid fa-play" aria-hidden="true"/>;
 if(n==="back") return <i className="fa-solid fa-chevron-left" aria-hidden="true"/>;
 if(n==="eye") return <i className="fa-solid fa-eye" aria-hidden="true"/>;
 if(n==="shuffle") return <i className="fa-solid fa-shuffle" aria-hidden="true"/>;
 return <i className={`fa-solid fa-${n}`} aria-hidden="true"/>;
};
const getCategoryIcon=(name:string)=>{
 const map:Record<string,string>={
  "Food":"fa-utensils","Pagkain":"fa-utensils","Philippine Food":"fa-bowl-rice",
  "Drinks":"fa-mug-hot","Inumin":"fa-glass-water",
  "Animals":"fa-paw","Hayop":"fa-paw",
  "Countries":"fa-earth-americas","Cities":"fa-city","World Cities":"fa-city","Philippine Cities":"fa-city","Philippine Provinces":"fa-map-location-dot","Lugar":"fa-location-dot","Mga Lugar sa Pilipinas":"fa-mountain-sun","Places":"fa-map-pin",
  "Sports":"fa-volleyball","Palakasan":"fa-futbol",
  "Movies":"fa-film","TV Shows":"fa-tv","Pelikula":"fa-clapperboard",
  "Video Games":"fa-gamepad","Larong Pinoy":"fa-puzzle-piece","Board Games":"fa-chess-board","Roblox Worlds":"fa-cubes","Block Worlds":"fa-cubes-stacked",
  "Technology":"fa-laptop-code","Technology Brands":"fa-microchip","Programming":"fa-code",
  "Jobs":"fa-briefcase","Trabaho":"fa-user-tie",
  "School":"fa-graduation-cap","Paaralan":"fa-school","Campus Life":"fa-book-open-reader",
  "Transportation":"fa-car-side","Sasakyan":"fa-bus-simple",
  "Clothing":"fa-shirt",
  "Household Objects":"fa-couch","Bagay":"fa-box-open","Bahay":"fa-house-chimney","Kitchen":"fa-kitchen-set","Bathroom":"fa-bath","Office":"fa-building",
  "Nature":"fa-tree","Kalikasan":"fa-leaf","Camping":"fa-campground","Garden":"fa-seedling","Farm":"fa-wheat-awn","Ocean Life":"fa-fish","Weather":"fa-cloud-sun",
  "Music":"fa-music",
  "Internet Culture":"fa-hashtag","Social Media":"fa-share-nodes","Brands & Social Media":"fa-icons",
  "Fantasy":"fa-wand-magic-sparkles","Anime":"fa-masks-theater","Superpowers":"fa-bolt",
  "Science & Space":"fa-rocket","Science":"fa-flask","Space":"fa-user-astronaut",
  "Hobbies":"fa-palette","Art":"fa-paintbrush","Photography":"fa-camera","Books":"fa-book",
  "Extreme Ideas":"fa-brain","Mystery":"fa-user-secret","History":"fa-landmark","Crime & Law":"fa-scale-balanced","Money":"fa-money-bill-wave","Shopping":"fa-bag-shopping","Construction":"fa-helmet-safety",
  "Celebrity":"fa-star","Artista":"fa-star","Artista at Aliwan":"fa-microphone-lines","Filipino Culture":"fa-heart","Kulturang Pilipino":"fa-hands-holding-child","Filipino Slang":"fa-comments","Pinoy Slang":"fa-comment-dots","Pista at Tradisyon":"fa-champagne-glasses","Filipino Festivals":"fa-masks-theater","Holidays":"fa-gifts","Party":"fa-cake-candles",
  "Childhood":"fa-child","Feelings":"fa-face-smile","Actions":"fa-person-running","Sounds":"fa-volume-high","Shapes & Colors":"fa-shapes","Health":"fa-heart-pulse","Travel":"fa-plane-departure","Pang-araw-araw na Buhay":"fa-sun"
 };
 const iconClass = map[name] || "fa-shapes";
 return <i className={`fa-solid ${iconClass}`} aria-hidden="true"/>;
};
const getCategoryDescription=(name:string, language:string)=>{
 const descs:Record<string,string>={
  "Food":"Delicious dishes, meals, snacks, and treats from around the world.",
  "Pagkain":"Masasarap na ulam, miryenda, at tradisyonal na pagkaing Pinoy.",
  "Philippine Food":"Popular and iconic Filipino dishes, street foods, and regional delicacies.",
  "Drinks":"Refreshing beverages, sodas, coffees, teas, and specialty drinks.",
  "Inumin":"Mga pampalamig, tradisyonal na inumin, kape, at sari-saring inumin.",
  "Animals":"Wild beasts, friendly pets, birds, sea creatures, and safari wildlife.",
  "Hayop":"Mga alagang hayop, maiilap na hayop sa gubat, at mga lumilipad at lumalangoy.",
  "Countries":"Nations and territories across all continents around the globe.",
  "Cities":"Famous world metropolises, iconic landmarks, and bustling capitals.",
  "World Cities":"Major international destinations and world-famous cities.",
  "Philippine Cities":"Prominent cities and urban centers across Luzon, Visayas, and Mindanao.",
  "Philippine Provinces":"Provinces and island regions known across the Philippines.",
  "Places":"Everyday locations, travel destinations, public spots, and venues.",
  "Lugar":"Mga pamilyar na pook, pasyalan, gusali, at pampublikong lugar.",
  "Mga Lugar sa Pilipinas":"Mga sikat na pasyalan, tanawin, at isla sa buong Pilipinas.",
  "Sports":"Popular team sports, athletics, competitive games, and matches.",
  "Palakasan":"Mga larong pampalakasan, kompetisyon, at pisikal na aktibidad.",
  "Movies":"Film terms, cinematic tropes, blockbuster cinema, and Hollywood magic.",
  "Pelikula":"Mga termino sa pelikula, eksena, at industriya ng sine.",
  "TV Shows":"Television series, streaming favorites, sitcoms, and broadcast formats.",
  "Video Games":"Gaming terms, mechanics, console favorites, and virtual adventures.",
  "Larong Pinoy":"Mga tradisyonal na larong kalye at paboritong libangan ng kabataan.",
  "Board Games":"Tabletop classics, strategy board games, and family party pastimes.",
  "Roblox Worlds":"Popular virtual worlds, obbies, and experiences on Roblox.",
  "Block Worlds":"Sandbox crafting, voxel survival, and block-building dimensions.",
  "Technology":"Digital devices, computing hardware, modern gadgets, and networks.",
  "Technology Brands":"World-leading tech innovators, hardware manufacturers, and software giants.",
  "Programming":"Coding concepts, development workflows, software architecture, and syntax.",
  "Jobs":"Professions, trades, workplace careers, and skilled occupations.",
  "Trabaho":"Iba't ibang hanapbuhay, propesyon, at serbisyong panlipunan.",
  "School":"Classroom life, school subjects, study gear, and academic milestones.",
  "Paaralan":"Buhay-estudyante, silid-aralan, gamit sa klase, at pagsusulit.",
  "Campus Life":"College student culture, university events, dorms, and campus routines.",
  "Transportation":"Vehicles, public transit systems, flights, and road travel.",
  "Sasakyan":"Mga pampublikong sasakyan, pampasaherong biyahe, at sasakyang panlupa't dagat.",
  "Clothing":"Apparel, fashion accessories, everyday wear, and wardrobe essentials.",
  "Household Objects":"Everyday tools, furniture, and appliances found inside the home.",
  "Bagay":"Mga karaniwang gamit, kagamitan sa bahay, at personal na ari-arian.",
  "Bahay":"Mga bahagi ng tahanan, silid, at kasangkapan sa pamamahay.",
  "Kitchen":"Cooking utensils, pantry staples, appliances, and kitchen items.",
  "Bathroom":"Bath essentials, hygiene products, toiletries, and restroom fixtures.",
  "Office":"Workplace furniture, desktop stationery, and office supplies.",
  "Nature":"Natural landscapes, weather wonders, wilderness, and Earth's terrain.",
  "Kalikasan":"Mga anyong lupa, anyong tubig, panahon, at kagandahan ng kapaligiran.",
  "Camping":"Outdoor survival gear, campfire basics, tents, and wild expeditions.",
  "Garden":"Plants, flowers, gardening tools, soil, and backyard greenery.",
  "Farm":"Agriculture, livestock, barn equipment, and countryside harvest.",
  "Ocean Life":"Marine creatures, coral reefs, deep-sea wonders, and coastal life.",
  "Weather":"Atmospheric phenomena, seasons, storms, and climate conditions.",
  "Music":"Instruments, genres, live concerts, melody, and rhythm.",
  "Internet Culture":"Viral memes, social trends, digital slang, and online behavior.",
  "Social Media":"Feeds, followers, viral reels, notifications, and social networks.",
  "Brands & Social Media":"Household brand names, tech platforms, and digital networks.",
  "Fantasy":"Dragons, spells, mythical creatures, knights, and magical lore.",
  "Anime":"Popular Japanese animation tropes, genres, and anime world concepts.",
  "Superpowers":"Extraordinary superhero abilities, psychic powers, and heroic gifts.",
  "Science & Space":"Cosmic wonders, astronomy, physics, experiments, and the universe.",
  "Science":"Scientific discoveries, lab experiments, elements, and natural laws.",
  "Space":"Planets, star clusters, galaxies, astronauts, and deep space exploration.",
  "Hobbies":"Creative crafts, leisure activities, outdoor pursuits, and relaxing pastimes.",
  "Art":"Fine art tools, painting techniques, gallery aesthetics, and drawing mediums.",
  "Photography":"Camera gear, lighting, shutter techniques, and visual composition.",
  "Books":"Literary terms, reading culture, book genres, and storytelling.",
  "Extreme Ideas":"Mind-bending paradoxes, philosophy, consciousness, and deep concepts.",
  "Mystery":"Whodunit clues, unsolved cases, secret agents, and cryptic riddles.",
  "History":"Ancient civilizations, historical eras, empires, and monumental events.",
  "Crime & Law":"Courtroom trials, legal terms, detectives, and criminal investigations.",
  "Money":"Currency, banking, finance, market economics, and wealth terms.",
  "Shopping":"Retail therapy, department stores, bargaining, and checkout carts.",
  "Construction":"Heavy machinery, building tools, materials, and architectural works.",
  "Celebrity":"World-famous musicians, Hollywood icons, and pop-culture megastars.",
  "Artista":"Mga sikat na aktor, aktres, mang-aawit, at personalidad sa Pilipinas.",
  "Artista at Aliwan":"Showbiz, teleserye, konsiyerto, at industriya ng aliwan sa Pilipinas.",
  "Filipino Culture":"Pinoy values, hospitality, customs, and proud national identity.",
  "Kulturang Pilipino":"Mga kaugalian, pagpapahalaga, at natatanging tradisyon ng mga Pilipino.",
  "Filipino Slang":"Lingo, trending colloquialisms, and conversational Pinoy expressions.",
  "Pinoy Slang":"Mga patok na salita, millennial/Gen-Z slang, at usapang kalye.",
  "Filipino Festivals":"Colorful cultural fiestas, street dancing, and religious celebrations.",
  "Pista at Tradisyon":"Mga pista, kapistahan, at nakagawiang pagdiriwang sa Pilipinas.",
  "Holidays":"Global festivities, seasonal holiday traditions, and celebrations.",
  "Party":"Birthday bashes, celebrations, music, decorations, and party games.",
  "Childhood":"Nostalgic playground games, toy memories, and youthful experiences.",
  "Feelings":"Human emotions, mood states, empathy, and heartfelt reactions.",
  "Actions":"Physical movements, dynamic activities, verbs, and athletic motions.",
  "Sounds":"Noises, acoustic echoes, music effects, and auditory sensations.",
  "Shapes & Colors":"Geometric shapes, vibrant hues, shades, and visual palettes.",
  "Health":"Wellness, medicine, fitness, healthcare, and bodily vitality.",
  "Travel":"Vacations, flight itineraries, luggage, and globetrotting adventures.",
  "Pang-araw-araw na Buhay":"Mga gawaing-bahay, araw-araw na rutina, at buhay sa komunidad."
 };
 return descs[name] || (language === "Tagalog" ? `Koleksyon ng mga salita para sa ${name}.` : `Word pack featuring ${name} terms and associations.`);
};
const shuffled=<T,>(x:T[])=>{const a=[...x];for(let i=a.length-1;i;i--){let j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
const explainHint=(word:string,hint:string,language:string,category:string)=>{
 const baseHint=hint.replace(/^Paired with /,"").replace(/^Kaugnay ng /,"").replace(/ connection$/,"").replace(/^Palatandaan: /,"");
 const exact:Record<string,string>={"Pizza:Slice":"Pizza is cut into triangular slices so it can be shared and eaten by hand.","Pizza:Cheese":"Melted cheese is the signature topping that stretches when a pizza slice is lifted.","Pizza:Oven":"Pizza dough and toppings are baked together in a very hot oven.","Coke:Fizzy":"Coke contains carbonation, which creates its fizzy feeling and sound when opened.","Coke:Cola":"Coke is one of the world's best-known cola-flavored soft drinks.","Coke:Bubbles":"Carbon dioxide forms visible bubbles when Coke is opened or poured.","Camera:Shutter":"A camera's shutter opens briefly to let light reach the film or image sensor.","Camera:Lens":"The lens focuses incoming light so a camera can create a sharp photograph.","Camera:Flash":"A flash produces a short burst of light when a scene is too dark for a photo.","Adobo:Toyo":"Toyo is commonly combined with vinegar, garlic, and spices to make Filipino adobo.","Adobo:Suka":"Suka helps preserve adobo and gives its sauce a distinct tangy flavor.","Adobo:Kanin":"Adobo's savory sauce is commonly paired with steamed rice or kanin.","Jeepney:Bayad":"Passengers pass their fare or bayad toward the driver while riding a jeepney.","Jeepney:Ruta":"A jeepney displays and follows a fixed route between familiar stops.","Jeepney:Barker":"A barker calls out destinations and invites passengers to board a jeepney.","Music Festival:Stage":"A music festival uses one or more large stages where artists perform throughout the event.","Music Festival:Crowd":"Music festivals gather large crowds that watch several live performers in one venue.","Music Festival:Wristband":"Festival attendees often wear admission wristbands that allow entry to stages and event areas.","Dolly de Leon:Triangle":"“Triangle” refers to Triangle of Sadness, the internationally acclaimed film featuring Dolly de Leon as Abigail.","Dolly de Leon:Golden Globe":"Dolly de Leon received a Golden Globe nomination for her performance in Triangle of Sadness.","Dolly de Leon:Actress":"Dolly de Leon is a Filipino stage and screen actress known internationally for Triangle of Sadness."};
 exact["Recess:Break"]="Recess is the scheduled break when students pause lessons for rest, play, or a snack.";
 exact["Oras ng Pahinga:Meryenda"]="Karaniwang kumakain ng meryenda ang mga mag-aaral tuwing oras ng pahinga sa paaralan.";
 const people:Record<string,string>={
 "Taylor Swift":"her Eras Tour, autobiographical songwriting, and well-known connection to the number thirteen.","Beyoncé":"her fanbase called the BeyHive, her Renaissance album, and her start in Destiny's Child.","Dwayne Johnson":"his wrestling name The Rock and his career in action films.","Tom Cruise":"his practical stunts, Mission: Impossible films, and pilot role in Top Gun.","Ariana Grande":"her signature ponytail, wide vocal range, and hit album Positions.","Ed Sheeran":"his acoustic guitar performances, red hair, and the song Shape of You.","Lady Gaga":"her Little Monsters fanbase, Poker Face, and the Chromatica era.","Bruno Mars":"his Hawaiian roots, Uptown Funk, and the duo Silk Sonic.","Rihanna":"her hit Umbrella, Fenty brand, and Barbadian roots.","Leonardo DiCaprio":"his role in Titanic, long-awaited Oscar, and famous iceberg film setting.","Selena Gomez":"her Rare brand, Wizards of Waverly Place, and cooking program.","Zendaya":"her roles in Euphoria and Dune and her influence in fashion.","Chris Hemsworth":"his role as Thor, whose signature weapon is a hammer and whose power is thunder.","Billie Eilish":"her early green-haired look, soft vocal style, and the song Ocean Eyes.","Ryan Reynolds":"his red Deadpool suit, Canadian background, and sarcastic comedy style.","Adele":"her hit Hello, emotional ballads, and London background.","Keanu Reeves":"The Matrix, his motorcycle interest, and the pencil story associated with John Wick.","Jennifer Lopez":"her Bronx roots, dance career, and nickname J.Lo.","Justin Bieber":"his Belieber fanbase, Canadian roots, and the song Peaches.","Morgan Freeman":"his instantly recognizable deep narration voice and role in The Shawshank Redemption.",
 "Kathryn Bernardo":"her KathNiel partnership, character Joy in Hello, Love, Goodbye, and box-office success.","Daniel Padilla":"his Supremo nickname, music performances with a guitar, and the KathNiel partnership.","Vice Ganda":"the Unkabogable nickname, comedy-bar roots, and hosting It's Showtime.","Anne Curtis":"her Dyosa nickname, It's Showtime hosting role, and Australian-Filipino background.","Coco Martin":"his character Cardo in Ang Probinsyano and later work as a director.","Bea Alonzo":"her character Basha and the famous film One More Chance.","Piolo Pascual":"his Papa P nickname and career as both singer and leading man.","Sarah Geronimo":"her Popstar Royalty title, hit dance song Tala, and role as a singing coach.","Alden Richards":"his Pambansang Bae nickname, Hello, Love films, and Eat Bulaga history.","Marian Rivera":"her portrayals of Darna and Dyesebel and her popular dance performances.","Dingdong Dantes":"his Kapuso career, motorcycle interest, and Primetime King title.","Nadine Lustre":"the playful President Nadine title, Siargao connection, and Diary ng Panget.","James Reid":"his Careless music label, singing career, and Australian background.","Kim Chiu":"her Chinita Princess nickname, Pinoy Big Brother beginnings, and Fit Check song.","Paulo Avelino":"his portrayal of Heneral Luna's Gregorio del Pilar and leading-man roles.","Judy Ann Santos":"her Teleserye Queen title, culinary career, and iconic role as Mara.","Regine Velasquez":"her Asia's Songbird title and ability to sing very high notes.","Jose Manalo":"his Juan for All hosting, comedy, and Kalyeserye characters.","Empoy Marquez":"his comedy role in Kita Kita, which was largely set in Japan."
 };
 const direct=exact[`${word}:${baseHint}`];if(direct)return direct;
 if(people[word]){
  const key=`${word}:${hint}`;
  const specific:Record<string,string>={
   "Regine Velasquez:Asia's Songbird":"“Asia’s Songbird” is the specific title widely associated with Regine Velasquez and her acclaimed vocal career.",
   "Regine Velasquez:High Notes":"“High Notes” refers to Regine Velasquez’s exceptional vocal range and her ability to sustain powerful high notes.",
   "Regine Velasquez:R2K":"“R2K” refers to Regine Velasquez’s landmark concert and live album project.",
   "Jose Manalo:Lola Tinidora":"“Lola Tinidora” is a specific Kalyeserye character portrayed by Jose Manalo.",
   "Judy Ann Santos:Judy Ann's Kitchen":"“Judy Ann’s Kitchen” is Judy Ann Santos’s cooking program, directly reflecting her culinary work.",
   "Dolly de Leon:Abigail":"“Abigail” is Dolly de Leon’s internationally recognized character in Triangle of Sadness.",
   "Piolo Pascual:Milan":"“Milan” is a specific film starring Piolo Pascual as Lino.",
   "Piolo Pascual:ASAP":"“ASAP” is the variety program where Piolo Pascual has performed and hosted.",
   "James Reid:Palm Dreams":"“Palm Dreams” is a studio album released by James Reid.",
   "Paulo Avelino:Goyo":"“Goyo” refers to Goyo: Ang Batang Heneral, where Paulo Avelino portrayed Gregorio del Pilar."
  };
  if(specific[key])return specific[key];
  const nickname=new Set(["Rock","J.Lo","KathNiel","Supremo","Unkabogable","Dyosa","Papa P","Popstar","Pambansang Bae","President","Chinita","Teleserye Queen","Primetime King"]);
  const song=new Set(["Shape","Poker Face","Uptown","Umbrella","Hello","Peaches","Tala","Fit Check","Ocean Eyes"]);
  const film=new Set(["Titanic","Matrix","Shawshank","One More Chance","Hello Love","Diary","Kita Kita","Dune"]);
  const role=new Set(["Wizard","Thor","Cardo","Basha","Darna","Dyesebel","Mara","Heneral","Joy"]);
  const place=new Set(["Hawaii","Barbados","London","Bronx","Canada","Australia","Siargao","Japan"]);
  const award=new Set(["Oscar","Golden Globe","Box Office"]);
  const title=new Set(["Renaissance","Positions","Chromatica","Rare","Euphoria","Probinsyano","Bridges"]);
  if(nickname.has(hint))return `“${hint}” is a nickname or public title specifically associated with ${word}.`;
  if(song.has(hint))return `“${hint}” refers to a song closely associated with ${word}.`;
  if(film.has(hint))return `“${hint}” refers to a film or screen project strongly associated with ${word}.`;
  if(role.has(hint))return `“${hint}” refers to a character or acting role portrayed by ${word}.`;
  if(place.has(hint))return `“${hint}” refers to a place connected to ${word} through their origin, upbringing, or notable work.`;
  if(award.has(hint))return `“${hint}” refers to an award, nomination, or major box-office achievement connected to ${word}.`;
  if(title.has(hint))return `“${hint}” refers to a specific album, series, or screen project involving ${word}.`;
 }
 const englishRelation:Record<string,string>={Food:"culinary feature",Drinks:"drink-related feature",Animals:"recognizable trait",Countries:"national identifier",Cities:"city identifier",Sports:"sporting feature",Movies:"film term","TV Shows":"television term","Video Games":"gameplay feature",Technology:"technology feature",Jobs:"workplace detail",School:"school-day detail",Places:"place feature",Transportation:"transport feature",Clothing:"clothing detail","Household Objects":"household feature",Nature:"natural feature",Music:"musical feature","Internet Culture":"online-culture term",Fantasy:"fantasy feature","Science & Space":"scientific feature","Brands & Social Media":"brand feature",Hobbies:"activity detail","Extreme Ideas":"defining concept",Celebrity:"public-career reference"};
 const tagalogRelation:Record<string,string>={Pagkain:"detalye sa pagkain",Inumin:"detalye sa inumin",Hayop:"kilalang katangian",Lugar:"palatandaan ng lugar",Trabaho:"detalye sa trabaho",Kalikasan:"katangian sa kalikasan",Sasakyan:"detalye ng sasakyan",Bagay:"gamit o bahagi ng bagay","Kulturang Pilipino":"detalye sa kulturang Pilipino","Pinoy Slang":"kahulugan sa slang","Artista at Aliwan":"detalye sa aliwan",Artista:"tiyak na detalye sa karera","Larong Pinoy":"bahagi ng laro",Paaralan:"detalye sa buhay-paaralan",Palakasan:"bahagi ng palakasan","Pista at Tradisyon":"detalye sa tradisyon",Bahay:"bahagi ng bahay","Pang-araw-araw na Buhay":"detalye sa pang-araw-araw na gawain","Mga Lugar sa Pilipinas":"kilalang palatandaan ng lugar"};
 return language==="Tagalog"?`Ang “${baseHint}” ang ${tagalogRelation[category]||"tiyak na detalyeng"} direktang kaugnay ng “${word}.”`:`“${baseHint}” describes the ${englishRelation[category]||"defining detail"} directly connected to “${word}.”`;
};
export default function App(){
 const [screen,setScreen]=useState<Screen>("home"),[players,setPlayers]=useState<Player[]>(names.map((name,i)=>({id:"p"+i,name,points:0,wins:0,correct:0,rounds:0}))),[selected,setSelected]=useState(["Food","Animals","Technology"]),[favorites,setFavorites]=useState<string[]>([]),[difficulty,setDifficulty]=useState("Easy"),[mode,setMode]=useState("Classic"),[imposterN,setImposterN]=useState(1),[escape,setEscape]=useState(false),[scoring,setScoring]=useState(false),[imposterHint,setImposterHint]=useState(true),[language,setLanguage]=useState<"English"|"Tagalog"|"Both">("English"),[timerSetting,setTimerSetting]=useState<number|null>(null),[theme,setTheme]=useState("dark"),[motion,setMotion]=useState(true),[rounds,setRounds]=useState(0),[used,setUsed]=useState<string[]>([]),[query,setQuery]=useState("");
 const [word,setWord]=useState(""),[imposterHints,setImposterHints]=useState<Record<string,string>>({}),[hintHistory,setHintHistory]=useState<Record<string,number>>({}),[selectedHint,setSelectedHint]=useState<{player:string;hint:string}|null>(null),[topic,setTopic]=useState(""),[wordLanguage,setWordLanguage]=useState("English"),[order,setOrder]=useState<Player[]>([]),[firstPlayerId,setFirstPlayerId]=useState(""),[voteMode,setVoteMode]=useState<"off"|"normal"|"anonymous">("off"),[imps,setImps]=useState<string[]>([]),[ri,setRi]=useState(0),[shown,setShown]=useState(false),[hasRevealed,setHasRevealed]=useState(false),[publicReveal,setPublicReveal]=useState(false),[ci,setCi]=useState(0),[time,setTime]=useState(0),[votes,setVotes]=useState<Record<string,string>>({}),[vi,setVi]=useState(0),[guess,setGuess]=useState(""),[winner,setWinner]=useState(""),[roundResolved,setRoundResolved]=useState(false),[escapedRound,setEscapedRound]=useState(false);
 const currentLanguageCategories=forLanguage(language),knownEntries=dataCategories.flatMap(c=>c.words);
 const preservedEnglish=legacyCategories.filter(c=>!dataCategories.some(d=>d.language==="English"&&d.name===c.name)).map(c=>({name:c.name,language:"English" as const,words:c.words.map((raw,i)=>{const word=raw.split(" · ")[0],known=knownEntries.find(x=>x.word===word),primary=["Familiar","Everyday","Recognizable","Common pairing","Often seen"][i%5];return{word,hints:known?.hints||[primary,`Linked to ${primary}`,`${primary} clue`],language:"English" as const,difficulty:(i<5?"Easy":i<10?"Normal":i<14?"Hard":"Extreme") as "Easy"|"Normal"|"Hard"|"Extreme"}})}));
 const gameCategories=language==="Tagalog"?currentLanguageCategories:[...currentLanguageCategories,...preservedEnglish],totalWords=gameCategories.reduce((n,c)=>n+c.words.length,0);
 useEffect(()=>{try{let s=JSON.parse(localStorage.getItem("uwp")||"null");if(s){setPlayers(s.players);setFavorites(s.favorites||[]);setTheme(s.theme||"dark");setRounds(s.rounds||0);setUsed(s.used||[]);setLanguage(s.language||"English");setTimerSetting(s.timerSetting===undefined?null:s.timerSetting);setEscape(s.escape??false);setScoring(s.scoring??false);setVoteMode(s.voteMode||"off");setImposterHint(s.imposterHint??true);setHintHistory(s.hintHistory||{})}}catch{}},[]);
 useEffect(()=>{localStorage.setItem("uwp",JSON.stringify({players,favorites,theme,rounds,used,language,timerSetting,escape,scoring,voteMode,imposterHint,hintHistory}));document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle("reduced",!motion)},[players,favorites,theme,rounds,used,motion,language,timerSetting,escape,scoring,voteMode,imposterHint,hintHistory]);
 useEffect(()=>{if(voteMode==="off"&&escape)setEscape(false)},[voteMode,escape]);
 useEffect(()=>{if(timerSetting===null||!time)return;let t=setInterval(()=>setTime(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[time,timerSetting]);
 const go=(s:Screen)=>{setScreen(s);scrollTo(0,0)},top=<header className="top"><button aria-label="Back" onClick={()=>go(screen==="topics"?"setup":"home")}>{ico("back")}</button><img src="/brand-logo.png" alt="BLENDIN Logo" className="brand-logo-mark"/><button aria-label="Settings" onClick={()=>go("settings")}>{ico("gear")}</button></header>;
 const start=()=>{let cs=selected.length?gameCategories.filter(c=>selected.includes(c.name)):gameCategories;if(!cs.length)cs=gameCategories;const wanted=mode==="No Mercy"?["Hard","Extreme"]:difficulty==="Easy"?["Easy"]:difficulty==="Normal"?["Normal"]:difficulty==="Hard"?["Hard"]:["Extreme"];let candidates=cs.flatMap(category=>{const matching=category.words.filter(w=>wanted.includes(w.difficulty));return matching.map(entry=>({entry,category}))});if(!candidates.length)candidates=gameCategories.flatMap(category=>category.words.filter(w=>wanted.includes(w.difficulty)).map(entry=>({entry,category})));const seen=new Set<string>();candidates=candidates.filter(({entry})=>{const key=entry.language+":"+entry.word.trim().toLowerCase();if(seen.has(key))return false;seen.add(key);return true});const wordKey=(entry:(typeof candidates)[number]["entry"])=>"word:"+entry.language+":"+entry.word.trim().toLowerCase();let fresh=candidates.filter(({entry})=>!used.includes(wordKey(entry)));if(!fresh.length){const ranked=[...candidates].sort((a,b)=>used.lastIndexOf(wordKey(a.entry))-used.lastIndexOf(wordKey(b.entry)));fresh=ranked.slice(0,Math.max(1,Math.ceil(ranked.length*.2)))}const pick=fresh[crypto.getRandomValues(new Uint32Array(1))[0]%fresh.length],entry=pick.entry,c=pick.category,n=mode==="Double Imposter"?2:mode==="Chaos"?1+crypto.getRandomValues(new Uint32Array(1))[0]%Math.min(3,players.length-2):imposterN,o=[...players],chosenImps=shuffled(players).slice(0,n).map(p=>p.id),tierOrder=entry.difficulty==="Easy"?[0,1,2]:entry.difficulty==="Normal"?[1,0,2]:entry.difficulty==="Hard"?[1,2,0]:[2,1,0],availableOrder=tierOrder.filter(i=>i<entry.hints.length),historyKey=entry.language+":"+entry.word+":"+entry.difficulty,base=(hintHistory[historyKey]||0)%availableOrder.length,hintMap=Object.fromEntries(chosenImps.map((id,i)=>[id,entry.hints[availableOrder[(base+i)%availableOrder.length]]]));setWord(entry.word);setImposterHints(hintMap);setHintHistory(h=>({...h,[historyKey]:(base+Math.max(1,n))%availableOrder.length}));setWordLanguage(entry.language);setTopic(c.name);setUsed(v=>[...v,wordKey(entry)].slice(-2000));setOrder(o);setFirstPlayerId("");setImps(chosenImps);setRi(0);setShown(false);setHasRevealed(false);setPublicReveal(false);setRoundResolved(false);setEscapedRound(false);setWinner("");setCi(0);setVotes({});setVi(0);setGuess("");setTime(0);go("reveal")};
 const counts=useMemo(()=>Object.values(votes).reduce((a,x)=>(a[x]=(a[x]||0)+1,a),{} as Record<string,number>),[votes]),mx=Math.max(0,...Object.values(counts)),accused=Object.keys(counts).filter(x=>mx>0&&counts[x]===mx),caughtImps=accused.filter(id=>imps.includes(id)),caught=caughtImps.length>0;
 const resolveRound=(win:string,escaped=false)=>{if(roundResolved)return;setWinner(win);setEscapedRound(escaped);setRoundResolved(true);setRounds(x=>x+1);setPlayers(ps=>ps.map(p=>{const imp=imps.includes(p.id),correct=imps.includes(votes[p.id]);const gain=scoring?((win==="players"&&!imp?2:0)+(win==="imposters"&&imp?(escaped?4:3):0)+(correct?1:0)):0;return{...p,points:p.points+gain,wins:p.wins+((win==="players"&&!imp)||(win==="imposters"&&imp)?1:0),correct:p.correct+(correct?1:0),rounds:p.rounds+1}}))};
 const revealRound=()=>{if(publicReveal)return;setPublicReveal(true);if(voteMode==="off"){setRoundResolved(true);setRounds(x=>x+1);setPlayers(ps=>ps.map(p=>({...p,rounds:p.rounds+1})))}else if(!caught)resolveRound("imposters");else if(!escape)resolveRound("players")};
 if(screen==="home")return <main className="shell home"><header><img src="/brand-logo.png" alt="BLENDIN Logo" className="brand-logo-mark"/><button onClick={()=>go("settings")}>{ico("gear")}</button></header><section className="hero"><p>WHO&apos;S THE IMPOSTOR?</p><h1>BLEND<br/><span>IN</span></h1><small>One secret word. Someone is trying to blend in.</small></section><button className="primary big" onClick={()=>go("setup")}>{ico("play")}<span><b>Play</b><small>Set up your perfect round</small></span></button><button className="secondary big" onClick={start}>{ico("shuffle")}<span><b>Quick Play</b><small>Jump in with saved players</small></span></button><nav>{[["topics","Categories","Browse topics"],["stats","Statistics",rounds+" rounds"],["settings","Settings","Rules & display"],["help","How to Play","Learn in 60 sec"]].map(x=><button key={x[0]} onClick={()=>go(x[0] as Screen)}><b>{x[1]}</b><small>{x[2]}</small></button>)}</nav></main>;
 if(screen==="setup")return <main className="shell">{top}<Head over="New game" title="Build your crew" sub="Pass one phone. Trust no clue."/><Card><div className="row"><b>Players <em>{players.length}/15</em></b><button className="text" onClick={()=>setPlayers(shuffled(players))}>{ico("shuffle")} Shuffle</button></div><div className="players">{players.map((p,i)=><label key={p.id}><small>{String(i+1).padStart(2,"0")}</small><input value={p.name} onChange={e=>setPlayers(players.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><button disabled={players.length<=3} onClick={()=>setPlayers(players.filter(x=>x.id!==p.id))}>×</button></label>)}</div><button className="add" disabled={players.length>=15} onClick={()=>setPlayers([...players,{id:crypto.randomUUID(),name:"Player "+(players.length+1),points:0,wins:0,correct:0,rounds:0}])}>+ Add player</button></Card><Card><Label>Language</Label><div className="segments three">{(["English","Tagalog","Both"] as const).map(x=><button key={x} className={language===x?"on":""} onClick={()=>{setLanguage(x);setSelected([])}}>{x}</button>)}</div><div className="row topic-row"><span><b>Topic packs</b><small>{selected.length||"All"} selected</small></span><button className="pill" onClick={()=>go("topics")}>Choose</button></div><Label>Difficulty</Label><div className="segments">{["Easy","Normal","Hard","Extreme"].map(x=><button key={x} className={difficulty===x?"on":""} onClick={()=>setDifficulty(x)}>{x}</button>)}</div><Label>Game mode</Label><div className="modes">{["Classic","Double Imposter","Chaos","Hidden Topic","Known Topic","No Mercy","Quick Round","Troll Mode"].map(x=><button key={x} className={mode===x?"on":""} onClick={()=>setMode(x)}><b>{x}</b><small>{x==="Classic"?"One hidden player":x==="Double Imposter"?"Two hidden players":x==="Chaos"?"Unknown enemy count":x==="Hidden Topic"?"Category stays secret":x==="Known Topic"?"Category is public":x==="No Mercy"?"Hard words only":x==="Quick Round"?"Short timers":"Reverse clue order"}</small></button>)}</div>{mode==="Classic"&&<div className="row line"><span><b>Imposters</b><small>Keep two citizens</small></span><div className="step"><button onClick={()=>setImposterN(Math.max(1,imposterN-1))}>−</button><b>{imposterN}</b><button onClick={()=>setImposterN(Math.min(players.length-2,imposterN+1))}>+</button></div></div>}</Card><Sticky onClick={start} disabled={players.length<3||players.some(p=>!p.name.trim())}>Start game</Sticky></main>;
 if(screen==="topics"){let list=gameCategories.filter(c=>c.name.toLowerCase().includes(query.toLowerCase()));return <main className="shell">{top}<Head over="Word library" title="Choose topics" sub="Mix English and Tagalog packs for unpredictable rounds."/><div className="language-badge">{language} collection</div><div className="search"><input aria-label="Search categories" placeholder="Search categories" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="tools"><button onClick={()=>setSelected(gameCategories.map(c=>c.name))}>Select all</button><button onClick={()=>setSelected([])}>Clear all</button><button onClick={()=>setSelected(shuffled(gameCategories).slice(0,3).map(c=>c.name))}>Random 3</button></div><div className="cats">{list.map((c,i)=>{const desc=getCategoryDescription(c.name,c.language);return <button key={c.language+c.name} className={"cat-btn "+(selected.includes(c.name)?"on":"")} title={`${c.name}: ${desc}`} aria-label={`${c.name} (${c.language}): ${desc}`} onClick={()=>setSelected(v=>v.includes(c.name)?v.filter(x=>x!==c.name):[...v,c.name])}><i className={"cat-icon a"+i%6}>{getCategoryIcon(c.name)}</i><span><b>{c.name}</b><small>{c.language}</small></span><em onClick={e=>{e.stopPropagation();setFavorites(f=>f.includes(c.name)?f.filter(x=>x!==c.name):[...f,c.name])}}>{favorites.includes(c.name)?"★":"☆"}</em><span className="cat-tooltip" role="tooltip">{desc}</span></button>})}</div><Sticky onClick={()=>go("setup")}>Use {selected.length||"all"} categories</Sticky></main>}
 if(screen==="reveal"){let p=order[ri],imp=imps.includes(p.id);const hide=()=>setShown(false),reveal=()=>{setShown(true);setHasRevealed(true)},next=()=>{setShown(false);setHasRevealed(false);if(ri<order.length-1)setRi(ri+1);else{const chosen=players[crypto.getRandomValues(new Uint32Array(1))[0]%players.length];setFirstPlayerId(chosen.id);go("firstPlayer")}};return <main className={"shell reveal-card-screen "+(shown?(imp?"danger":"safe"):"")}><div className="phase"><span>PRIVATE ROLE</span><span>{ri+1} / {order.length}</span></div><div className="bar"><i style={{width:(ri/order.length*100)+"%"}}/></div><header className="reveal-player"><p>Pass the phone to</p><h1>{p.name}</h1><small>Only {p.name} should view the card</small></header><div className="flip-stage"><button className={"flip-card "+(shown?"is-flipped":"")} aria-label="Press and hold to reveal your private role" aria-pressed={shown} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);reveal()}} onPointerUp={hide} onPointerCancel={hide} onPointerLeave={hide} onContextMenu={e=>e.preventDefault()}><span className="flip-inner"><span className="card-face card-front"><i>B</i><em>PLAYER {ri+1}</em><h2>{p.name}</h2><div className="hold-ring">{ico("eye")}</div><b>Press and hold</b><small>Release to hide</small></span><span className={"card-face card-back "+(imp?"imposter-face":"word-face")}><em>{imp?"PRIVATE ROLE":"YOUR WORD"}</em>{imp?<><i className="card-mark">?</i><h2>YOU ARE THE<br/><b>IMPOSTOR</b></h2>{imposterHint&&<aside>Hint<b>{imposterHints[p.id]}</b></aside>}</>:<h2 className="card-word">{word}</h2>}<small>Keep holding to view</small></span></span></button></div><p className="reveal-instruction">{shown?"Release the card before passing the phone.":"Hold the card to check your private role."}</p>{hasRevealed&&<button className="primary next-player" disabled={shown} onClick={next}>{ri<order.length-1?"Next player":"Choose first player"} <span>→</span></button>}</main>}
 if(screen==="firstPlayer"){const first=players.find(p=>p.id===firstPlayerId)||players[0],continueRound=()=>{if(voteMode==="off")go("imposterReveal");else{setVotes({});setVi(0);go("voting")}};return <main className="shell first-player-screen"><div className="phase"><span>FIRST PLAYER</span><span>RANDOM PICK</span></div><section><i>{first.name.slice(0,1).toUpperCase()}</i><p>FIRST TO SPEAK</p><h1>{first.name}</h1><small>{first.name} gives the first clue. Only the first player is randomized, so the group can choose who follows.</small><button className="primary wide" onClick={continueRound}>{voteMode==="off"?"Continue to reveal":"Continue to voting"} →</button></section></main>}
 if(screen==="imposterReveal")return (
  <main className={"shell public-reveal "+(publicReveal?"danger":"")}>
   <div className="phase"><span>ROUND REVEAL</span><span>EVERYONE</span></div>
   <section>
    {!publicReveal ? (
     <>
      <i className="sealed-mark">?</i>
      <p className="eyebrow-public">THE MOMENT OF TRUTH</p>
      <h1>Ready to reveal<br/>the Impostor?</h1>
      <small>Make sure everyone can see the screen.</small>
      <button className="primary wide red" onClick={revealRound}>Reveal the Impostor →</button>
     </>
    ) : (
     <>
      <div className="public-secret"><small>SECRET WORD</small><b>{word}</b></div>
      {voteMode!=="off"&&<div className="combined-votes"><p>VOTE RESULT</p><div className="voteResult">{[...order].sort((a,b)=>(counts[b.id]||0)-(counts[a.id]||0)).map(p=>{const voterNames=order.filter(v=>votes[v.id]===p.id).map(v=>v.name);return <div key={p.id}><i>{p.name[0]}</i><b>{p.name}</b><span><em style={{width:(counts[p.id]||0)/order.length*100+"%"}}/></span><strong>{counts[p.id]||0}</strong>{voteMode==="normal"&&<small className="voter-list">{voterNames.length?"Voted by: "+voterNames.join(", "):"No votes"}</small>}</div>})}</div></div>}
      {voteMode!=="off"&&<div className={"round-verdict "+(winner==="players"?"players-win":"impostor-win")}><small>{caught?"IMPOSTOR CAUGHT":"GROUP VOTED INCORRECTLY"}</small><b>{winner==="players"?"PLAYERS WIN":escapedRound?"THE IMPOSTOR ESCAPED":caught&&escape&&!roundResolved?"FINAL GUESS AVAILABLE":"IMPOSTORS WIN"}</b>{caught&&<span>{caughtImps.map(id=>players.find(p=>p.id===id)?.name).join(" & ")}{caughtImps.length>1?" were":" was"} among the highest-voted players.</span>}</div>}
      <div className="impostor-identity"><i className="unmasked">!</i><p className="eyebrow-public">THE IMPOSTOR{imps.length>1?"S ARE":" IS"}</p><h1>{imps.map(id=>players.find(p=>p.id===id)?.name).join(" & ")}</h1></div>
      <div className="revealed-hints">
       {imps.map(id=>{const player=players.find(p=>p.id===id)?.name||"Impostor",playerHint=imposterHints[id];return <div key={id}><span><small>{player}&apos;s hint</small><b>{playerHint}</b></span><button aria-label={`Explain the connection between ${playerHint} and ${word}`} onClick={()=>setSelectedHint({player,hint:playerHint})}>?</button></div>})}
      </div>
      {(voteMode==="off"||roundResolved)&&<div className="reveal-actions"><button className="primary wide" onClick={start}>Play again →</button><button className="secondary wide" onClick={()=>go("home")}>Return home</button></div>}
      {selectedHint&&<div className="hint-modal-backdrop" role="presentation" onPointerDown={e=>{if(e.target===e.currentTarget)setSelectedHint(null)}}><div className="hint-modal" role="dialog" aria-modal="true" aria-labelledby="hint-title"><button className="modal-close" aria-label="Close explanation" onClick={()=>setSelectedHint(null)}>×</button><i>?</i><p>{selectedHint.player}&apos;s hint</p><h2 id="hint-title">{selectedHint.hint}</h2><div className="hint-equation"><b>{word}</b><span>→</span><b>{selectedHint.hint}</b></div><p className="hint-explanation">{explainHint(word,selectedHint.hint,wordLanguage,topic)}</p><button className="primary wide" onClick={()=>setSelectedHint(null)}>Got it</button></div></div>}
     </>
    )}
   </section>
  </main>
 );
 if(screen==="clue"){let p=order[ci];return <main className="shell"><div className="phase"><span>CLUE PHASE</span><span>{ci+1} OF {order.length}</span></div><div className="bar"><i style={{width:(ci+1)/order.length*100+"%"}}/></div><section className={"turn "+(timerSetting===null?"untimed":"")}><small>IT'S YOUR TURN</small><h2>{p.name}</h2>{mode!=="Hidden Topic"&&<em>Topic: {topic}</em>}{timerSetting!==null&&<Timer time={time}/>}<aside><b>Give one clue out loud</b><p>Say something connected to the word. Be useful, but stay subtle.</p></aside><button className="primary" onClick={()=>{if(ci<order.length-1){setCi(ci+1);setTime(mode==="Quick Round"?15:(timerSetting||0))}else{setTime(timerSetting===null?0:(mode==="Quick Round"?60:Math.min(300,timerSetting*4)));go("discussion")}}}>{ci<order.length-1?"Clue given · Next player":"All clues given · Discuss"} →</button><p>Up next: {order[ci+1]?.name||"Group discussion"}</p></section></main>}
 if(screen==="discussion")return <main className="shell"><div className="phase"><span>OPEN DISCUSSION</span><span>EVERYONE</span></div><section className={"discuss "+(timerSetting===null?"untimed":"")}><i>?</i><h2>Who doesn't belong?</h2><p>Compare clues. Defend your answer. Watch for hesitation.</p>{timerSetting!==null&&<Timer time={time}/>}<div>{order.map((p,i)=><span key={p.id}><b>{i+1}</b>{p.name}</span>)}</div><button className="primary red" onClick={()=>go("voting")}>Start secret voting →</button></section></main>;
 if(screen==="voting"){let voter=order[vi],choice=votes[voter.id];const lockVote=()=>{if(vi<order.length-1){setVi(vi+1);return}if(caught&&escape){go("guess");return}resolveRound(caught?"players":"imposters");setPublicReveal(true);go("imposterReveal")};return <main className="shell"><div className="phase"><span>{voteMode==="normal"?"NORMAL VOTING":"ANONYMOUS VOTING"}</span><span>{vi+1} / {order.length}</span></div><aside className="handoff">Pass to <b>{voter.name}</b>. Voting follows the player list order.</aside><Head over="" title="Who is the Impostor?" sub="Choose one player. You cannot vote for yourself."/><div className="ballot">{order.filter(p=>p.id!==voter.id).map(p=><button key={p.id} className={choice===p.id?"on":""} onClick={()=>setVotes(v=>({...v,[voter.id]:p.id}))}><i>{p.name[0]}</i><b>{p.name}</b><small>{choice===p.id?"Selected":"Tap to vote"}</small></button>)}</div><Sticky disabled={!choice} onClick={lockVote}>{vi===order.length-1?"Lock final vote":"Lock vote & pass"}</Sticky></main>}
 if(screen==="guess"){const caughtNames=caughtImps.map(id=>players.find(p=>p.id===id)?.name).filter(Boolean).join(" & ");const showResult=(win:string,escaped=false)=>{resolveRound(win,escaped);setPublicReveal(true);go("imposterReveal")};const submitGuess=()=>{const correct=guess.trim().toLocaleLowerCase()===word.trim().toLocaleLowerCase();showResult(correct?"imposters":"players",correct)};return <main className="shell reveal danger"><section className="role"><p>IMPOSTOR ESCAPE</p><i className="mark">?</i><h2>THE IMPOSTOR<br/><b>WAS CAUGHT</b></h2><small>Pass the phone to {caughtNames}. {caughtImps.length>1?"They have one shared chance":"They have one chance"} to enter the secret word before it is revealed.</small><label className="guess">SECRET WORD GUESS<input value={guess} onChange={e=>setGuess(e.target.value)} placeholder="Enter your guess" autoComplete="off" autoFocus/></label><button className="primary wide" disabled={!guess.trim()} onClick={submitGuess}>Submit guess →</button><button className="text" onClick={()=>showResult("players")}>Skip and lose</button></section></main>}
 if(screen==="result")return <main className={"shell reveal "+(winner==="players"?"safe":"danger")}><section className="final"><i>{winner==="players"?"V":"X"}</i><p>ROUND COMPLETE</p><h2>{winner==="players"?"PLAYERS WIN":"IMPOSTOR REVEALED"}</h2><small>{winner==="players"?"The crew uncovered the deception.":"The hidden player has been unmasked."}</small><div><span>SECRET WORD<b>{word}</b></span><span>IMPOSTOR{imps.length>1?"S":""}<b>{imps.map(id=>players.find(p=>p.id===id)?.name).join(", ")}</b></span></div>{scoring&&<button className="secondary wide" onClick={()=>go("scores")}>View scoreboard</button>}<button className="primary wide" onClick={start}>Play another round →</button><button className="text" onClick={()=>go("home")}>Return home</button></section></main>;
 if(screen==="scores")return <main className="shell">{top}<Head over="League table" title="Scoreboard" sub="Every bluff and correct read counts."/><div className="score"><header><span>Player</span><span>Pts</span><span>Wins</span><span>Votes</span></header>{[...players].sort((a,b)=>b.points-a.points).map((p,i)=><div><span><i>{i+1}</i><b>{p.name}</b></span><strong>{p.points}</strong><span>{p.wins}</span><span>{p.correct}</span></div>)}</div><button className="primary wide" onClick={start}>Next round →</button></main>;
 if(screen==="settings")return <main className="shell">{top}<Head over="Preferences" title="Game settings" sub="Make every round work for your group."/><Card><Toggle label="Imposter escape" note={voteMode==="off"?"Turn on voting to use the final word guess":"Final word guess after an Impostor is caught"} v={escape} set={setEscape} disabled={voteMode==="off"}/><Toggle label="Imposter hint" note="Show a subtle word-specific association" v={imposterHint} set={setImposterHint}/><Toggle label="Scoring" note="Track wins, votes and points" v={scoring} set={setScoring}/><div className="setting-block"><span><b>Voting system</b><small>Choose whether votes reveal voter names</small></span><div className="segments three setting-segments">{(["off","normal","anonymous"] as const).map(x=><button key={x} className={voteMode===x?"on":""} onClick={()=>{setVoteMode(x);if(x==="off")setEscape(false)}}>{x==="off"?"OFF":x==="normal"?"Normal":"Anonymous"}</button>)}</div></div><div className="setting-block"><span><b>Round timer</b><small>OFF creates a completely untimed game</small></span><div className="timer-options">{([null,15,30,45,60,90] as (number|null)[]).map(x=><button key={x??"off"} className={timerSetting===x?"on":""} onClick={()=>setTimerSetting(x)}>{x===null?"OFF":x+"s"}</button>)}</div></div><Toggle label="Reduced motion" note="Limit interface animations" v={!motion} set={v=>setMotion(!v)}/><div className="row setting"><span><b>Theme</b><small>Choose display style</small></span><div className="segments mini theme-toggle">{[{id:"dark",label:"Dark mode",icon:"moon"},{id:"light",label:"Light mode",icon:"sun"}].map(x=><button key={x.id} aria-label={x.label} title={x.label} className={theme===x.id?"on":""} onClick={()=>setTheme(x.id)}>{ico(x.icon)}</button>)}</div></div></Card></main>;
 if(screen==="stats")return <main className="shell">{top}<Head over="Your group" title="Game statistics" sub="Stored privately on this device."/><div className="stats">{[["Total rounds",rounds],["Players",players.length],["Words seen",used.length],["Favorites",favorites.length]].map(x=><div><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><Card><b>Top detectives</b>{[...players].sort((a,b)=>b.correct-a.correct).map((p,i)=><div className="rank"><i>{i+1}</i><b>{p.name}</b><small>{p.correct} correct votes</small></div>)}</Card></main>;
 return <main className="shell">{top}<Head over="Quick guide" title="How to play" sub="Learn the whole game in one minute."/><div className="steps">{[["01","Set the crew","Add 3–15 players, topics and a mode."],["02","Reveal privately","Citizens see the word. Imposters do not."],["03","Give clues","Say one related clue without exposing the answer."],["04","Discuss & vote","Compare stories and cast private ballots."],["05","Reveal the truth","Catch the Imposter before they escape."]].map(x=><div><i>{x[0]}</i><span><b>{x[1]}</b><p>{x[2]}</p></span></div>)}</div><button className="primary wide" onClick={()=>go("setup")}>Set up a game →</button></main>
}
function Head({over,title,sub}:{over:string,title:string,sub:string}){return <header className="head"><p>{over}</p><h1>{title}</h1><small>{sub}</small></header>}
function Card({children}:{children:React.ReactNode}){return <section className="card">{children}</section>}
function Label({children}:{children:React.ReactNode}){return <p className="label">{children}</p>}
function Sticky({children,onClick,disabled=false}:{children:React.ReactNode,onClick:()=>void,disabled?:boolean}){return <div className="sticky"><button className="primary" disabled={disabled} onClick={onClick}>{children}<span>→</span></button></div>}
function Timer({time}:{time:number}){return <div className={"timer "+(!time?"ended":"")}><b>{String(Math.floor(time/60)).padStart(2,"0")}:{String(time%60).padStart(2,"0")}</b><small>{time?"Time remaining":"Time is up"}</small></div>}
function Toggle({label,note,v,set,disabled=false}:{label:string,note:string,v:boolean,set:(x:boolean)=>void,disabled?:boolean}){return <div className={"row setting "+(disabled?"disabled-setting":"")}><span><b>{label}</b><small>{note}</small></span><button role="switch" aria-checked={v} disabled={disabled} className={"toggle "+(v?"on":"")} onClick={()=>set(!v)}><i/></button></div>}
