export const detailedExplanations: Record<string, string> = {
 // Food
 "Pizza:Slice": "Pizza is baked as a whole round pie and sliced into wedges, making single slices the most recognizable way people eat and serve it.",
 "Pizza:Cheese": "Melted mozzarella stretches into stringy layers across the crust, giving pizza its signature savory richness.",
 "Pizza:Oven": "High-temperature wood-fired or deck ovens cook the crust quickly, crisping the bottom while bubbling the cheese.",
 "Burger:Bun": "Toasted sesame or brioche buns sandwich the patty and toppings together so the burger can be held and eaten.",
 "Sushi:Wasabi": "Spicy green wasabi paste is served alongside sushi to cut through the richness of fresh raw fish.",
 "Ramen:Broth": "Slow-simmered savory broth—such as tonkotsu, miso, or shoyu—serves as the flavorful soul of a bowl of ramen.",
 "Fried Chicken:Crispy": "Deep-fried golden seasoned batter gives the chicken skin its irresistible crunch and texture.",
 "Ice Cream:Cone": "Waffle or sugar cones hold scoops of cold ice cream without needing a spoon or bowl.",
 "Pancakes:Syrup": "Warm maple syrup drizzles over stacked fluffy pancakes, soaking into the batter for sweetness.",
 "Donut:Hole": "The circular cutout in the center allows ring donuts to fry evenly throughout without doughy middles.",
 "Chocolate:Cocoa": "Roasted cocoa beans provide the rich, bittersweet foundation that defines all authentic chocolate.",
 "Spaghetti:Fork": "Long strands of pasta are twirled around a fork against the plate to neatly eat spaghetti and sauce.",
 "Tacos:Shell": "Crispy corn tortillas or warm soft shells cradle seasoned fillings, salsa, and cheese.",
 "Sandwich:Layers": "Bread slices enclose stacked layers of deli meats, cheeses, crisp greens, and savory spreads.",
 "Steak:Grill": "Searing meat over open grill grates creates smoky char marks and locks in succulent juices.",
 "Popcorn:Cinema": "Freshly popped buttery kernels are the quintessential snack enjoyed in movie theaters worldwide.",
 "Hot Chocolate:Marshmallow": "Puffy mini marshmallows float atop warm cocoa, slowly melting into a creamy sweet froth.",
 "Curry:Spice": "Aromatic blends of turmeric, cumin, cardamom, and chili peppers produce curry's deep flavor and golden hue.",

 // Drinks
 "Coke:Fizzy": "Carbonation releases a crisp effervescence and sparkling bite as soon as a cold Coke is poured.",
 "Coke:Cola": "Cola nut extracts and secret botanical flavorings give Coke its distinctive dark caramel taste.",
 "Coke:Bubbles": "Carbon dioxide forms rising micro-bubbles that dance upward against the glass.",
 "Coffee:Caffeine": "Natural stimulant compounds extracted during brewing provide the morning energy boost associated with coffee.",
 "Tea:Teapot": "Dried herbal or black tea leaves steep in hot water inside a ceramic teapot before pouring.",
 "Milk:Calcium": "Dairy milk is widely recognized as a key dietary source of calcium for strong bones and teeth.",
 "Lemonade:Sour": "Freshly squeezed tart lemon juice delivers the sharp, refreshing acidity balanced by sweet syrup in lemonade.",
 "Smoothie:Blender": "High-speed spinning blades pulverize fruits, ice, and yogurt into a thick, drinkable smoothie.",
 "Water:Thirst": "Pure clean water is the body's primary hydrator that immediately quenches dry thirst.",
 "Juice:Pulp": "Natural citrus fibers suspended in the liquid provide authentic fresh-squeezed juice texture.",
 "Soda:Bubbles": "Pressurized carbonation trapped in canned sodas creates fizzy bursts of popping bubbles.",
 "Milkshake:Straw": "Wide-gauge straws allow thick blended ice cream, milk, and sweet syrup to be sipped smoothly.",
 "Espresso:Shot": "High-pressure boiling water forced through fine grounds extracts a concentrated, crema-topped shot of espresso.",
 "Coconut Water:Shell": "Sweet electrolyte-rich coconut water is naturally stored inside the hard fibrous shell of young green coconuts.",
 "Energy Drink:Boost": "Taurine, B-vitamins, and caffeine in energy drinks are formulated to provide an instant burst of stamina.",
 "Iced Tea:Pitcher": "Chilled sweetened tea steeped with lemon slices is traditionally served from a tall frosted pitcher.",
 "Root Beer:Foam": "Sassafras and vanilla flavorings produce a thick creamy head of foam when root beer is poured over ice.",

 // Animals
 "Dog:Bark": "Dogs vocalize with a sharp bark to guard territory, greet companions, or express excitement.",
 "Cat:Whiskers": "Sensitive facial whiskers help cats measure tight spaces and navigate silently in the dark.",
 "Lion:Mane": "A majestic dark ring of thick hair crowns adult male lions, signaling dominance and strength.",
 "Tiger:Stripes": "Vertical camouflage stripes break up a tiger's outline while stalking prey through tall jungle grasses.",
 "Elephant:Trunk": "A powerful elongated muscular snout allows elephants to trumpet, grab food, and shower themselves with water.",
 "Giraffe:Neck": "Exceptionally long vertebrae allow giraffes to browse tender acacia leaves at the tops of tall savanna trees.",
 "Monkey:Banana": "Agile primates are famously associated with peeling and snacking on sweet tropical bananas.",
 "Penguin:Tuxedo": "Counter-shaded black and white plumage gives penguins their tuxedo look while camouflaging them in icy waters.",
 "Dolphin:Echo": "Intelligent marine mammals use high-frequency echolocation clicks to navigate underwater and pinpoint fish.",
 "Shark:Fin": "A sharp triangular dorsal fin slicing through ocean waves is the classic silhouette of a cruising shark.",
 "Eagle:Talon": "Curved razor-sharp talons allow raptors to swoop down from high altitudes and grasp fish or prey securely.",
 "Snake:Slither": "Flexible spines and belly scales enable legless snakes to glide smoothly across ground and branches.",
 "Turtle:Shell": "A hard bony dome carapace provides turtles with a defensive armor fortress they can retract inside.",
 "Panda:Bamboo": "Giant pandas spend up to 12 hours a day munching on tough fibrous stalks of green bamboo.",
 "Kangaroo:Pouch": "Female marsupials carry and nurse their developing joey in a specialized front abdominal pouch.",

 // Technology
 "Laptop:Hinge": "A sturdy mechanical hinge connects the keyboard deck to the display screen, allowing laptops to open and close smoothly.",
 "Smartphone:Touchscreen": "Capacitive glass displays register multi-finger taps, swipes, and pinches to operate smartphone apps.",
 "Keyboard:Keys": "Individual mechanical or membrane switches spring back under fingers to input text and execute shortcuts.",
 "Mouse:Cursor": "Optical laser sensors track desk movements to navigate an on-screen pointer across digital desktop interfaces.",
 "Internet:Browser": "Web browsers decode HTML, styles, and scripts to display global websites across connected networks.",
 "Wi-Fi:Router": "Wireless antennas broadcast high-speed radio frequencies connecting local laptops and phones to the web.",
 "Bluetooth:Pairing": "Short-range wireless handshakes synchronize headphones, smartwatches, and peripherals without cables.",
 "Server:Rack": "Standardized metal frames house stacks of humming enterprise server blades inside climate-controlled data centers.",
 "Programming:Code": "Developers write structured syntax and logic in languages like TypeScript and Python to build functional software.",
 "Robot:Automation": "Programmable sensors, motors, and microcontrollers enable machines to perform repetitive tasks autonomously.",
 "Artificial Intelligence:Model": "Neural networks trained on vast datasets recognize complex patterns to generate text, logic, and predictions.",
 "Camera:Shutter": "A rapid mechanical curtain opens for a fraction of a second to expose the digital sensor to incoming light.",
 "Password:Login": "Encrypted credential strings authenticate user identities before granting access to secured accounts.",
 "Database:Records": "Structured schemas and relational tables organize vast amounts of user information for instant querying.",
 "Algorithm:Steps": "A systematic series of deterministic computational instructions resolves complex logic and calculations.",

 // Countries & Cities
 "Philippines:Islands": "The Philippine archipelago consists of over 7,640 tropical islands surrounded by rich coral seas.",
 "Japan:Sakura": "Pink cherry blossoms burst into delicate bloom each spring, inspiring nationwide hanami flower-viewing festivals.",
 "Canada:Maple": "The iconic red maple leaf symbolizes Canada's vast forests and sweet maple syrup heritage.",
 "Brazil:Carnival": "Electrifying samba drums, dazzling feathered costumes, and vibrant street parades take over Rio during Carnival.",
 "France:Eiffel": "Gustave Eiffel's 330-meter wrought-iron lattice tower stands as the universal symbol of Paris and France.",
 "Egypt:Pyramid": "Ancient monumental stone pyramids built along the Giza plateau have stood for millennia as pharaonic tombs.",
 "Australia:Outback": "Vast, sun-baked red desert wilderness stretches across the remote and rugged heart of Australia.",
 "India:Taj Mahal": "The breathtaking ivory-white marble mausoleum in Agra represents Mughal architectural brilliance.",
 "Mexico:Sombrero": "Wide-brimmed woven sombreros traditionally shield against the blazing desert sun across Mexico.",
 "Thailand:Temple": "Gilded Buddhist wats with tiered golden roofs and spire stupas adorn landscapes across Thailand.",
 "Norway:Fjord": "Deep, glacier-carved saltwater inlets flanked by dramatic sheer mountain cliffs define Norway's coastline.",
 "Argentina:Tango": "Passionate acoustic accordion melodies and dramatic partner steps originated in the historic barrios of Buenos Aires.",
 "Kenya:Safari": "Wildlife expeditions across the Maasai Mara witness the great migrations of lions, zebras, and elephants.",
 "Italy:Boot": "Italy's distinctive peninsular geography extends south into the Mediterranean in the shape of a high-heeled boot.",
 "Spain:Flamenco": "Strummed Spanish guitars, rhythmic hand claps, and passionate heel tapping bring Andalusian flamenco to life.",
 "Manila:Bay": "Golden coastal sunsets over Manila Bay draw crowds along the historic seaside capital promenade.",
 "Tokyo:Shibuya": "Thousands of pedestrians cross simultaneously beneath towering neon video billboards at Shibuya Scramble.",
 "Paris:Eiffel": "The City of Light revolves around the iconic wrought-iron monument overlooking the Seine River.",
 "Seoul:Han River": "The broad Han River cuts through Seoul, bordered by glowing parks, bridges, and bustling night markets.",
 "Singapore:Merlion": "The mythical lion-headed, fish-bodied statue spouts water over Marina Bay as Singapore's national mascot.",
 "London:Big Ben": "The iconic gothic clock tower overlooking the Palace of Westminster chimes the hours across London.",
 "New York:Times Square": "A dazzling canyon of glowing electronic billboards and Broadway marquees defines Midtown Manhattan.",
 "Sydney:Opera House": "Distinctive precast concrete sail roofs jut into Sydney Harbour as an architectural masterpiece.",
 "Dubai:Burj": "Burj Khalifa pierces the desert sky as the world's tallest skyscraper and modern engineering marvel.",
 "Rome:Colosseum": "The massive ancient stone amphitheater once hosted gladiatorial battles in the heart of imperial Rome.",
 "Bangkok:Tuk-tuk": "Colorful, open-air three-wheeled motorized rickshaws weave through Bangkok's vibrant street markets.",
 "Toronto:CN Tower": "The 553-meter concrete communications tower dominates the skyline overlooking Lake Ontario.",
 "Cairo:Nile": "The legendary Nile River flows through Egypt's bustling capital, sustaining civilization for millennia.",
 "Barcelona:Gaudí": "Antoni Gaudí's whimsical modernist architecture culminates in the soaring spires of the Sagrada Família.",
 "Amsterdam:Canals": "Centuries-old concentric canal rings bordered by narrow gabled merchant houses define Amsterdam.",

 // Sports
 "Basketball:Hoop": "Players shoot an orange ball through an elevated iron rim and nylon net ten feet off the ground.",
 "Football:Touchdown": "Crossing into the opponent's end zone with possession of the pigskin awards six points in American football.",
 "Soccer:Goal": "Eleven players pass and strike the ball into a netted goal box without using their hands.",
 "Volleyball:Spike": "Athletes jump high at the net to slam an airborne ball downward into the opponent's court floor.",
 "Tennis:Racket": "Strung composite rackets drive fuzzy yellow balls back and forth over a center net at blistering speeds.",
 "Baseball:Diamond": "Batters sprint around four bases arranged in a diamond after hitting a pitched leather baseball.",
 "Boxing:Gloves": "Padded leather gloves protect knuckles as fighters trade jabs, hooks, and uppercuts inside the ring.",
 "Swimming:Laps": "Swimmers kick and stroke through Olympic-sized pool lanes, touching wall pads to record lap splits.",
 "Golf:Caddy": "An experienced bag carrier advises the golfer on wind conditions, yardages, and club selection.",
 "Badminton:Shuttlecock": "Feathered shuttlecocks flutter and drop rapidly when smashed across a high badminton net.",
 "Cycling:Pedals": "Riders apply leg power to foot pedals that drive chains and spin aerodynamic bicycle wheels.",
 "Skateboarding:Kickflip": "Skaters kick their toes against the grip tape to spin the board 360 degrees mid-air before landing.",
 "Archery:Bullseye": "Archers draw taut bowstrings to release feathered arrows straight into the center yellow target ring.",
 "Surfing:Wave": "Riders paddle out past breaking swells and pop up onto fiberglass boards to carve along curling wave faces.",
 "Fencing:Foil": "Masked duelists lunge and parry with slender steel foils to score electronic touch points on the torso.",

 // Movies & TV
 "Cinema:Screen": "Massive panoramic white screens reflect high-lumen digital projections in darkened movie theaters.",
 "Director:Cut": "The film director shouts 'cut' to halt the camera recording when a scene take is finished.",
 "Actor:Script": "Performers memorize character dialogue, emotional cues, and stage directions printed in the script.",
 "Villain:Scheme": "Antagonists construct sinister master plans that the hero must uncover and stop before it's too late.",
 "Superhero:Cape": "A flowing fabric cape billows behind comic heroes as a striking silhouette of power and rescue.",
 "Plot Twist:Surprise": "An unexpected narrative revelation turns the entire storyline upside down at the climax.",
 "Soundtrack:Score": "Orchestral compositions and emotive background music intensify the dramatic tension of film scenes.",
 "Sequel:Return": "Follow-up movie installments bring beloved characters back for new adventures after a hit release.",
 "Animation:Frames": "Artists sequence thousands of individual illustrated frames per second to create the illusion of lifelike motion.",
 "Documentary:Real": "Non-fiction filmmaking documents real-world historical events, social issues, or natural phenomena.",
 "Horror:Scream": "Frightening jump scares and creepy monsters elicit involuntary screams from terrified theater audiences.",
 "Comedy:Laugh": "Witty timing, funny situations, and slapstick punchlines keep audiences laughing in stitches.",
 "Stunt Double:Danger": "Skilled replacement performers execute dangerous falls, car crashes, and explosions in place of the lead actor.",
 "Red Carpet:Premiere": "Celebrity casts walk down velvet red carpets under flashing paparazzi cameras for theatrical movie premieres.",
 "Credits:Ending": "A scrolling roll of names acknowledges every cast member, visual effects artist, and crew behind the movie.",

 // Video Games
 "Checkpoint:Save": "Stepping into an illuminated checkpoint automatically records player progress so they respawn there if defeated.",
 "Boss Battle:Health Bar": "A massive health bar spanning the screen signals an intense showdown against a powerful area boss.",
 "Power-Up:Boost": "Collecting glowing power-up items grants temporary invulnerability, speed boosts, or upgraded firepower.",
 "Controller:Buttons": "Ergonomic handheld gamepads translate thumbsticks and trigger clicks into responsive in-game actions.",
 "Respawn:Return": "Defeated characters instantly reappear at a respawn beacon to jump right back into the action.",
 "Multiplayer:Lobby": "Online matchmaking lobbies gather players together in party queues before dropping into match servers.",
 "Quest:Objective": "NPCs assign mission markers and reward items for completing storyline objectives across the map.",
 "Avatar:Character": "Players customize virtual avatars with skins, gear, and emotes to represent their gaming identity.",
 "Inventory:Items": "Grid-based bag menus organize weapons, healing potions, crafting resources, and collectible loot.",
 "Leaderboard:Rank": "Competitive rank leaderboards showcase top-scoring players and speedrun record holders worldwide.",
 "Speedrun:Timer": "Precision timers track every split second as speedrunners exploit skips to beat games in record time.",
 "Cutscene:Story": "Cinematic animated cutscenes pause gameplay to deliver dramatic story reveals and character dialogue.",
 "Open World:Explore": "Sprawling seamless game worlds invite players to roam freely beyond linear path boundaries.",
 "Achievement:Unlocked": "Notification banners pop up on screen whenever rare trophies and gameplay milestones are achieved.",
 "Final Boss:Ending": "The climactic multi-stage villain battle guards the ultimate ending credits and victory screen.",

 // School & Jobs
 "Teacher:Lesson": "Educators lead classroom lectures, write on boards, and guide discussions to teach key concepts.",
 "Student:Class": "Learners take notes, ask questions, and collaborate with peers during daily class periods.",
 "Exam:Score": "Graded test scores measure how thoroughly students have mastered the curriculum material.",
 "Classroom:Desks": "Neat rows of student desks and chairs face the teacher's podium and presentation display.",
 "Homework:Deadline": "After-school assignments have strict turn-in deadlines to reinforce concepts studied during the day.",
 "Blackboard:Chalk": "White chalk sticks squeak across dark slate boards to sketch diagrams and equations during class.",
 "Mathematics:Equation": "Balanced mathematical formulas solve for unknown variables using arithmetic and algebraic logic.",
 "Science:Experiment": "Hands-on lab trials test hypotheses using beakers, measurements, and scientific methods.",
 "Library:Books": "Quiet study halls house towering shelves of reference encyclopedias, novels, and literature.",
 "Principal:Office": "School administrators oversee campus safety, student policies, and teacher conferences from the main office.",
 "Report Card:Grades": "End-of-term report cards evaluate academic letter grades and teacher feedback for parents.",
 "Recess:Break": "The school bell rings for a joyful outdoor break where kids play games, run, and eat morning snacks.",
 "Notebook:Lines": "Lined paper notebooks keep handwritten class notes and study guides organized across chapters.",
 "Laboratory:Goggles": "Protective polycarbonate eyewear shields student eyes from chemical splashes and heat in lab experiments.",
 "Graduation:Diploma": "Graduates in caps and gowns walk across the stage to receive parchment diplomas marking their accomplishment.",

 // Household Objects
 "Vase:Bloom": "Ceramic or glass vases hold fresh water to display colorful blooming flower arrangements on tabletops.",
 "Pillow:Sleep": "Soft cushioned pillows support heads and necks comfortably on mattresses through the night.",
 "Umbrella:Rain": "Waterproof fabric canopies pop open at the push of a button to shield against pouring rain showers.",
 "Candle:Flame": "A lit cotton wick melts fragrant wax, casting a gentle warm flicker of ambient candlelight.",
 "Sofa:Cushion": "Padded upholstered couches provide comfortable seating for family lounging in the living room.",
 "Refrigerator:Cold": "Insulated cooling compartments keep perishable groceries, dairy, and leftovers fresh.",
 "Mirror:Reflection": "Silver-backed glass reflects clear optical images for checking outfits, hair, and grooming.",
 "Blanket:Warmth": "Thick woven fleece or wool blankets trap body heat on chilly evenings on the bed or sofa.",
 "Toaster:Bread": "Glowing heating elements toast sliced bread until golden brown and pop it up when ready.",
 "Broom:Sweep": "Bristled broom heads sweep dust, crumbs, and debris off hard floors into a dustpan.",
 "Lamp:Shade": "Translucent lampshades diffuse harsh bulb glare to create soft, cozy ambient lighting in bedrooms.",
 "Curtain:Window": "Hanging drapery panels slide across windows to block bright sunlight and ensure nighttime privacy.",
 "Kettle:Whistle": "Steam pressure blowing through the spout produces a high-pitched whistle when boiling tea water is ready.",
 "Vacuum:Dust": "Powerful motorized suction pulls dust mites, pet hair, and carpet dirt into filtration bins.",
 "Bookshelf:Rows": "Sturdy wooden shelves support rows of hardcovers and paperbacks organized by genre.",

 // Tagalog Packs
 "Adobo:Toyo": "Ang toyo ang nagbibigay ng maalat at maitim na sarsa na pinapakuluan kasama ng suka at bawang sa adobo.",
 "Adobo:Suka": "Suka ang natural na pampaasim at pampatagal ng buhay ng ulam na nagpapakinis sa timpla ng adobo.",
 "Adobo:Kanin": "Mainit at bagong saing na kanin ang perpektong kapares na binubuhusan ng malinamnam na sarsa ng adobo.",
 "Sinigang:Maasim": "Kilala ang sinigang sa matapang at nakakapukaw na asim ng sabaw na humahaplos sa lalamunan.",
 "Sinigang:Sampalok": "Bunga ng sampalok ang tradisyonal at natural na pampaasim sa masarap na sabaw ng sinigang.",
 "Sinigang:Sabaw": "Mainit at maasim na sabaw ang unang hinihigop para magpaginhawa ng katawan lalo na kapag umuulan.",
 "Lechon:Balat": "Ang malutong, mapula, at kumakalutkot na balat ang pinakaaagawan sa bawat handaan kapag may lechon.",
 "Kare-Kare:Mani": "Ginisang mani at peanut butter ang nagpapalapot at nagbibigay ng katakam-takam na kulay at lasa sa kare-kare.",
 "Tinola:Luya": "Hiniwang sariwang luya ang nagtatanggal ng lansa ng manok at nagpapasarap sa sabaw ng tinola.",
 "Sisig:Sizzling": "Inihahain ang tinadtad na pisngi at tainga ng baboy sa mainit at umuusok na sizzling plate.",
 "Lumpia:Balot": "Maninipis na wrapper ang ibinabalot sa masarap na palaman bago ito iprito hanggang maging gintong malutong.",
 "Halo-halo:Yelo": "Pinong kinaskas na yelo ang nagpapalamig sa halo-halong minatamis na saging, gulaman, leche flan, at ube.",
 "Balut:Itik": "Itlog ng itik na may sisiw ang pinakukuluan at kinakain nang may asin at maanghang na suka sa gabi.",
 "Taho:Arnibal": "Matamis at mainit na arnibal kasama ang sago ang ibinubuhos sa malasutlang tokwa ng magtataho sa umaga.",
 "Pancit:Mahaba": "Sumisimbolo ang mahahabang hibla ng pancit sa mahabang buhay at kalusugan tuwing may kaarawan.",
 "Jeepney:Bayad": "Iniaabot ng mga pasahero ang kanilang barya habang sumisigaw ng 'bayad po' patungo sa tsuper.",
 "Jeepney:Ruta": "Nakasulat sa gilid at signboard ng jeepney ang mga rutang dinadaanan nito sa kalsada.",
 "Jeepney:Barker": "Sumisigaw at tumatawag ng pasahero ang barker para mapuno ang jeepney bago umalis sa terminal.",
 "Aso:Tahol": "Tumatahol ang aso kapag may dumarating na bisita o nagbabantay ng bakuran sa gabi.",
 "Pusa:Bigote": "Mahahabang sensitibong bigote sa pisngi ang ginagamit ng pusa sa pagtatantiya ng daraanan sa dilim.",
 "Payong:Ulan": "Binubuksan ang payong para hindi mabasa ang damit at katawan tuwing bumubuhos ang ulan sa lansangan.",
 "Unan:Tulog": "Malambot na unan ang sinasandalan ng ulo para maging mahimbing at komportable ang tulog sa gabi.",
 "Kandila:Apoy": "Maliit na apoy sa mitsa ang nagliliwanag kapag brownout o tuwing nagdarasal sa altar."
};

export const getSmartHintExplanation = (
 word: string,
 hint: string,
 language: string,
 category: string
): string => {
 const baseHint = hint
  .replace(/^Paired with /, "")
  .replace(/^Kaugnay ng /, "")
  .replace(/ connection$/, "")
  .replace(/^Palatandaan: /, "")
  .trim();

 const lookupKey = `${word}:${baseHint}`;
 if (detailedExplanations[lookupKey]) {
  return detailedExplanations[lookupKey];
 }

 // Tagalog dynamic contextual explanations
 if (language === "Tagalog") {
  const tCatHints: Record<string, string> = {
   "Pagkain": `Ang “${baseHint}” ay isang pangunahing sangkap, lasa, o katangiang nagpapakilala sa sarap at luto ng “${word}.”`,
   "Inumin": `Ang “${baseHint}” ay may malapit na kaugnayan sa lasa, paghahain, o pampalamig na katangian ng “${word}.”`,
   "Hayop": `Ang “${baseHint}” ay isang kapansin-pansing katangian, tunog, o pisikal na anyo na agad nagpapaalala sa “${word}.”`,
   "Lugar": `Ang “${baseHint}” ay isang tanyag na palatandaan, pasyalan, o bahagi ng pamumuhay na matatagpuan sa “${word}.”`,
   "Trabaho": `Ang “${baseHint}” ay kagamitan, tungkulin, o larangang ginagampanan ng isang “${word}” sa kanyang serbisyo.`,
   "Kalikasan": `Ang “${baseHint}” ay isang likas na anyo, elemento, o tanawing kaugnay ng kagandahan ng “${word}.”`,
   "Sasakyan": `Ang “${baseHint}” ay isang mahalagang bahagi o karanasan sa pagsakay at pagbiyahe gamit ang “${word}.”`,
   "Bagay": `Ang “${baseHint}” ay naglalarawan sa gamit, bahagi, o gamit sa pang-araw-araw na may kinalaman sa “${word}.”`,
   "Kulturang Pilipino": `Ang “${baseHint}” ay sumasalamin sa mga natatanging kaugalian, pagtitipon, at tradisyong Pilipino kaugnay ng “${word}.”`,
   "Pinoy Slang": `Ang “${baseHint}” ang kahulugan o kontekstong pinagmulan ng patok na salitang “${word}” sa usapang Pinoy.`,
   "Artista at Aliwan": `Ang “${baseHint}” ay mahalagang proyekto, tema, o tagpo sa industriya ng telebisyon at pelikula kaugnay ng “${word}.”`,
   "Artista": `Ang “${baseHint}” ay sumasagisag sa sikat na bansag, teleserye, kanta, o tagumpay sa karera ni “${word}.”`,
   "Larong Pinoy": `Ang “${baseHint}” ay pangunahing kagamitan, galaw, o patakaran sa tradisyonal na larong “${word}.”`,
   "Paaralan": `Ang “${baseHint}” ay mahalagang bahagi ng karanasan, gamit, o aktibidad ng mga mag-aaral sa “${word}.”`,
   "Palakasan": `Ang “${baseHint}” ay pangunahing kagamitan, puntos, o kasanayan na ginagamit sa larong “${word}.”`,
   "Pista at Tradisyon": `Ang “${baseHint}” ay kulay, simbolo, o nakagawiang selebrasyon sa kapistahan ng “${word}.”`,
   "Bahay": `Ang “${baseHint}” ay mahalagang bahagi o kagamitang nagbibigay-buhay sa bawat sulok ng “${word}.”`,
   "Pang-araw-araw na Buhay": `Ang “${baseHint}” ay natural na bahagi ng pang-araw-araw na gawi at karanasan kaugnay ng “${word}.”`,
   "Mga Lugar sa Pilipinas": `Ang “${baseHint}” ay ang tanyag na atraksyon o natatanging tanawin na dinarayo sa “${word}.”`
  };
  if (tCatHints[category]) return tCatHints[category];
  return `Ang “${baseHint}” ay may malinaw at direktang kaugnayan sa katangian at pagkakakilanlan ng “${word}.”`;
 }

 // English dynamic contextual explanations
 const eCatHints: Record<string, string> = {
  "Food": `“${baseHint}” is a key ingredient, serving style, or flavor note that immediately defines “${word}.”`,
  "Drinks": `“${baseHint}” highlights the taste, carbonation, or serving ritual enjoyed with a cold or hot “${word}.”`,
  "Animals": `“${baseHint}” is a distinctive anatomical trait, sound, or natural behavior unique to the “${word}.”`,
  "Countries": `“${baseHint}” is an iconic cultural symbol, landscape, or heritage emblem associated with ${word}.`,
  "Cities": `“${baseHint}” is a world-famous landmark, transit hub, or cultural feature located in ${word}.`,
  "Sports": `“${baseHint}” is an essential piece of equipment, scoring action, or rule in the sport of ${word}.`,
  "Movies": `“${baseHint}” represents a classic storytelling trope, production element, or cinematic convention tied to ${word}.`,
  "TV Shows": `“${baseHint}” captures a defining broadcast format, viewing habit, or episodic feature of ${word}.`,
  "Video Games": `“${baseHint}” is an interactive gameplay mechanic, UI indicator, or milestone encountered in ${word}.`,
  "Technology": `“${baseHint}” is an essential hardware component, protocol, or interface that powers a “${word}.”`,
  "Jobs": `“${baseHint}” is a standard tool, responsibility, or working environment of a professional “${word}.”`,
  "School": `“${baseHint}” is an essential academic item, schedule milestone, or daily classroom detail in “${word}.”`,
  "Places": `“${baseHint}” is a prominent physical fixture, feature, or activity visitors encounter at the “${word}.”`,
  "Transportation": `“${baseHint}” is an integral mechanical part, safety gear, or transit experience of a “${word}.”`,
  "Clothing": `“${baseHint}” is a functional design detail, fabric, or styling feature of “${word}.”`,
  "Household Objects": `“${baseHint}” is the primary function, component, or comfort provided by a “${word}” in the home.`,
  "Nature": `“${baseHint}” is an evocative geological feature, weather pattern, or landscape trait of “${word}.”`,
  "Music": `“${baseHint}” is a fundamental sonic element, instrument component, or performance aspect of ${word}.`,
  "Internet Culture": `“${baseHint}” reflects a viral pattern, social phenomenon, or digital trend tied to “${word}.”`,
  "Fantasy": `“${baseHint}” is a mythical weapon, enchantment, or folklore element found across stories featuring “${word}.”`,
  "Science & Space": `“${baseHint}” is a core physical law, celestial wonder, or experimental principle explaining “${word}.”`,
  "Brands & Social Media": `“${baseHint}” is an iconic feature, product line, or platform mechanic created by ${word}.`,
  "Hobbies": `“${baseHint}” is a hands-on tool, material, or creative technique used when enjoying ${word}.`,
  "Extreme Ideas": `“${baseHint}” is a provocative philosophical insight or psychological phenomenon exploring ${word}.`,
  "Celebrity": `“${baseHint}” directly references a major career milestone, signature role, or public persona of ${word}.`
 };

 if (eCatHints[category]) return eCatHints[category];
 return `“${baseHint}” provides a vivid contextual clue highlighting what makes “${word}” memorable.`;
};
